add_subdirectory(clah)
add_subdirectory(concurrent)
add_subdirectory(debug_info)
add_subdirectory(diagnostic)
add_subdirectory(diagnostic_interactive)
add_subdirectory(filesystem)
add_subdirectory(init)
add_subdirectory(json)
add_subdirectory(logger)
add_subdirectory(printer)
add_subdirectory(query_framework)
add_subdirectory(state_machine)
add_subdirectory(string_id)
add_subdirectory(system_command)
add_subdirectory(tester)
add_subdirectory(timer)
add_subdirectory(tokenizer)
add_subdirectory(llvm)
add_subdirectory(hashing)
add_subdirectory(artifacts)
add_subdirectory(events)
