PostCase: python3 check.py

PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo
  @{duck_exe} init bar
  echo "dependencies:
    bar:
      source:
        path: ../bar
      conditions:
        package-features: [f]

  features:
    f: []" >> foo/quackconfig.yaml

  echo "features:
    b: []" >> bar/quackconfig.yaml

Tests:
  sync:
    Description: can sync a project with dependency and conditions
    Cases:
      sync:
        test_cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
