# Intermediate Statements Tests

Tests:
  while_statement:
    Cases:
      modifying_with_function:
        Input:
          File: "while_statement/modifying_with_function.rtf"
        Output:
          String: "@{begining}\n42\n42\n42\n42\n@{instruction_prompt}@{end}"
  
  for_statement:
    Cases:
      basic_for_usage:
        Input:
          File: "for_statement/basic_for_usage.rtf"
        Output:
          String: "@{begining}\n0\n1\n2\n3\n4\n5\n@{instruction_prompt}@{end}"
      modifying_variable:
        Input:
          File: "for_statement/modifying_variable.rtf"
        Output:
          String: "@{begining}\n@{instruction_prompt}=> 42\n@{end}"