# Tests for box types
Tests:
  simple_boxes:
    Cases:
      all:
        backend: all
        Output:
          String: "42\n123\n1\n2\n99\n100\n"
        ExitCode: 0
      llvm_valgrind:
        backend: llvm
        valgrind: "true"
        TimeOut: 3 # 1 second is often not enough on runners
        Output:
          String: "42\n123\n1\n2\n99\n100\n"
        ExitCode: 0
  box_coercions:
    Cases:
      all:
        backend: all
        Output:
          String: "2\n1\n2\n777\n2\n"
        ExitCode: 0
      llvm_valgrind:
        backend: llvm
        valgrind: "true"
        TimeOut: 3 # 1 second is often not enough on runners 
        Output:
          String: "2\n1\n2\n777\n2\n"
        ExitCode: 0
  reference_kind_collapsing:
    Cases:
      all:
        backend: all
        Output:
          String: "1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n3\n"
        ExitCode: 0
      llvm_valgrind:
        backend: llvm
        valgrind: "true"
        TimeOut: 3 # 1 second is often not enough on runners
        Output:
          String: "1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n3\n"
        ExitCode: 0
