# Tests for statements

Tests:
  numeric_io:
    Cases: 
      llvm:
        backend: llvm
        Input:
          String: "42\n-42\n18446744073709551615\n3.141\n-6.022e+23\n"
        Output:
          String: "42\n-42\n18446744073709551615\n3.141\n-6.022e+23\n"
      # @TODO: #1782 Add dvm test when DVM supports more builtins.
  to_string:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "123.14dtrue()(John Smith,42,1.69)Person(John Smith,42,1.69)"
