# @TODO: #2464 reenable it, currently mangling of symbols inside macros is not correct, and it causes tests that duplicate modules to fail.
enable_conc_deterministic_tests: "false"

Tests:
  simple_expand_1:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "2\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "2\n"
        ExitCode: 0

  simple_expand_2:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "2\n2\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "2\n2\n"
        ExitCode: 0

  simple_expand_3:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n2\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "1\n2\n"
        ExitCode: 0

  expand_expand:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n2\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "1\n2\n"
        ExitCode: 0

  various_statements:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "177\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "177\n"
        ExitCode: 0

  expand_comp_time:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "42\n1\n"
        ExitCode: 0
      # @TODO: #1849 #2483 reenable DVM case, currently it fails because of both
      # the fact that we don't handle string compilation to DVM and that we don't handle
      # constants compilation to DVM.
      # dvm:
      #   backend: dvm
      #   Output:
      #     String: "42\n1\n"
      #   ExitCode: 0


  mangling_in_expand:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n2\n"
        ExitCode: 0

      dvm:
        backend: dvm
        Output:
          String: "1\n2\n"
        ExitCode: 0
