compile_duck: "cmake --build @{build_dir} -- duck"
compile_dvm: "cmake --build @{build_dir} -- VM"

duck_path: "@{build_dir}/bin/duck"
dvm_path: "@{build_dir}/bin/VM"

PreTest: "@{compile_duck}"

SubDirs:
  - cli
  - compilation
