PostCase: python3 check.py && @{cleanup_tmp_env}

PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  @{duck-exe} init bar
  @{duck-exe} -C foo add --local ../bar bar
  echo "features:
    f: []" >> foo/quackconfig.yaml

  echo "features:
    b: []" >> bar/quackconfig.yaml

Tests:
  dep-and-flags:
    Description: can sync a project with dependency, conditions and flags
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Output:
          Run: |+
            echo "info: starting synchronization of the package at \`$DIT_TMP_DIR/foo\`
            info: starting solving the dependency graph
            info: starting gathering the dependency graph
            info: running gathering
            info: starting the solver engine
            info: starting fetching 2 packages
            info: fetched source codes of 2 packages, 0 were downloaded, 2 were alredy present
            info: successfully synchronized venv \`foo\`"
        
