Run: "@{build_dir}/bin//duckc repl"

prompt: "duckling> "
begining: |
  Duckling REPL
  Type /help for available commands, /exit to quit.
  Press Enter for new line, Alt+Enter to submit.

end: "\nGoodbye!\n"
instruction_prompt: "Instruction executed.\n"

SubDirs:
  - working_tests
  # - TO_BE_ADDED
