Run: "@{build_dir}/bin//duckc repl"

prompt: "duckling> "
beginning: |
  Duckling REPL
  Type /help for available commands, /exit to quit.
  Press Enter to submit. Press Alt+Enter for new line.

end: "\nGoodbye!\n"
instruction_prompt: "Instruction executed.\n"

SubDirs:
  - fundamentals
  - intermediate_statements
  - declarations
  - basic_expressions
  - decl_of_functions
  # - multiline
  - script_loading
  - variable_assignment
