compile_duckc: "cmake --build @{build_dir} -j -- duckc"
compile_dvm: "cmake --build @{build_dir} -j -- VM"

duckc_path: "@{build_dir}/bin/duckc"
dvm_path: "@{build_dir}/bin/VM"

PreNode: "@{compile_duckc} && @{compile_dvm}"

SubDirs:
  - features
