compile_duckc: "cmake --build @{build_dir} -j -- duckc"
compile_dvm: "cmake --build @{build_dir} -j -- VM"

duckc_path: "@{build_dir}/bin/duckc"
dvm_path: "@{build_dir}/bin/VM"

# Toolchain is built by the root PreNode.
PreNode: ""

SubDirs:
  - features
