#include "memory/memory.hpp"
#include "stencils/import_stencils.hpp"

#include "memory/memory.hpp"
#include "stencils/import_stencils.hpp"

#include <vm/core/safe/low_program/instruction.hpp>
#include <vm/core/safe/low_program/low_program.hpp>

namespace vm::jit::cnp {
	using JitOpFun = void(const vm::MicroInstruction**, byte**, vm::Frame**, vm::SafeVMThread*);

	JitOpFun* compileCP(const vm::low::LowFuncData& func_data) {
		PUSH_DIAGNOSTIC
		ALLOW_EXTENSIONS
		// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays)
		static constexpr char BIN[] = {
#if __has_embed("stencils-so")
	#embed "stencils-so"
#else
			0
#endif
		};
		POP_DIAGNOSTIC

		// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays)
		static constexpr StencilData DATA[] = {
#if __has_include(<stencils-nm>)
	#include <stencils-nm>  // File generated by `analyze_bin.py`
#else
			StencilData{}
#endif
		};

		static constinit auto stencils
			= Stencils{ .stencils_binary = std::bit_cast<std::array<byte, sizeof(BIN)>>(BIN),
			            .stencils_data   = std::to_array(DATA) };
		auto loaded_stencils = std::move(stencils).load();

		auto opcodes         = func_data.bc | std::views::transform(getInstructionOpcode);
		auto get_opfunc_size = [&](low::MicroOpcode opcode) {
			return loaded_stencils.stencilsData().at(static_cast<u64>(opcode)).size;
		};
		usize size = std::ranges::fold_left(
			opcodes | std::views::transform(get_opfunc_size), 0, std::plus{}
		);

		auto  memory = JitFuncMemory::allocate(size);
		byte* next   = memory.addr;
		for (low::MicroOpcode opcode: opcodes) {
			auto stencil_data = loaded_stencils.stencilsData().at(static_cast<u64>(opcode));
			next              = loaded_stencils.relocate(stencil_data, next);
		}
		return memory.intoFunc<JitOpFun>();
	}
}
