#include "memory/memory.hpp"
#include "stencils/import_stencils.hpp"

#include <vm/core/safe/low_program/instruction.hpp>
#include <vm/core/safe/low_program/low_program.hpp>

#include <expected>
#include <string>

namespace vm::jit::cnp {
	using JitOpFun = void(const vm::MicroInstruction**, byte**, vm::Frame**, vm::SafeVMThread*);

	std::expected<JitOpFun*, std::string> compileCP(const vm::low::LowFuncData& func_data) {
		PUSH_DIAGNOSTIC
		ALLOW_EXTENSIONS
		// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays)
		static constexpr char BIN[] = {
		// Linter doesn't actually build stencils-so so it would be unavailable.
#if __has_embed("stencils-so")
	#embed "stencils-so"
#else
			0
#endif
		};
		POP_DIAGNOSTIC

		// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays)
		static constexpr StencilData DATA[] = {
		// Linter doesn't actually build  so it would be unavailable.
#if __has_include(<stencils-nm>)
	#include <stencils-nm>  // File generated by `analyze_bin.py`
#else
			StencilData{}
#endif
		};

		static constinit auto stencils
			= Stencils{ .stencils_binary = std::bit_cast<std::array<byte, sizeof(BIN)>>(BIN),
			            .stencils_data   = std::to_array(DATA) };
		auto loaded = std::move(stencils).load();
		if (!loaded) return std::unexpected(std::move(loaded).error());
		auto& loaded_stencils = loaded.value();

		auto opcodes         = func_data.bc | std::views::transform(getInstructionOpcode);
		auto get_opfunc_size = [&](low::MicroOpcode opcode) {
			return loaded_stencils.stencilsData().at(static_cast<u64>(opcode)).size;
		};
		usize size = std::ranges::fold_left(
			opcodes | std::views::transform(get_opfunc_size), 0, std::plus{}
		);

		auto memory_result = JitFuncMemory::allocate(size);
		if (!memory_result) return std::unexpected(std::move(memory_result).error());
		auto& memory = memory_result.value();

		byte* next = memory.addr;
		for (low::MicroOpcode opcode: opcodes) {
			auto stencil_data = loaded_stencils.stencilsData().at(static_cast<u64>(opcode));
			next              = loaded_stencils.relocate(stencil_data, next);
		}
		return memory.intoFunc<JitOpFun>();
	}
}
