openapi: 3.0.0
info:
  title: RiftVM API
  description: API reference
  # termsOfService: https://example.com/terms/
  # contact:
  #   name: API Support
  #   url: https://www.example.com/support
  #   email: support@example.com
  # license:
  #   name: Apache 2.0
  #   url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: dev1
servers:
  - url: http://127.0.0.1:5000
    description: Default local server
paths:
  /status/{pid}:
    get:
      description: Get status of process's execution
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          description: Status of the process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '400':
          $ref: '#/components/responses/CoreOperationError'
  
  /process/spawn:
    put:
      description: Create new process
      responses:
        '200':
          description: Created process PID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInfo'
  /process/kill/{pid}:
    delete:
      description: Stop and remove a process
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /process/load/{pid}:
    post:
      description: Load code from file
      parameters:
        - $ref: '#/components/parameters/pid'
      requestBody:
        description: Relative or absolute path to file in .riftbc format
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /process/run/{pid}:
    post:
      description: Run a program
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /process/join/{pid}:
    post:
      description: Wait until a program finishes
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /process/stop/{pid}:
    post:
      description: Force stop a program
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /process/input/{pid}:
    post:
      description: Pass input a standard input into a program
      parameters:
        - $ref: '#/components/parameters/pid'
      requestBody:
        description: Input for a program as string
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /process/output/{pid}:
    get:
      description: Get output from a program
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          description: Output of a program
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /debug/pause/{pid}:
    post:
      description: Pause execution of a program
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /debug/step/{pid}:
    post:
      description: Execute only next instruction
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /debug/resume/{pid}:
    post:
      description: Resume execution of a program
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          $ref: '#/components/responses/Empty'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /data/type/{pid}:
    get:
      description: Get type metadata
      parameters:
        - $ref: '#/components/parameters/pid'
      responses:
        '200':
          description: Type metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
  /data/block/{pid}:
    get:
      description: Get raw data of a block
      parameters:
        - $ref: '#/components/parameters/pid'
        - $ref: '#/components/parameters/block_id'
      responses:
        '200':
          description: Raw data of a block
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '400':
          $ref: '#/components/responses/CoreOperationError'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    ProcessInfo:
      type: object
      required:
        - pid
      properties:
        pid:
          type: integer
          format: int32
          minimum: 0
    Status:
      oneOf:
        - $ref: '#/components/schemas/ExecutionNotStarted'
        - $ref: '#/components/schemas/Parsing'
        - $ref: '#/components/schemas/TypeAnalysis'
        - $ref: '#/components/schemas/Panicked'
        - $ref: '#/components/schemas/Executing'
      discriminator:
        propertyName: type
    ExecutionNotStarted:
      type: object
    Parsing:
      type: object
    TypeAnalysis:
      type: object
    Panicked:
      type: object
      required:
        - exception
      properties:
        exception:
          type: string
    Executing:
      type: object
      required:
        - exec_status
      properties:
        exec_status:
          $ref: '#/components/schemas/ExecutingVariant'
    ExecutingVariant:
      oneOf:
        - $ref: '#/components/schemas/Running'
        - $ref: '#/components/schemas/Paused'
        - $ref: '#/components/schemas/PausedOnError'
        - $ref: '#/components/schemas/WaitingForInput'
        - $ref: '#/components/schemas/NotStarted'
      discriminator:
        propertyName: type
    Running:
      type: object
    Paused:
      type: object
    PausedOnError:
      type: object
      required:
        - reason
      properties:
        reason:
          type: string
    WaitingForInput:
      type: object
    NotStarted:
      type: object
    Output:
      type: object
      required:
        - output
      properties:
        size:
          type: string
    Block:
      type: object
      required:
        - data
      properties:
        data:
          type: string
          format: byte
    Type:
      type: object
      required:
        - size
      properties:
        size:
          type: integer
          format: int64
          minimum: 0
    Empty:
      type: object
    # Errors
    ProcessError:
      oneOf:
        - $ref: '#/components/schemas/ProcessNotFound'
      discriminator:
        propertyName: type
    ProcessNotFound:
      type: object
    CoreOperationError:
      type: object
      required:
        - error
      properties:
        error:
          $ref: '#/components/schemas/CoreOperationErrorVariant'
    CoreOperationErrorVariant:
      oneOf:
        - $ref: '#/components/schemas/ResumeError'
        - $ref: '#/components/schemas/PauseError'
        - $ref: '#/components/schemas/RunError'
        - $ref: '#/components/schemas/JoinError'
        - $ref: '#/components/schemas/OtherError'
        - $ref: '#/components/schemas/LoadProgramError'
      discriminator:
        propertyName: type
    ResumeError:
      type: object
    PauseError:
      type: object
    RunError:
      type: object
    JoinError:
      type: object
    OtherError:
      required:
        - error
      properties:
        error:
          type: string
    LoadProgramError:
      required:
        - why
      properties:
        why:
          type: string
    WrongResponse:
      type: object
  parameters:
    pid:
      name: pid
      in: path
      description: Process ID
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
    block_id:
      name: block_id
      in: path
      description: Block ID
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
  responses:
    Empty:
      description: Empty response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Empty'
    ServerError:
      description: Execution thread error
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ProcessError'
              - $ref: '#/components/schemas/Parsing'
    CoreOperationError:
      description: Execution thread error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CoreOperationError'
