# Expression tests

Tests:
  ternary:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: "9\n9\n9\n18\n4\n"
      llvm:
        backend: llvm
        Output:
          String: "9\n9\n9\n18\n4\n"
  single-comparison: # Any type of comparison between two values.
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  comparison-chain:
    Cases:
#      @TODO: #2179 Re-enable when ops on globals are implemented.
#      dvm:
#        backend: dvm
#        Output:
#          String: ""
#        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0
  unit_simple:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n1\n"
        ExitCode: 0
  unit_simple_multiple_modules:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n1\n"
        ExitCode: 0

  casts:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: "-1\n255\n-1\n-42\n2147483647\n-2147483648\n7\n9\n1\n"
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: "-1\n255\n-1\n-42\n2147483647\n-2147483648\n7\n9\n1\n"
        ExitCode: 0

  floating_point_arithmetic:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  floating_point_comparisons:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  unsigned_integers:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  signed_integers:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  float_32:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  coercions:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0

  zero_init:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "0\n0\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "0\n0\n"
        ExitCode: 0

  strings:
    Cases:
      llvm:
        backend: llvm
        Input:
          String: "Test"
        Output:
          String: "Test\nHello, world!\nab\nbcd\nHello, world!\n"

  chars:
    Cases:
      llvm:
        backend: llvm
        Input:
          String: "Xd;"
        Output:
          String: "Enter a character: The provided character is uppercase.\nIts lowercase counterpart is: x\nEnter a character: The provided character is lowercase.\nIts uppercase counterpart is: D\nEnter a character: The provided character is not a letter.\n"
          
