# Tests for declaration of variables in REPL
ans: => 42\n
ans2: => 30\n
ans2small: => 30\n

Tests:
  basic_declarations:
    Cases:
      basic_declarations:
        Input:
          File: "basic_declarations/basic_declarations.rtf"
        Output: 
          String : "@{beginning}\n=> 42\n@{end}"
      basic_declarations2:
        Input:
          File: "basic_declarations/basic_declarations2.rtf"
        Output: 
          String : "@{beginning}\n=> 3.140000\n@{end}"

  interactions:
    Cases:
      interactions:
        Input:
          File: "interactions/interactions.rtf"
        Output:
          String: "@{beginning}\n=> 42\n@{end}"
      interactions2:
        Input:
          File: "interactions/interactions2.rtf"
        Output:
          String: "@{beginning}\n=> 6.000000\n@{end}"

  multiple_calls:
    Cases:
      multiple_calls:
        Input:
          File: "multiple_calls/multiple_calls.rtf"
        Output:
          String: "@{beginning}\n@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans2}@{ans2}@{ans2small}@{ans2small}@{ans2small}@{end}"
