# Tests for declarations of classes in scripts in Duckling.

# @TODO: #2569 Enable the tests after making usage of classes in REPL and scripts possible.

Tests:
  basic_declarations:
    Enabled: "true"
    folder: "basic_declarations"
    Cases:
      direct:
        mode: direct
        Output: 
          String : "42\n25\n"
      vm:
        mode: vm
        Output:
          String : "42\n25\n"
      exe:
        mode: exe
        Output:
          String : "42\n25\n"
  
  using_previously_defined_objects:
    Enabled: "false"
    folder: "interactions"
    Cases:
      direct:
        mode: direct
        Output:
          String: "12\n"
      vm:
        mode: vm
        Output:
          String: "12\n"
      exe:
        mode: exe
        Output:
          String: "12\n"
