# Tests for statements

Tests:
  blocks:
    Cases:
      all:
        backend: all
        Output:
          String: "42\n42\n42\n"
        ExitCode: 0
  conditional: # if, if-else
    Cases:
      all:
        backend: all
        ExitCode: 99

  declaration_coercions:
    Cases:
      all:
        backend: all
        Output:
          String: "0\n1\n-1\n0\n1\n-1\n0\n1\n-1\n0\n1\n-1\n0\n1\n-1\n"
        ExitCode: 0

  default_initialization:
    # @TODO: #2448 Investigate why deterministic compilation check fails for this test (mangling issue)
    enable_conc_deterministic_tests: "false"
    Cases:
      # @TODO: #3163 When lists are handled in DVM, add a DVM case here
      # and remove `expressions/zero_init` in favour of this test.
      llvm:
        backend: llvm
        Output:
          String: "=================\n0\n0\n0\nA0\n3\n+++++\n0\n0\n0\nA0\n3\n+++++\n1\n1\n1\nACkajak\n+++++\n=================\n0\n1\n0\n=================\n1\n1\n0\n=================\n0\n0\n0\nA=================\n999\n0\n999\n999\n=================\n1\n=================\n1\n123\n"
        ExitCode: 0

  for_static:
    # @TODO: #2448 Investigate why deterministic compilation check fails for this test (mangling issue)
    enable_conc_deterministic_tests: "false"
    Cases:
      all:
        backend: all
        Output:
          String: "888\n1\n2\n888\n123\n123\n888\n1\n2\n888\n100\n200\n888\n1\n2\n888\n1\n1\n2\n2\n1\n2\n888\n1\n2\n3\n4\n888\n1\n0\n888\n1\n3\n1\n2\n"
        ExitCode: 0

  for_dynamic:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "888\n1\n2\n888\n1\n11\n888\n21\n21\n888\n4\n888\n1\n0\n888\n1\n3\n1\n2\n"
        ExitCode: 0        

  loops-performance: # while
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "20\n100000001\n"
        ExitCode: 0
        TimeOut: 1 # 10^8/3 loops should definitely be done in this time.

  destructor_insertion:
    Cases:
      all:
        backend: all
        Output:
          String: "0\n1\n2\n0\n1\n0\n1\n"
        ExitCode: 0

  named_statements:
    Cases:
      all:
        backend: all
        Output:
          String: ""
        ExitCode: 0
