Tests:
  pack:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0
  person:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "JohnDoe30\nJaneSmith23"
        ExitCode: 0
