
Tests:
  dvm_no_strings:
    enable_conc_deterministic_tests: "false"
    Cases:
      all:
        backend: all
        Output:
          String: "10\n20\n15\n35\n15\n35\n"
        ExitCode: 0
  pack:
    enable_conc_deterministic_tests: "false"
    Cases:
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0
  person:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "JohnDoe30\nJaneSmith23\n"
        ExitCode: 0
