PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo @{is_ephemeral}
  @{duck-exe} -C foo sync

Tests:
  basic:
    Description: can get info about a venv of a project
    Cases:
      basic:
        is_ephemeral: ""
        Run: "@{expect_output} --out-regex \"@{stdout_regex}\" --err-regex \"@{stderr_regex}\" @{duck-exe} -C $DIT_TMP_DIR/foo info"
        stderr_regex: ""
        stdout_regex: 'foo:\n  last-location: $DIT_TMP_DIR/foo\n  last-access: @{date-regex}\n  last-modification: @{date-regex}\n  not ephemeral'
      ephemeral:
        is_ephemeral: "--ephemeral"
        Run: "@{expect_output} --out-regex \"@{stdout_regex}\" --err-regex \"@{stderr_regex}\" @{duck-exe} -C $DIT_TMP_DIR/foo info"
        stderr_regex: ""
        stdout_regex: 'foo:\n  last-location: $DIT_TMP_DIR/foo\n  last-access: @{date-regex}\n  last-modification: @{date-regex}\n  ephemeral'
