Tests:
  base:
    Cases:
      all:
        backend: all
        Output:
          String: "4\n1\n23\n4\n1\n4\n4\n8\n4\n8\n76\n"
        ExitCode: 76

SubDirs:
  - expressions
  - comp_time
  - builtins
  - copy_constructors
  - destructors
  - samples
  - statements
  - functions
  - constants
  - classes
  - extern_c
  - ffi
  - static_arrays
  - dynamic_arrays
  - optimisations
  - references
  - boxes
  - variants
  - pointers
  - globals
  - tuples
  - templates
  - imports
  - macros
  - diagnostics
  - packages
  - custom_operators
  - standard_library
  - conditional_compilation
