# Aggregate for all sorts of unit type () peculiarities

Tests:
  unit-as-a-type:
    Description: Test for using implicit value of () as a type.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n2\n3\n4\n5\n6\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "1\n2\n3\n4\n5\n6\n"
        ExitCode: 0
