Tests:
  duck/init/invalid-arguments:
    Description: checks for invalid arguments
    Cases:
      doesnt-panic-when-passed-root:
        test_cmd: duck init /
        ExitCode: 1
        Err:
          String: |+
            error: path \`/\` doesn't have a filename
