PostCase: python3 check.py && @{cleanup_tmp_env}
PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo

Tests:
  sync:
    Description: can sync a new project
    Cases:
      sync:
        test_cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
