
Tests:
  globals:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "4\n1\n3\n4\n"
        ExitCode: 0
      dvm:
        backend: dvm 
        Output:
          String: "4\n1\n3\n4\n"
        ExitCode: 0
