# Note: this workflow currently does nothing.
# in the future we will change it to workflow, that does something.

name: Dummy

on: pull_request

jobs:
  dummy:
    runs-on: ubuntu-24.04
    steps:
      - name: Dummy
        run: echo "This is a dummy workflow"

