PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  @{duck-exe} init bar
  @{duck-exe} -C foo add --local ../bar bar
  rm -rf bar

Tests:
  nonexistent-local-dep:
    Description: cannot sync a project with a nonexistent dependency
    Cases:
      sync:
        test-cmd: duck -C foo sync
        ExitCode: 1
        Err:
          Run: |+
            echo "error: the path \`$DIT_TMP_DIR/bar\` is not a directory"
