# Simplest tests for using lists and arrays in Duckling scripts.

Tests:
  list_length:
    folder: "lists"
    Cases:
      direct:
        mode: direct
        Output:
          String: "6\n"
      vm:
        mode: vm
        Output:
          String: "6\n"
      exe:
        mode: exe
        Output:
          String: "6\n"

  list_access:
    folder: "lists"
    Cases:
      direct:
        mode: direct
        Output:
          String: "2\n4\n6\n"
      vm:
        mode: vm
        Output:
          String: "2\n4\n6\n"
      exe:
        mode: exe
        Output:
          String: "2\n4\n6\n"
