[package]
name = "duck"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "duck"
path = "src/lib/lib.rs"

[[bin]]
name = "duck"

[dependencies]
clap = { version = "4.5.54", features = ["cargo"] }
clap_complete = { version = "4.5.65", optional = true }
color-print = "0.3.7"
console = "0.16.2"
curl = "0.4.49"
dialoguer = "0.12.0"
flate2 = "1.1.9"
git2 = "0.20.3"
indicatif = "0.18.3"
itertools = "0.14.0"
libc = "0.2.182"
libgit2-sys = "0.18.3"
libssh2-sys = "0.3.1"
openssl = "0.10.75"
openssl-sys = "0.9.111"
rusqlite = "0.37.0"
russcip = { version = "0.9.1", features = ["bundled"]}
scip-sys = { version = "0.1.26", features = ["bundled"]}
serde = { version = "1.0.228", features = ["derive"] }
serde-untagged = "0.1.9"
serde_json = "1.0.149"
serde_yaml_ng = "0.10.0"
sha2 = "0.10.9"
shellexpand = "3.1.1"
soft-canonicalize = "0.5.4"
tar = "0.4.44"
tempfile = "3.24.0"
toml = "1.0.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = { version = "2.5.8", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [ "Win32_Foundation", "Win32_System_Console"] }

[dev-dependencies]
httpmock = { version = "0.8.3", default-features = false }

[features]
shell-completion = ["dep:clap_complete"]

bundled-all = ["bundled-sqlite3", "bundled-openssl", "bundled-git2", "bundled-ssh2"]
bundled-git2 = ["libgit2-sys/vendored"]
bundled-openssl = ["openssl/vendored"]
bundled-sqlite3 = ["rusqlite/bundled"]
bundled-ssh2 = ["libssh2-sys/vendored-openssl"]
