[package]
name = "duck"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "duck"
path = "src/lib/lib.rs"

[[bin]]
name = "duck"

[dependencies]
clap = { version = "4.6.0", features = ["cargo"] }
clap_complete = { version = "4.6.0", optional = true }
console = "0.16.3"
const_format = "0.2.35"
curl = "0.4.49"
dialoguer = "0.12.0"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
git2 = "0.20.4"
indicatif = "0.18.4"
itertools = "0.14.0"
libc = "0.2.183"
libgit2-sys = "0.18.3"
libssh2-sys = "0.3.1"
openssl = "0.10.76"
openssl-sys = "0.9.112"
rusqlite = "0.39.0"
russcip = "0.9.1"
scip-sys = "0.1.26"
serde = { version = "1.0.228", features = ["derive"] }
serde-untagged = "0.1.9"
serde_json = "1.0.149"
serde_yaml_ng = "0.10.0"
sha2 = "0.11.0"
shellexpand = "3.1.2"
soft-canonicalize = "0.5.4"
tar = { version = "0.4.45", default-features = false }
tempfile = "3.27.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = { version = "2.5.8", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [ "Win32_Foundation", "Win32_System_Console"] }

[dev-dependencies]
httpmock = { version = "0.8.3", default-features = false }

[features]
# Hack around https://github.com/scipopt/scip-sys/issues/39
default = ["bundled-scip"]

shell-completion = ["dep:clap_complete"]

bundled-all = ["bundled-sqlite3", "bundled-openssl", "bundled-git2", "bundled-ssh2", "bundled-curl", "static-scip"]
bundled-curl = ["curl/static-curl", "curl/force-system-lib-on-osx"]
bundled-git2 = ["libgit2-sys/vendored"]
bundled-openssl = ["openssl/vendored"]
bundled-sqlite3 = ["rusqlite/bundled"]
bundled-ssh2 = ["libssh2-sys/vendored-openssl"]
# NOTE: These two should not be enabled at the same time.
bundled-scip = ["russcip/bundled"]
static-scip = ["russcip/from-source"]
