[package]
name = "duck"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "duck"
path = "src/lib/lib.rs"

[[bin]]
name = "duck"

[dependencies]
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
clap = { version = "4.5.54", features = ["cargo"] }
clap_complete = { version = "4.5.65", optional = true }
console = "0.16.2"
dialoguer = "0.12.0"
git2 = "0.20.3"
indicatif = "0.18.3"
itertools = "0.14.0"
libgit2-sys = "0.18.3"
libssh2-sys = "0.3.1"
openssl = "0.10.75"
openssl-sys = "0.9.111"
ordered-float = "5.1.0" # We have to add it, because saphyr (YAML library) exposes this type explicitly, so we have to pull it in order to use it.
paste = "1.0.15"
reqwest = { version = "0.13.1", features = ["deflate", "gzip", "json", "multipart", "stream"] }
rusqlite = "0.37.0"
russcip = { version = "0.9.1", features = ["bundled"]}
rustvil = { version = "0.9", features = ["full"] }
saphyr = "0.0.6"
serde = { version = "1.0.228", features = ["derive"] }
serde-untagged = "0.1.9"
serde_ignored = "0.1.14"
serde_json = "1.0.149"
serde_yaml_ng = "0.10.0"
symbol_table = { version = "0.5.0", features = ["global", "serde"] }
tempfile = "3.24.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-rusqlite = "0.7.0"
toml = "0.9.11"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
wiremock = "0.6.5"

[features]
shell-completion = ["dep:clap_complete"]

bundled-all = ["bundled-sqlite3", "bundled-openssl", "bundled-git2", "bundled-ssh2"]
bundled-git2 = ["libgit2-sys/vendored"]
bundled-openssl = ["openssl/vendored"]
bundled-sqlite3 = ["rusqlite/bundled"]
bundled-ssh2 = ["libssh2-sys/vendored-openssl"]