PreCase: |+
  @{cd-tmp-dir}
  touch a.dks

Tests:
  basic:
    Description: can run a script
    Cases:
      fast-path:
        test-cmd: duck a.dks
        ExitCode: 1
        Err:
          String: |+
            error: @TODO: #2900 Pass scripts through \`Unit\`s
            
            critical: got the internal error: @TODO: #2900 Pass scripts through \`Unit\`s
            note: run with \`DUCK_BACKTRACE=1\` to see backtraces
            note: Please file a bug report at: https://github.com/ducktype-org/duckling/issues/
      subcommand:
        test-cmd: duck run-script a.dks
        ExitCode: 1
        Err:
          String: |+
            error: @TODO: #2900 Pass scripts through \`Unit\`s
            
            critical: got the internal error: @TODO: #2900 Pass scripts through \`Unit\`s
            note: run with \`DUCK_BACKTRACE=1\` to see backtraces
            note: Please file a bug report at: https://github.com/ducktype-org/duckling/issues/
