# @TODO: #2448 Investigate why deterministic compilation check fails for these tests
enable_conc_deterministic_tests: "false"

Tests:
  no_main_source_file:
    Cases:
      llvm:
        backend: llvm
        # @TODO: #2228 add better output handling here!
        Output:
          String: ""
        Err:
          String: "\u001b[31m\u001b[1merror[E0]\u001b[39m\u001b[0m\u001b[31m\u001b[1m:\u001b[39m\u001b[0m \u001b[1mPackage does not have a main source file.\
            \u001b[39m\u001b[0m\nThe main source file is required for package no_main_source_file. Please add a no_main_source_file.dm file to the package module directory.\n\n"
        ExitCode: 1
