# @TODO: #2448 Investigate why deterministic compilation check fails for these tests
enable_conc_deterministic_tests: "false"

Tests:
  no_main_source_file:
    Cases:
      llvm:
        backend: llvm
        # @TODO: #2228 add better output handling here!
        Output:
          String: ""
        Err:
          String: "\u001b[31m\u001b[1merror[E0]\u001b[39m\u001b[0m\u001b[31m\u001b[1m:\u001b[39m\u001b[0m \u001b[1mPackage does not have a main source file or script.\
            \u001b[39m\u001b[0m\nPackage no_main_source_file must contain either a no_main_source_file.dmf main module file or at least one .ds script at the package root.\n\n"
        ExitCode: 1
