

Tests:
  no_main_source_file:
    Cases:
      llvm:
        backend: llvm
        # @TODO: #2228 add better output handling here!
        Output:
          String: ""
        Err:
          String: "error[E0]: Main package does not have a main source file.\n\
           The main source file is required for compilation.
           Please add a no_main_source_file.dmf file to the main module directory.\n\n"
        ExitCode: 1
