before_cmd: export PATH="$(pwd):$PATH"
duck_home: '.'

Tests:
  test-run-external-subcmd:
    Description: Finds external subcommands
    test_cmd: duck echo External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n

  test-fixes-to-external:
    Description: Can fix typo in external subcommand
    test_cmd: duck ecjo External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n
  test-fixes-to-alias_to_external:
    Description: Aliases can expand to external subcommands
    test_cmd: duck abababq External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n
