# NOTE: 'EOF' needs to be quoted, so $@ is not expanded by the shell.
prepare: |
  cat <<'EOF' > duck-echo
  #!/bin/sh
  echo "$@"
  EOF
  chmod +x duck-echo

before_cmd: export PATH="$(pwd):$PATH" && export DUCK_HOME="$(pwd)"

PostTest: rm duck-echo

Tests:
  test-run-external-subcmd:
    Description: Finds external subcommands
    test_cmd: duck echo External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n

  test-fixes-to-external:
    Description: Can fix typo in external subcommand
    test_cmd: duck ecjo External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n
  test-fixes-to-alias_to_external:
    Description: Aliases can expand to external subcommands
    test_cmd: duck abababq External subcmd

    Cases:
      echo:
        Output:
          String: External subcmd\n
