PostCase: python3 check.py && @{cleanup_tmp_env}

PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  @{duck-exe} init bar
  echo "dependencies:
    bar:
      source:
        path: ../bar
      conditions:
        package-features: [f]
      features:
        - b:
           package-features: [f]

  features:
    f: []" >> foo/quackconfig.yaml

  echo "features:
    b: []" >> bar/quackconfig.yaml

Tests:
  duck/sync-with-a-single-local-dep-and-conditions2:
    Description: can sync a project with dependency and conditions
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
