# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import view_pb2 as view__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in view_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ViewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetView = channel.unary_unary(
                '/view.ViewService/GetView',
                request_serializer=view__pb2.ViewRequest.SerializeToString,
                response_deserializer=view__pb2.ViewResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/view.ViewService/Click',
                request_serializer=view__pb2.ClickRequest.SerializeToString,
                response_deserializer=view__pb2.ClickResponse.FromString,
                _registered_method=True)
        self.CloseSideInfo = channel.unary_unary(
                '/view.ViewService/CloseSideInfo',
                request_serializer=view__pb2.CloseSideInfoRequest.SerializeToString,
                response_deserializer=view__pb2.CloseSideInfoResponse.FromString,
                _registered_method=True)
        self.GetEdge = channel.unary_unary(
                '/view.ViewService/GetEdge',
                request_serializer=view__pb2.EdgeRequest.SerializeToString,
                response_deserializer=view__pb2.EdgeResponse.FromString,
                _registered_method=True)


class ViewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSideInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetView,
                    request_deserializer=view__pb2.ViewRequest.FromString,
                    response_serializer=view__pb2.ViewResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=view__pb2.ClickRequest.FromString,
                    response_serializer=view__pb2.ClickResponse.SerializeToString,
            ),
            'CloseSideInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSideInfo,
                    request_deserializer=view__pb2.CloseSideInfoRequest.FromString,
                    response_serializer=view__pb2.CloseSideInfoResponse.SerializeToString,
            ),
            'GetEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdge,
                    request_deserializer=view__pb2.EdgeRequest.FromString,
                    response_serializer=view__pb2.EdgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'view.ViewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('view.ViewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ViewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/view.ViewService/GetView',
            view__pb2.ViewRequest.SerializeToString,
            view__pb2.ViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/view.ViewService/Click',
            view__pb2.ClickRequest.SerializeToString,
            view__pb2.ClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSideInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/view.ViewService/CloseSideInfo',
            view__pb2.CloseSideInfoRequest.SerializeToString,
            view__pb2.CloseSideInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/view.ViewService/GetEdge',
            view__pb2.EdgeRequest.SerializeToString,
            view__pb2.EdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
