#pragma once

#include "mir_lifetime_scope.hpp"
#include "mir_local_ref.hpp"

#include <typesystem/higher/types.hpp>

#include <base/types/ints.hpp>
#include <base/optional.hpp>
#include <base/stable_container.hpp>
#include <base/stable_hashmap.hpp>
#include <base/string_id.hpp>
#include <base/stringifyable_enum.hpp>
#include <base/strongly_typed_id.hpp>
#include <base/variant.hpp>

#include <variant>
#include <vector>

// Doc style is intentional, caused by inexplicable funkiness in how Doxygen interacts with macros.
MAKE_STRINGIFYABLE_ENUM(compiler::mir, u64, Operation,
	Uninitialized,

	/** Empty instruction, sometimes used by the lowering to fill instruction holes that were not needed */
	Nop,

	Call,
	VCall,

	/** Simple byte by byte assignment */
	Assign,

	/**
		@brief Placeholder.
		@todo  Some decisions here to be made about operations like that.
	*//**
		Perhaps we want more generic code for MIR, so algorithms are simpler.
		There could be single operation for all Add, Sub, etc, and single one for all comparisons.
	*/
	IntegerAdd,
	IntegerSub,
	IntegerNeg,
	IntegerMul,
	IntegerDiv,
	IntegerMod,

	IntegerLt,    // Less then
	IntegerGt,    // Greater then
	IntegerLteq,  // Less then or equal to
	IntegerGteq,  // Greater then or equal to
	IntegerEq,    // Equal to
	IntegerNeq,   // Not equal to


	BooleanAnd,
	BooleanOr,
	BooleanNot,

	/** See readme.md for more info about destruct. */
	Destruct,
	/** See readme.md for more info about DestructIf. */
	DestructIf,

	ReturnVoid,
	ReturnValue,
	Jump,
	Branch,

	/**
		@brief Operation that represents end of a function.
		This operation can have different meaning depending on the context.
		For example in a function that returns void, it is just a return.
		In a function that returns value, "it is" an compiler error, unless it's unreachable.
		@note  It is always implicitly added at the end of a function.
	*/
	FunctionEnd
)

namespace compiler::mir {
	/**
	 * @brief BlockID is a temporary solution that should be replaced by
	 * proper BlockReference.
	 * It is like that for now, to avoid confusion with BlockRef used in mir_lowering and
	 * transformation between that BlockRef to this "BlockRef".
	 */
	STRONG_TYPEDEF_ID_DIRECT_CREATION(BlockID);
}

ID_STD_HASH(::compiler::mir::BlockID);

namespace compiler::mir {

	/**
	 * @brief Whether given operation is an operation that can (and has to be)
	 * the last operation in the block (i.e. be a terminator).
	 */
	bool isTerminating(Operation);

	struct MirUnitConst final {};

	struct MirIntegerConst final {
		i64 value;
	};

	struct MirBoolConst final {
		bool value;
	};

	/**
	 * Represent a direct reference to a function linked to a HELIOS SymID.
	 */
	struct MirFunctionLiteral final {
		helios::SymID helios_id;
	};

	STRONG_TYPEDEF_ID(LocalID);

	/**
	 * @brief Description of a MIR Local variable, like a function argument or simply local
	 * variable.
	 * @note This structure should only be stored directly in MIR Function, as part of the
	 * description of a function. Other uses should use LocalRef to reference the variable
	 * description.
	 */
	struct MirLocal final {
		LocalID id;

		/**
		 * HELIOS SymID of the local variable.
		 * Locals without a helios_id are locals created for temporary values.
		 */
		base::Optional<helios::SymID> helios_id;
		tsh::SymbolType<>             type;

		/**
		 * Lifetime scopes of this local.
		 * This is used to determine when the local is valid (i.e. "live") and when it should be
		 * destructed. The local is valid only in instructions for which the instruction scope is in
		 * the scope-sub-tree of the lifetime scope of the local.
		 *
		 * It is optional, because the scope is not always known during creation of local variable.
		 * One MIR Function is created the scopes should always be set.
		 *
		 * If this is set to no_lifetime_scope (defined in MIR Function), then the local will be
		 * ignored by lifetime analysis. This means that no destructors will be inserted for this
		 * local, and no use-after-free verification will be performed (move analysis will likely
		 * still happen @TODO: #505 determine it). This possibility should only be used for simple
		 * values generated by the compiler itself, to go-around the problem of using the value
		 * after destructors should be called, e.g: in return statements, for if condition value.
		 */
		base::Optional<ScopeRef> scope;

		/**
		 * If this local is a function parameter, this field contains the index of the parameter.
		 */
		base::Optional<u64> parameter_index;

	private:
		// @note: Constructing MirLocal from helios_id
		// might work poorly for template/generic instantiations.

		/**
		 * @brief Constructor for a local variables with a HELIOS SymID.
		 */
		MirLocal(helios::SymID helios_id, tsh::SymbolType<> type):
			  id(LocalID::next()),
			  helios_id(helios_id),
			  type(type) {}

		/**
		 * @brief Constructor for a local variables with a HELIOS SymID that are the function
		 * parameters.
		 */
		MirLocal(helios::SymID helios_id, tsh::SymbolType<> type, u64 parameter_index):
			  id(LocalID::next()),
			  helios_id(helios_id),
			  type(type),
			  parameter_index(parameter_index) {}

		/**
		 * @brief Constructor for temporary values.
		 */
		MirLocal(tsh::SymbolType<> type): id(LocalID::next()), helios_id({}), type(type) {}

		/**
		 * Setter of lifetime scope of this local.
		 * MIR lowering uses it to set the lifetime scope of the local
		 * during the process of generating function code from HOUT.
		 */
		void setLifetimeScope(ScopeRef scope);

		friend struct Function;
		friend struct FunctionBuilder;
		friend struct ExprBlockVisitor;
		friend struct StmtBlockVisitor;
		friend struct LocalVarCollectionVisitor;
		friend LocalRef;

	public:
		void debugPrint(std::ostream& output, bool detailed = false) const;

		[[nodiscard]]
		base::StrID getName() const;

		bool operator==(const MirLocal& other) const { return id == other.id; }

		/**
		 * @brief Returns true if this local is not of a unit type or a similar data-less type.
		 */
		[[nodiscard]]
		bool carriesInformation() const {
			return type.getType().carriesInformation();
		}
	};

	/**
	 * @brief Represents a global value in MIR.
	 *
	 * This structure is used to reference a global variable in MIR code. It is directly connected
	 * to the value from HOUT global data, allowing the MIR to operate on global variables defined
	 * at the HOUT level.
	 *
	 * @details
	 * - The `helios_id` field is the HELIOS SymID of the global variable, used for referencing.
	 * - The `type` field stores the type of the global variable.
	 *
	 * This structure enables MIR instructions to refer to and manipulate global variables that
	 * originate from HOUT global data.
	 */
	struct MirGlobal final {
		/**
		 * @brief HELIOS SymID of the global variable.
		 * It is used to reference the global variable in the code.
		 */
		helios::SymID helios_id;

		/**
		 * @brief Type of the global variable.
		 */
		tsh::SymbolType<> type;

		MirGlobal(helios::SymID helios_id, tsh::SymbolType<> type):
			  helios_id(helios_id),
			  type(type) {}

		void debugPrint(std::ostream& output, bool detailed = false) const;

		/**
		 * @brief Returns true if this local is not of a unit type or a similar data-less type.
		 */
		[[nodiscard]]
		bool carriesInformation() const {
			return type.getType().carriesInformation();
		}
	};

	/**
	 * @brief Structure representing any MIR value.
	 */
	struct MIRValue final {
	private:
		// @TODO: literal, ...
		// "LocalAccess" a.b.c
		// "GlobalAccess" a.b.c
		using ValueType = std::variant<
			MirUnitConst,
			MirIntegerConst,
			MirBoolConst,
			LocalRef,
			BlockID,
			MirFunctionLiteral,
			MirGlobal>;

		ValueType value;

	public:
		MIRValue(MirUnitConst value): value(value) {}

		MIRValue(MirIntegerConst value): value(value) {}

		MIRValue(MirBoolConst value): value(value) {}

		MIRValue(LocalRef value): value(value) {}

		MIRValue(MutLocalRef value): value(value) {}

		MIRValue(BlockID value): value(value) {}

		MIRValue(MirFunctionLiteral value): value(value) {}

		MIRValue(MirGlobal value): value(value) {}

		void debugPrint(std::ostream& output) const;

		[[nodiscard]]
		const ValueType& getVariant() const {
			return value;
		}

		/**
		 * @brief Returns reference value of given type
		 * stored in MIRValue.
		 * Throws if value is not of given type.
		 * @tparam T
		 * @return const T&
		 */
		template<class T>
		const T& get() const {
			return std::get<T>(value);
		}

		[[nodiscard]]
		bool isLocal() const {
			return std::holds_alternative<LocalRef>(value);
		}

		[[nodiscard]]
		bool isGlobal() const {
			return std::holds_alternative<MirGlobal>(value);
		}

		/**
		 * @brief Returns true if this value contains valuable information.
		 * Valuable information is either a reference to a block or function,
		 * or contains a value (local, global, or literal) that is not of
		 * unit or void type, or any other information-less type.
		 */
		[[nodiscard]]
		bool carriesInformation() const {
			variant_match(value) {
				variant_case_novalue(MirUnitConst) { return false; }
				variant_case(MirGlobal, global) { return global.carriesInformation(); }
				variant_case(LocalRef, local) { return local->carriesInformation(); }
			}
			return true;
		}
	};

	/**
	 * @brief Structure representing meta informations about operation
	 * such as:
	 * * does operation construct some variable
	 * * does operation destruct some variable
	 * * does operation move some variable
	 */
	struct OperationFlag final {
		enum class Flag { Construct, Destruct, Move };
		Flag     flag;
		LocalRef local;

		void debugPrint(std::ostream& output) const;
	};

	/**
	 * @brief Creates construct flag for given local.
	 */
	constexpr OperationFlag flagConstruct(LocalRef local) {
		return { .flag = OperationFlag::Flag::Construct, .local = local };
	}

	/**
	 * @brief Creates destruct flag for given local.
	 */
	constexpr OperationFlag flagDestruct(LocalRef local) {
		return { .flag = OperationFlag::Flag::Destruct, .local = local };
	}

	/**
	 * @brief Creates move flag for given local.
	 */
	constexpr OperationFlag flagMove(LocalRef local) {
		return { .flag = OperationFlag::Flag::Move, .local = local };
	}

	/**
	 * @brief Single instruction of MIR code.
	 */
	struct Instruction final {
		using Output = std::variant<LocalRef, MirGlobal>;

		Operation operation = Operation::Uninitialized;

		base::Optional<Output> output;

		std::vector<MIRValue> arguments;

		// construct, destruct, move.
		std::vector<OperationFlag> flags;

		// @TODO: each Instruction should have source position reference

		/**
		 * @brief lifetime-scope of this instruction.
		 */
		ScopeRef scope;

		Instruction()                   = delete;
		Instruction(const Instruction&) = default;

		/**
		 * @todo this line produces -Wmaybe-uninitialized warning for some reason.
		 * fix it.
		 */
		Instruction(Instruction&&) = default;

		Instruction(
			Operation                  operation,
			base::Optional<Output>     output,
			std::vector<MIRValue>      arguments,
			std::vector<OperationFlag> flags,
			ScopeRef                   scope
		):
			  operation(operation),
			  output(output),
			  arguments(std::move(arguments)),
			  flags(std::move(flags)),
			  scope(scope) {}

		void debugPrint(std::ostream& output) const;
	};

	/**
	 * @brief Returns list of MIR BlockIDs that
	 * can be jumped to from given terminator instruction.
	 *
	 * @param terminator
	 * @return std::vector<BlockID>
	 */
	std::vector<BlockID> getTerminatorSuccessors(const Instruction& terminator);

	/**
	 * @brief A simple block of MIR cfg code.
	 */
	struct Block final {
		/**
		 * @brief Unique identifier of the block.
		 * @note it must be identical to the index in the vector of blocks.
		 */
		BlockID id;

		/**
		 * @brief List of instructions in the block.
		 * @note It does not include terminator instruction.
		 */
		std::vector<Instruction> instructions;

		/**
		 * @brief Last instruction of the block.
		 * It has to be terminating instruction (branch, return, etc).
		 *
		 * @todo: Decide if we wan't to move it to instruction vector.
		 */
		Instruction terminator;

		[[nodiscard]]
		ScopeRef beginScope() const;
	};

	struct FunctionSymID final {
		helios::SymID id;
	};

	struct GlobalVariableCTOR final {
		helios::SymID global_var_id;
	};

	/**
	 * @brief Function in MIR.
	 */
	struct Function final {
		/**
		 * This name is only used for debugging and error logging and is not mangled (and is not
		 * used for mangling in LIR)
		 */
		base::StrID name;

		tsh::SymbolType<>              return_type;
		std::vector<tsh::SymbolType<>> parameter_types;

		/**
		 * @brief Map from BlockID to the Block.
		 * The block's content is stored here.
		 * @note Block with ID "0" should always be the one with FunctionEnd (@p
		 * finalizeFunctionEnd)
		 */
		base::StableHashMap<BlockID, Block> blocks;

		/**
		 * @brief The generated order of blocks in the function.
		 * It serves as a list of all the blocks that are inside the function.
		 * The order is not important but it is more human friendly.
		 * First block in the block order is the entry block.
		 */
		std::vector<BlockID> block_order;

		/**
		 * @brief List of all local variables in the function.
		 */
		base::StableVector<const MirLocal> local_list;

		/**
		 * Lifetimes scope-tree of this function.
		 */
		LifetimeScopeTree lifetime_scope_tree;

		/**
		 * Special scope for local variables that are not
		 * omitted by lifetime analysis and destructor calls.
		 * See MirLocal::scope for details.
		 */
		ScopeRef no_lifetime_scope;

		/**
		 * HELIOS SymID releted to the function.
		 * Functions without a helios_id are functions created for eg. from expressions
		 */
		using HSymID = std::variant<FunctionSymID, GlobalVariableCTOR>;

		HSymID helios_id;

		Function()                    = delete;
		Function(const Function&)     = delete;
		Function(Function&&) noexcept = default;

		Function& operator=(const Function&) = delete;

		// We can change it to default, when there will be a reason:
		Function& operator=(Function&&) = delete;

		Function(
			base::StrID                         name,
			tsh::SymbolType<>                   return_type,
			std::vector<tsh::SymbolType<>>      parameter_types,
			base::StableHashMap<BlockID, Block> blocks,
			std::vector<BlockID>                block_order,
			base::StableVector<const MirLocal>  local_list,
			LifetimeScopeTree                   lifetime_scope_tree,
			ScopeRef                            no_lifetime_scope,
			HSymID                              helios_id
		);

		[[nodiscard]]
		u64 queryUnstablePerfectHash() const;

		void debugPrint(std::ostream& output) const;

		/**
		 * @brief Checks if the id's from the HashMap match the id's in the blocks,
		 * if all block_order elements are present in the HashMap and
		 * if the jump targets exist.
		 * Used for debugging.

		 * @note If there is a block in the HashMap but not in the block_order,
		 * it is considered invalid.
		 */
		base::OkBad validateBlockIDs() const;
	};

}

ID_STD_HASH(compiler::mir::LocalID)
