# A subfolder fot testing diagnostics produced by the compiler when compiling invalid code.

# We don't run the actual duckling programs in this test, 
# instead we test that the compiler produces the expected diagnostics when compiling invalid code.

PreCase: "@{clean_cmd} && mkdir build"

Run: "
  case @{backend} in
    dvm)       @{compile_dvm_backend_cmd}                   ;;
    llvm)      @{compile_llvm_backend_cmd}                  ;;
    nobackend) echo \"Backend undefined\"; exit 1               ;;
    *)         echo \"Unknown backend\";   exit 1                 ;;
  esac;
  "
  
SubDirs:
  - initialization
