
# We don't run the actual duckling programs in this test, 
# instead we test that the compiler produces the expected diagnostics when compiling invalid code.

PreCase: "@{clean_cmd} && mkdir build"

Run: "
  case '@{backend}' in
    dvm)       @{compile_dvm_backend_cmd}                   ;;
    llvm)      @{compile_llvm_backend_cmd}                  ;;
    nobackend) exit 1 ;;
    *)         exit 2 ;;
  esac;
  "
  
Tests:
  no_main_source_file:
    Cases:
      llvm:
        backend: llvm
        # @TODO: #2228 add better output handling here!
        Output:
          String: ""
        Err:
          String: "error[E0]: Main package does not have a main source file.\nThe main source file is required for compilation. Please add a no_main_source_file.dmf file to the main module directory.\n\n"
        ExitCode: 1
