PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo
  @{duck_exe} init bar
  echo "dependencies:
    bar:
      source:
        path: ../bar/
      features: [b]" >> foo/quackconfig.yaml
Tests:
  sync:
    Description: cannot sync a project with a nonexistent dependency feature
    Cases:
      sync:
        test_cmd: duck -C foo sync
        ExitCode: 1
        Err:
          Run: |+
            echo "error: package at the directory \`$DIT_TMP_DIR/bar\` does not have feature \`b\`"
