PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo

Tests:
  errors:
    Cases:
      adding-itself:
        test-cmd: duck -C foo add foo --local .
        ExitCode: 1
        Err:
          String: |+
            error: tried to add root as its own dependency
