# Tests for script loading in REPL via /load and preload argument.

# These run from subdirectories of script_loading, hence the "../".
script-basic: "../scripts/basic_expr.dks"
script-if-flow: "../scripts/if_flow.dks"
script-mixed: "../scripts/mixed.dks"
script-print-burst: "../scripts/print_burst.dks"
script-nested-functions: "../scripts/nested_functions.dks"
script-silent-state: "../scripts/silent_state.dks"
script-silent-functions: "../scripts/silent_functions.dks"
script-nasty: "../scripts/nasty.dks"

SubDirs:
  - load_command
  - preload_script
