PreNode: ""

SubDirs:
  - basic
  - basic-with-flags
  - cycle-in-flags
  - dep
  - dep-and-conditions
  - dep-and-conditions2
  - dep-and-flags
  - dep-and-flags2
  - errors
  - exposed-freezefile
  - exposed-freezefile-and-deps
  - legal-packages-names
