Tests:
  sync:
    Description: can sync a new project
    Cases:
      sync:
        test_cmd: -C foo sync
        ExitCode: 1
        Err:
          Run: |+
            echo "error: the path \`$(pwd)/bar\` is not a directory"
