# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: view.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'view.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nview.proto\x12\x04view\"P\n\tTextEntry\x12\x0c\n\x04text\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.view.TextDisplayType\x12\x10\n\x08group_id\x18\x03 \x01(\x05\"1\n\rTextComponent\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.view.TextEntry\"4\n\rListComponent\x12#\n\ncomponents\x18\x01 \x03(\x0b\x32\x0f.view.Component\"\x82\x01\n\tComponent\x12\n\n\x02id\x18\x03 \x01(\x05\x12-\n\x0etext_component\x18\x01 \x01(\x0b\x32\x13.view.TextComponentH\x00\x12-\n\x0elist_component\x18\x02 \x01(\x0b\x32\x13.view.ListComponentH\x00\x42\x0b\n\tcomponent\"2\n\x0cViewResponse\x12\"\n\tcomponent\x18\x01 \x01(\x0b\x32\x0f.view.Component\"!\n\x0c\x43lickRequest\x12\x11\n\tobject_id\x18\x01 \x01(\x05\"\x1f\n\rClickResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty*&\n\x0fTextDisplayType\x12\t\n\x05PLAIN\x10\x00\x12\x08\n\x04\x43ODE\x10\x01\x32k\n\x0bViewService\x12*\n\x07GetView\x12\x0b.view.Empty\x1a\x12.view.ViewResponse\x12\x30\n\x05\x43lick\x12\x12.view.ClickRequest\x1a\x13.view.ClickResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'view_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTDISPLAYTYPE']._serialized_start=469
  _globals['_TEXTDISPLAYTYPE']._serialized_end=507
  _globals['_TEXTENTRY']._serialized_start=20
  _globals['_TEXTENTRY']._serialized_end=100
  _globals['_TEXTCOMPONENT']._serialized_start=102
  _globals['_TEXTCOMPONENT']._serialized_end=151
  _globals['_LISTCOMPONENT']._serialized_start=153
  _globals['_LISTCOMPONENT']._serialized_end=205
  _globals['_COMPONENT']._serialized_start=208
  _globals['_COMPONENT']._serialized_end=338
  _globals['_VIEWRESPONSE']._serialized_start=340
  _globals['_VIEWRESPONSE']._serialized_end=390
  _globals['_CLICKREQUEST']._serialized_start=392
  _globals['_CLICKREQUEST']._serialized_end=425
  _globals['_CLICKRESPONSE']._serialized_start=427
  _globals['_CLICKRESPONSE']._serialized_end=458
  _globals['_EMPTY']._serialized_start=460
  _globals['_EMPTY']._serialized_end=467
  _globals['_VIEWSERVICE']._serialized_start=509
  _globals['_VIEWSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
