# Copyright 2026 DuckType LLC
#
# This file is part of the Duckling project, licensed under the DuckType
# Compiler License, Version 1.0. See the LICENSE or LICENSE.md file in the root
# of this repository or https://ducktype.org/licenses/DTCL-1.0

NAME = "Name"
CASE_NAME = "CaseName"
DESCRIPTION = "Description"
TESTS = "Tests"
SUBDIRS = "SubDirs"
COMPILE = "Compile"
RUN = "Run"
ENABLED = "Enabled"
PRE_NODE = "PreNode"
POST_NODE = "PostNode"
PRE_TEST = "PreTest"
POST_TEST = "PostTest"
PRE_CASE = "PreCase"
POST_CASE = "PostCase"
NEEDED_THREADS = "NeededThreads"
CLEAN = "Clean"
ENV = "Env"
TIME_OUT = "TimeOut"
EXIT_CODE = "ExitCode"
PARENT = "_Parent"
CONFIG_FILE = "_ConfigFile"
CONFIG_DIR = "ConfigDir"
INPUT = "Input"
OUTPUT = "Output"
CASES = "Cases"
ERR = "Err"
FILE = "File"
STRING = "String"
FAIL_FAST = "FailFast"
NO_PARALLEL = "NoParallel"
