#!/usr/bin/env python3
"""Generate the two structured-bindings tables under src/ser/detail/.

    ladder.inc        - hand the fields to a callback (the walk)
    ladder_decls.inc  - hand out each field's DECLARED type (the guard)

A structured binding declaration is a statement, not an expression, so the 65 arities
cannot be folded into one - unlike the field-count probe, whose braced clauses DO come
out of a pack expansion (see describe_bind.hpp).

Sixty-five branches written by hand is a guaranteed typo in branch 47, and the typo
would not be a compile error: it would be one field written twice and another never
written, which is a format bug that round-trips perfectly on the machine that made it.

Run from anywhere:  python tools/gen_ladder.py
"""

import os

MAX_MEMBERS = 64
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_LADDER = os.path.join(HERE, "..", "src", "ser", "detail", "ladder.inc")
OUT_DECLS = os.path.join(HERE, "..", "src", "ser", "detail", "ladder_decls.inc")

LADDER_HEAD = """// GENERATED by tools/gen_ladder.py - do not edit
// Included inside ser::access::visitMembersN, which supplies `obj`, `f` and the
// constant `N`. An .inc rather than a macro, so a compiler error points at a line of
// real C++.
//
// Structured bindings, not reflection: on every compiler that exists today this is the
// primary implementation. It sees private fields because the declaration lives inside
// ser::access, which the type befriends with SER_FRIEND.
//
// This file is also the backstop for a wrong field count. The arity of a structured
// binding is CHECKED against the type, never deduced, so a count that does not match is
// a compile error here - which is why a miscount can never turn into wrong bytes. If the
// compiler points at a line below saying the number of identifiers does not match the
// number of members, the count is wrong: declare it in the class with
//     using ser_members = ser::members<N>;
"""

DECLS_HEAD = """// GENERATED by tools/gen_ladder.py - do not edit
// Included inside ser::access::fieldDeclsN, which supplies `obj` and the constant `N`.
//
// The companion table to ladder.inc, and its reason for existing is narrow: a member's
// DECLARED type is visible HERE and nowhere downstream. Handing a binding to a function
// parameter turns `int&` (a reference member) and `const int` (a const member) into the
// same `const int&`, because an expression never has reference type - so no guard written
// further down can tell those two apart, and one of them is a shape that works. decltype
// on the binding does tell them apart, and that is what this table hands out.
//
// `bindable` comes from the same place for the same reason: nothing can bind a non-const
// lvalue reference to a bit-field, and the binding is the last place able to ask.
"""

TAIL = """else static_assert(::ser::detail::DEPENDENT_FALSE<T>,
    "ser: this type has more than 64 members, which is the limit of the generated "
    "structured-bindings ladder. Split it, or give it a serVisit hook.");
"""


def branch(n, first):
    keyword = "     if constexpr" if first else "else if constexpr"
    if n == 0:
        return keyword + " (N ==  0) { (void)obj; return f(); }\n"
    names = ", ".join("m{}".format(i) for i in range(n))
    return "{} (N == {:2d}) {{ auto&& [{}] = obj; return f({}); }}\n".format(
        keyword, n, names, names)


def decl_branch(n, first):
    keyword = "     if constexpr" if first else "else if constexpr"
    if n == 0:
        return keyword + " (N ==  0) { (void)obj; return ::ser::detail::type_list<>{}; }\n"
    names = ", ".join("m{}".format(i) for i in range(n))
    decls = ",\n        ".join(
        "::ser::detail::field_decl<decltype(m{i}), (requires {{ bindProbe(m{i}); }})>".format(i=i)
        for i in range(n))
    return ("{} (N == {:2d}) {{ auto&& [{}] = obj;\n"
            "    return ::ser::detail::type_list<\n        {}>{{}}; }}\n").format(
        keyword, n, names, decls)


def write(path, text, what):
    path = os.path.normpath(path)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote {}: {} branches ({})".format(path, MAX_MEMBERS + 1, what))


def main():
    write(OUT_LADDER,
          LADDER_HEAD + "".join(branch(n, n == 0) for n in range(MAX_MEMBERS + 1)) + TAIL,
          "the walk")
    write(OUT_DECLS,
          DECLS_HEAD + "".join(decl_branch(n, n == 0) for n in range(MAX_MEMBERS + 1)) + TAIL,
          "declared types")


if __name__ == "__main__":
    main()
