#!/usr/bin/env python3
"""Generate include/ser/detail/for_each.inc - the preprocessor FOR_EACH tables.

The preprocessor has no recursion, so "apply this macro to each of my arguments" is
one macro per arity. Two families are needed, because the two uses need different
separators:

  SER_DETAIL_FOR_EACH(m, ...)       m(a), m(b), m(c)     an argument list
  SER_DETAIL_FOR_EACH_STMT(m, ...)  m(a) m(b) m(c)       statements, m supplies the ;

Run from anywhere:  python tools/gen_for_each.py
"""

import os

MAX_ARGS = 64
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "include", "ser", "detail", "for_each.inc")

HEAD = """// GENERATED by tools/gen_for_each.py - do not edit
//
// SER_DETAIL_NARG(...) counts arguments by shifting a descending list of numbers past
// 64 named parameters: with k arguments the (k+1)-th number lands on N. It needs a
// conforming preprocessor, which on MSVC means /Zc:preprocessor (CMakeLists sets it).
"""


def narg():
    picks = ", ".join("_{}".format(i) for i in range(1, MAX_ARGS + 1))
    numbers = ", ".join(str(i) for i in range(MAX_ARGS, -1, -1))
    return (
        "#define SER_DETAIL_NARG_PICK({}, N, ...) N\n"
        "#define SER_DETAIL_NARG(...) SER_DETAIL_NARG_PICK(__VA_ARGS__, {})\n\n"
    ).format(picks, numbers)


def family(suffix, separator):
    out = []
    out.append("#define SER_DETAIL_FE_{}_1(m, x) m(x)\n".format(suffix))
    for n in range(2, MAX_ARGS + 1):
        out.append(
            "#define SER_DETAIL_FE_{s}_{n}(m, x, ...) m(x){sep} "
            "SER_DETAIL_FE_{s}_{p}(m, __VA_ARGS__)\n".format(
                s=suffix, n=n, p=n - 1, sep=separator))
    return "".join(out)


def main():
    text = [HEAD, "\n", narg()]
    text.append("// ── m(a), m(b), m(c) ──────────────────────────────────────────────────────────\n")
    text.append(family("C", ","))
    text.append("\n#define SER_DETAIL_FOR_EACH(m, ...) \\\n"
                "    SER_DETAIL_CAT(SER_DETAIL_FE_C_, SER_DETAIL_NARG(__VA_ARGS__))(m, __VA_ARGS__)\n\n")
    text.append("// ── m(a) m(b) m(c) - m supplies its own semicolon ─────────────────────────────\n")
    text.append(family("S", ""))
    text.append("\n#define SER_DETAIL_FOR_EACH_STMT(m, ...) \\\n"
                "    SER_DETAIL_CAT(SER_DETAIL_FE_S_, SER_DETAIL_NARG(__VA_ARGS__))(m, __VA_ARGS__)\n")

    path = os.path.normpath(OUT)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(text))
    print("wrote {}: 2 x {} arities".format(path, MAX_ARGS))


if __name__ == "__main__":
    main()
