# Tests for statements

Tests:
  simple:
    Cases: 
      default:
        Output:
          String: "5 \n7 \n"
        ExitCode: 0
  single_stmt_body:
    Cases:
      default:
        Output:
          String: "5 \n7 \n"
        ExitCode: 0
  named_default_args:
    Cases:
      default:
        Output:
          String: "1 \n2 \n1 \n2 \n3 \n2 \n4 \n5 \n1 \n3 \n1 \n2 \n2 \n3 \n4 \n5 \n1 \n5 \n4 \n2 \n"
        ExitCode: 0

