# Tests for statements

Tests:
  simple:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "5 \n7 \n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "5\n7\n"
        ExitCode: 0
  single_stmt_body:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "5 \n7 \n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "5\n7\n"
        ExitCode: 0

