Name: "Tests of C++"

compile_flags: "-O2 -std=c++23 -Wall"
compile_args: "-o @{program_name}.bin"

Compile: "g++ @{program_name}.cpp @{compile_args} @{compile_flags}"
Run: "./@{program_name}.bin"
PostRun: "echo \"This is a post run message about @{program_name}!\""
Clean: "rm @{program_name}"

ExitCode: 0
TimeOut: 10

Tests:
  fib-tests:
    Name: "Custom name"
    program_name: "file_fib"
    Cases:
      simple:
        Input:
          String: "5"
        Output:
          String: "0 1 1 2 4 "
      simple-from-file:
        Input:
          File: input_for_fib.in
        Output:
          String: "0 1 1 2 3 "
      normal:
        Name: "Up to 100"
        Input:
          String: "100"
        Output:
          Run: "python3 gen_fibs.py 100"
      large:
        Name: "Up to 100000"
        Input:
          String: 100000
        Err:
          String: "Too large\n"
        ExitCode: 1
