PostCase: python3 check.py && @{cleanup_tmp_env}

Tests:
  duck/init/basic-project:
    Description: can initialise a new project
    Cases:
      init:
        test-cmd: duck init foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
