PostCase: python3 check.py

Tests:
  init:
    Description: can initialise a new project
    Cases:
      init:
        test_cmd: duck init foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
