
Tests:
  simple_expand_1:
    Cases:
      all:
        Output:
          String: "2\n"
        ExitCode: 0

  simple_expand_2:
    Cases:
      all:
        Output:
          String: "2\n2\n"
        ExitCode: 0

  simple_expand_3:
    Cases:
      all:
        Output:
          String: "1\n2\n"
        ExitCode: 0

  expand_expand:
    Cases:
      all:
        Output:
          String: "1\n2\n"
        ExitCode: 0

  various_statements:
    Cases:
      all:
        Output:
          String: "177\n"
        ExitCode: 0

  expand_comp_time:
    Cases:
      all:
        Output:
          String: "42\n1\n30\n20\nhello10\n"
        ExitCode: 0

  mangling_in_expand:
    Cases:
      all:
        Output:
          String: "1\n2\n"
        ExitCode: 0

