# Tests for variant types
Tests:
  variant_match:
    Cases:
      all:
        backend: all
        Output:
          String: ""
        ExitCode: 0

  variant_owning_alternatives:
    Cases:
      llvm_valgrind:
        backend: llvm
        valgrind: "true"
        TimeOut: 3 # 1 second is often not enough on runners
        Output:
          String: ""
        ExitCode: 0
      dvm:
        backend: dvm
        TimeOut: 3
        Output:
          String: ""
        ExitCode: 0
