#pragma once

namespace pst {
	// Meta
	class Stmt;
	class NotStmt;
	class ClassStmt;
	// Lists
	class ParamList;
	class ImplementsList;
	class TemplateList;
	class AtrArgList;
	class InitList;
	class CallList;
	class FlowPatternList;
	class NestedImportList;
	// Not Statements
	class Param;
	class DottedName;
	class Attribute;
	class CallArgument;
	class CodeBlock;
	class CodeBlockOrStmt;
	class ClassBlock;
	class StmtSpecifier;
	class RoundGroupExpr;
	class ExprElement;
	class FormatSubElement;
	class FormatSubExpression;
	class FormatSubString;
	// Wrappers
	class OperatorWrapper;
	class IdentifierWrapper;
	class KeywordWrapper;
	// Patterns
	class FlowPattern;
	class AnalysisPattern;
	class DeconstructorPattern;
	class TuplePattern;
	class WildcardPattern;
	class BindingPattern;
	class ValuePattern;
	// Import Chains
	class ImportChain;
	class ImportIdentifierAs;
	class ImportStarHides;
	class ImportNested;
	// Statements
	class Import;
	class Using;
	class ExprStmt;
	class Alias;
	class Action;
	class Decl;
	class Expand;
	class SpecifierBlock;
	// Declarations
	class CodeDecl;
	class TopLevel;
	class Block;
	class Namespace;
	class Class;
	class Variable;
	class Const;
	class Fun;
	class FunDecl;
	class Pattern;
	class If;
	class While;
	class For;
	class TemplateDecl;
	// Actions
	class Return;
	class Continue;
	class Redo;
	class Restart;
	class Defer;
	class Throw;
	class Break;
	// Class Elements
	class ClassSpecifierBlock;
	class ClassSpecial;
	class Constructor;
	class CopyConstructor;
	class Destructor;
	class Method;
	class Field;

	namespace expr {
		class PrefixOperator;
		class SuffixOperator;
		class BinaryOperator;
		class ExprNumericValue;
		class ExprStrValue;
		class ExprCharValue;
		class ExprFormatStrValue;
		class Literal;
		class TemplateSpecifier;
		class IdentifierLiteral;
		class KeywordLiteral;
		class Access;
		class Call;
		class Atom;
		class ChainExpr;
		class RoundExpr;
		class UnitExpr;
		class BlockExpr;
		class MatchExpr;
		class GeneralPrefix;
		class GeneralSuffix;
		class GeneralBinary;
		class ComparisonChain;
		class LogicNot;
		class LogicAnd;
		class LogicOr;
		class Ternary;
		class Comma;
		class Assignment;
	}

	// Expr Holders

	class ExprHolder;
	class UniversalExprHolder;
	class UniversalAllowBlockExprHolder;
	class UniversalExprHolderLowerLevel;
	class CommaExprHolder;
	class CommaAllowBlocksExprHolder;
	class AssignmentExprHolder;
	class ValuePatternExprHolder;
	class ImplementsElementExprHolder;
	class ForTypeExprHolder;
}
