#pragma once

#include <helios/symbols/symbol_id.hpp>

#include <base/extend_cpp/stringifyable_enum.hpp>

#include <query_framework/query_int.hpp>
#include <query_framework/query_result.hpp>

MAKE_STRINGIFYABLE_ENUM(compiler::helios, u32, LanguagePrimitive,
    Panic,
	String,
	StringifyStr,
	StringifyChar,
	StringifyBool,
	StringifyI64,
	StringifyU64,
	StringifyF64,
	ConcatStrings,
	PrependChar,
	AppendChar
	// List
	// PanicOutOfBounds
)

namespace compiler::helios {
	struct QueryLanguagePrimitiveSymID_key {
		LanguagePrimitive primitive;

		[[nodiscard]] u64 queryUnstablePerfectHash() const { return static_cast<u64>(primitive); }
	};

	/**
	 * @brief Lookup the SymID of a language primitive.
	 * The language primitives are essential parts of the standard library that
	 * can be used by the compiler itself, but they are written as normal Duckling
	 * code in some place in the standard library.
	 *
	 * For example `panic` call can be generated by the compiler on out-of-bounds access,
	 * but it is written in Duckling.
	 *
	 * \query_thread_safe_if_cache
	 */
	DECLARE_QUERY(
		QueryLanguagePrimitiveSymID,
		QueryLanguagePrimitiveSymID_key,
		CRef<query::QResult<SymID>>,
		({})
	);
}
