// Copyright 2026 DuckType LLC
//
// This file is part of the Duckling project, licensed under the DuckType
// Compiler License, Version 1.0. See the LICENSE or LICENSE.md file in the root
// of this repository or https://ducktype.org/licenses/DTCL-1.0

#pragma once

#include <ctv/ctv.hpp>
#include <helios/symbols/symbol_id.hpp>
#include <helios/tsh/symbol_type.hpp>
#include <helios/tsh/types.hpp>

#include <base/extend_cpp/stringifyable_enum.hpp>

#include <query_framework/query_int.hpp>
#include <query_framework/query_result.hpp>

MAKE_STRINGIFYABLE_ENUM(compiler::helios, u32, LanguagePrimitive,
    Panic,

	// Power `**` operator
	PowInt,
	PowF32,
	PowF64,
	
	// String
	String,
	StringifyStr,
	StringifyChar,
	StringifyBool,
	StringifyI64,
	StringifyU64,
	StringifyF64,
	StringifyPtr,
	StringifyManyPtr,
	StringifyCPtr,
	StringifySlice,
	StringifyStaticArray,
	
	BoxAlloc,
	BoxFree,

	OptionalNone,
	OptionalValue,
	OptionalValueRef,
	OptionalFull,
	OptionalEmpty,
	OptionalReset
	// List
	// PanicOutOfBounds
)

namespace query {
	struct Context;
}

namespace compiler::helios {
	struct QueryLanguagePrimitiveSymID_key {
		LanguagePrimitive primitive;

		[[nodiscard]] u64 queryUnstablePerfectHash() const { return static_cast<u64>(primitive); }
	};

	/**
	 * @brief Lookup the SymID of a language primitive.
	 * The language primitives are essential parts of the standard library that
	 * can be used by the compiler itself, but they are written as normal Duckling
	 * code in some place in the standard library.
	 *
	 * For example `panic` call can be generated by the compiler on out-of-bounds access,
	 * but it is written in Duckling.
	 *
	 * \query_thread_safe_if_cache
	 */
	DECLARE_QUERY(
		QueryLanguagePrimitiveSymID,
		QueryLanguagePrimitiveSymID_key,
		CRef<query::QResult<SymID>>,
		({})
	);

	/**
	 * @brief Checks whether a language primitive resolves to at least one symbol.
	 * Unlike QueryLanguagePrimitiveSymID this never logs an error: a missing primitive
	 * (e.g. a no-std build without `core.containers`) simply returns false.
	 */
	bool isLanguagePrimitivePresent(query::Context& ctx, LanguagePrimitive primitive);

	/**
	 * @brief Bakes a templated language primitive with a single type argument.
	 * The primitive must be declared as `template(T: type)` in the standard library; the
	 * returned symbol is the specialization for @p type_argument, callable like any other
	 * function symbol.
	 */
	SymID bakeLanguagePrimitive(
		query::Context&                    ctx,
		LanguagePrimitive                  primitive,
		std::vector<ctv::CompileTimeValue> ctv_arguments
	);

	/**
	 * @brief Helper overload tha accepts the symbol types.
	 */
	SymID bakeLanguagePrimitiveWithTypes(
		query::Context&                ctx,
		LanguagePrimitive              primitive,
		std::vector<tsh::SymbolType<>> type_arguments
	);

	/**
	 * @brief The `None` class type, which is the empty alternative of every optional.
	 */
	tsh::SymbolType<> getOptionalNoneType(query::Context& ctx);

	/**
	 * @brief The optional type `?T`, i.e. the variant `T | None` marked as an optional.
	 */
	tsh::VariantAbstractType getOptionalType(query::Context& ctx, tsh::SymbolType<> value_type);
}
