#pragma once

namespace compiler::helios {

	/**
	 * @brief Stores general kind/type of a symbol.
	 */
	enum class SymbolKind {
		Namespace,
		Function,
		Const,
		Class,
		Alias,
		Using,
		Variable,
		Import,
		Parameter,

		// we distinguish between functions and builtin functions
		// as for example there is no code-gen for builtin functions
		BuiltinFunction,

		// Anything generated by the compiler, such as implicit constructors or conversions,
		// or variables inside them.
		Generated,

		// Class-specific Symbols
		Method,
		Field,
		Constructor,
		Destructor,

		// ...
	};
}
