repos:
  - repo: local
    hooks:
      - id: format
        name: Run formatter
        entry: uv
        args: [ run, ruff, format, --diff ]
        types: [ python ]
        stages: [ pre-push ]
        language: system

      - id: lint
        name: Run linter
        entry: uv
        args: [ run, ruff, check ]
        types: [ python ]
        stages: [ pre-push ]
        language: system

      - id: pyright
        name: Run pyright
        entry: uv
        args: [ run, pyright ]
        pass_filenames: false
        types: [ python ]
        stages: [ pre-push ]
        language: system
