[project]
name = "quackpack"
version = "0.1.0"
description = "Package manager for Duckling"
readme = "README.md"
authors = [
    { name = "Ignacy Gębuś", email = "ig448499@students.mimuw.edu.pl" },
    { name = "Tymoteusz Kucharek", email = "tk448520@students.mimuw.edu.pl" },
    { name = "Stanisław Wiśniewski", email = "sw448598@students.mimuw.edu.pl" },
    { name = "Artur Wojtuszkiewicz", email = "aw448602@students.mimuw.edu.pl" }
]
requires-python = ">=3.12"
dependencies = [
    "rich-argparse>=1.6.0",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "pycurl>=7.45.4",
    "gitpython>=3.1.44",
    "pywin32>=308 ; sys_platform == 'win32'",
    "uvloop>=0.21.0 ; os_name == 'posix'",
    "pyscipopt>=5.4.1",
    "tomlkit>=0.13.2",
    "strictyaml>=1.7.3",
    "treelib>=1.8.0",
]

[project.scripts]
quackpack = "quackpack:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ducknest>=0.1.0",
    "pyright>=1.1.395",
    "pytest>=8.3.4",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.7",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
]

[tool.pyright]
exclude = [".venv", "tests/unit/fetcher"]
ignore = [".venv", "tests/unit/fetcher"]
pythonPlatform = "All"
pythonVersion = "3.12"
reportImportCycles = "error"
reportImplicitOverride = "error"
reportMissingModuleSource = false
reportUnusedClass = "warning"
reportUnusedFunction = "warning"
reportUnusedImport = "warning"
reportUnusedVariable = "warning"
typeCheckingMode = "strict"
venv = ".venv/"
venvPath = "./"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "strict"

[tool.ruff]
exclude = ["./extras"]
fix = false
indent-width = 4
line-length = 110
preview = true
target-version = "py312"

[tool.ruff.analyze]
detect-string-imports = true

# Most of the settings are same as https://github.com/astral-sh/ruff/blob/main/python/py-fuzzer/pyproject.toml
[tool.ruff.lint]
select = [
    "ARG",
    "B",
    "B9",
    "C4",
    "E",
    "F",
    "I",
    "PGH",
    "PIE",
    "PYI",
    "RUF",
    "SIM",
    "UP",
]
ignore = [
    # only relevant if you run a script with `python -0`,
    "B011",
    # These are enforced by, or incompatible with, the ruff formatter:
    "E203",
    # Too long line for docstrings.
    "E501",
    # Makes code slower and more verbose
    # https://github.com/astral-sh/ruff/issues/7871
    "UP038",
]
unfixable = [
    "B018",   # automatic fix might obscure issue
    "F601",   # automatic fix might obscure issue
    "F602",   # automatic fix might obscure issue
    "F841",   # unused variable. ruff keeps the call, but mostly it's best to get rid of it all
    "RUF017", # Ruff's fix is faster, but I prefer using itertools.chain_from_iterable
]

[tool.ruff.lint.isort]
combine-as-imports = true
# Ruff can't format files with both `isort.split-on-magic-trailing-comma` and `ruff.format.skip-magic-trailing-comma`.
split-on-trailing-comma = false

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = true

[tool.uv.sources]
ducknest = { git = "ssh://git@github.com/ducktype-org/duck-nest.git" }
