# The different targets supported by the compiler,
# thus also the targets for which built-in libraries are built.
set(BUILTIN_TARGETS
        x86_64-linux-gnu

        # This target requires further configuration so that clang
        # can find the appropriate sysroot and libraries.
        #        aarch64-linux-gnu

        # This target requires proprietary Apple libraries and SDKs,
        # so can only be built on macOS hosts.
        #        x86_64-apple-darwin
)

# Before going further, ensure that there exists a Clang version on the system which
# matches the LLVM version used by the compiler. This is important because the builtins
# will be compiled with the system Clang, and later lined into modules generated by our LLVM.

# Function to check if a given clang binary matches the expected LLVM version.
function(check_clang_version result_var candidate_path)
    # Get the version string from the candidate binary
    execute_process(
            COMMAND "${candidate_path}" --version
            OUTPUT_VARIABLE clang_out
            ERROR_QUIET
    )

    # Use a regex to extract the major version number and compare it with LLVM
    # Standard clang --version output: "clang version 15.0.0 ..."
    if (clang_out MATCHES "clang version ([0-9]+)")
        if ("${CMAKE_MATCH_1}" EQUAL LLVM_VERSION_MAJOR)
            set(${result_var} TRUE PARENT_SCOPE)
            return()
        endif ()
    endif ()

    set(${result_var} FALSE PARENT_SCOPE)
endfunction()

# Find all llvm-related 'bin' directories inside
# scripts/downloads in case user built/downloaded clang themselves.
file(GLOB POTENTIAL_CLANG_PATHS
        LIST_DIRECTORIES true
        "${CMAKE_SOURCE_DIR}/scripts/downloads/llvm_lib*/bin"
)

# Find the actual clang binary
find_program(CLANG_BIN
        NAMES clang clang-19
        PATHS ${POTENTIAL_CLANG_PATHS}
        VALIDATOR check_clang_version
)

if (CLANG_BIN)
    message(STATUS "Using Clang for built-ins source generation: ${CLANG_BIN}")
else ()
    message(FATAL_ERROR "Clang version ${LLVM_VERSION_MAJOR} not found. A version which matches the used LLVM version is required to generate sources of the built-in library.")
endif ()

set(GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")

# For each target, add command to generate the LLVM bitcode
# and convert it to an embedded header file.
foreach (target IN LISTS BUILTIN_TARGETS)
    # Define output file names
    set(bc_file "${GENERATED_DIR}/builtins_${target}.bc")
    set(embedding_file "${GENERATED_DIR}/builtins_${target}.cpp")

    set(BUILTINS_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src_private/driver_private/builtins")

    # Add command to generate LLVM bitcode by compiling the built-ins source code via clang.
    add_custom_command(
            OUTPUT ${bc_file}
            COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
            COMMAND ${CLANG_BIN}
            --target=${target}
            -O2
            -emit-llvm
            -c ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
            -o ${bc_file}
            DEPENDS ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
            COMMENT "Generating LLVM bitcode for target ${target}"
    )

    # The symbol name in the generated header file should not contain `-`. Replace `-` with `_`.
    string(REPLACE "-" "_" target_sanitized ${target})
    set(symbol_name builtins_${target_sanitized}_bc)

    # Add command to convert the LLVM bitcode to an embedded header file using xxd.
    add_custom_command(
            OUTPUT ${embedding_file}
            COMMAND xxd -i -n ${symbol_name} ${bc_file} > ${embedding_file}
            DEPENDS ${bc_file}
            COMMENT "Converting LLVM bitcode to embedded header for ${target}"
    )

    list(APPEND BUILTINS_EMBEDS ${embedding_file})
endforeach ()

add_custom_target(
        builtins_embeds ALL
        DEPENDS ${BUILTINS_EMBEDS}
)

add_custom_target(
        builtins_object_file
        SOURCES ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
)
