# The different targets supported by the compiler,
# thus also the targets for which built-in libraries are built.
set(BUILTIN_TARGETS
        x86_64-linux-gnu

        # This target requires further configuration so that clang
        # can find the appropriate sysroot and libraries.
        #        aarch64-linux-gnu

        # This target requires proprietary Apple libraries and SDKs,
        # so can only be built on macOS hosts.
        #        x86_64-apple-darwin
)

# Before going further, ensure that there exists a Clang version on the system which
# matches the LLVM version used by the compiler. This is important because the builtins
# will be compiled with the system Clang, and later lined into modules generated by our LLVM.
find_program(CLANG_BIN
    NAMES clang-${LLVM_VERSION_MAJOR} clang
    REQUIRED
)

# For each target, add command to generate the LLVM bitcode
# and convert it to an embedded header file.
foreach (target IN LISTS BUILTIN_TARGETS)
    # Define output file names
    set (GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
    set(bc_file "${GENERATED_DIR}/builtins_${target}.bc")
    set(header_file "${GENERATED_DIR}/builtins_${target}.h")

    set(BUILTINS_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src_private/driver_private/builtins")

    # Add command to generate LLVM bitcode by compiling the built-ins source code via clang.
    add_custom_command(
            OUTPUT ${bc_file}
            COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
            COMMAND ${CLANG_BIN}
            --target=${target}
            -O2
            -emit-llvm
            -c ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
            -o ${bc_file}
            DEPENDS ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
            COMMENT "Generating LLVM bitcode for target ${target}"
    )

    # The symbol name in the generated header file should not contain `-`. Replace `-` with `_`.
    string(REPLACE "-" "_" target_sanitized ${target})
    set(symbol_name builtins_${target_sanitized}_bc)

    # Add command to convert the LLVM bitcode to an embedded header file using xxd.
    add_custom_command(
            OUTPUT ${header_file}
            COMMAND xxd -i -n ${symbol_name} ${bc_file} > ${header_file}
            DEPENDS ${bc_file}
            COMMENT "Converting LLVM bitcode to embedded header for ${target}"
    )

    list(APPEND BUILTIN_HEADERS ${header_file})
endforeach ()

add_custom_target(
        builtins_headers ALL
        DEPENDS ${BUILTIN_HEADERS}
)
