# The built-in library is compiled for the target the compiler itself runs on.
# By default this is Clang's own default target (i.e. the host triple).
# Cross-compiling the driver requires setting BUILTINS_TARGET to the target triple,
# and providing Clang with a matching sysroot / libraries via BUILTINS_EXTRA_CLANG_FLAGS.
# On macOS the SDK sysroot is added automatically, see below.
set(BUILTINS_TARGET "" CACHE STRING "Target triple for the built-in library (empty = Clang default/host)")
set(BUILTINS_EXTRA_CLANG_FLAGS "" CACHE STRING "Extra Clang flags used when compiling the built-in library")

# Before going further, ensure that there exists a Clang version on the system which
# matches the LLVM version used by the compiler. This is important because the builtins
# will be compiled with the system Clang, and later lined into modules generated by our LLVM.

# Function to check if a given clang binary matches the expected LLVM version.
function(check_clang_version result_var candidate_path)
    # Get the version string from the candidate binary
    execute_process(
            COMMAND "${candidate_path}" --version
            OUTPUT_VARIABLE clang_out
            ERROR_QUIET
    )

    # Use a regex to extract the major version number and compare it with LLVM
    # Standard clang --version output: "clang version 15.0.0 ..."
    if (clang_out MATCHES "clang version ([0-9]+)")
        if ("${CMAKE_MATCH_1}" EQUAL LLVM_VERSION_MAJOR)
            set(${result_var} TRUE PARENT_SCOPE)
            return()
        endif ()
    endif ()

    set(${result_var} FALSE PARENT_SCOPE)
endfunction()

# Find all llvm-related 'bin' directories inside
# scripts/downloads in case user built/downloaded clang themselves.
file(GLOB POTENTIAL_CLANG_PATHS
        LIST_DIRECTORIES true
        "${CMAKE_SOURCE_DIR}/scripts/downloads/llvm_lib*/bin"
)

# Find the actual clang binary
find_program(CLANG_BIN
        NAMES clang clang-19
        PATHS ${POTENTIAL_CLANG_PATHS}
        VALIDATOR check_clang_version
)

if (CLANG_BIN)
    message(STATUS "Using Clang for built-ins source generation: ${CLANG_BIN}")
else ()
    message(FATAL_ERROR "Clang version ${LLVM_VERSION_MAJOR} not found. A version which matches the used LLVM version is required to generate sources of the built-in library.")
endif ()

set(GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")

set(bc_file "${GENERATED_DIR}/builtins_native.bc")
set(embedding_file "${GENERATED_DIR}/builtins_native.cpp")
set(symbol_name builtins_native_bc)

set(BUILTINS_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src_private/driver_private/builtins")

if (BUILTINS_TARGET)
    set(clang_target_flag "--target=${BUILTINS_TARGET}")
    message(STATUS "Built-in library target: ${BUILTINS_TARGET}")
else ()
    set(clang_target_flag "")
    message(STATUS "Built-in library target: Clang default (host)")
endif ()

# This Clang is not the compiler CMake configured the build with, so it does not pick up the
# macOS SDK on its own. Without a sysroot it resolves no system header at all, not even <cstdint>.
if (APPLE AND NOT BUILTINS_EXTRA_CLANG_FLAGS MATCHES "-isysroot|--sysroot")
    set(builtins_sysroot "${CMAKE_OSX_SYSROOT}")
    if (NOT builtins_sysroot)
        execute_process(
                COMMAND xcrun --show-sdk-path
                OUTPUT_VARIABLE builtins_sysroot
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
        )
    endif ()

    if (builtins_sysroot)
        list(PREPEND BUILTINS_EXTRA_CLANG_FLAGS -isysroot "${builtins_sysroot}")
        message(STATUS "Built-in library sysroot: ${builtins_sysroot}")
    else ()
        message(WARNING "Could not determine the macOS SDK path. If generating the built-in library fails on missing system headers, pass the SDK explicitly via -DBUILTINS_EXTRA_CLANG_FLAGS=\"-isysroot;<sdk-path>\".")
    endif ()
endif ()

# Generate LLVM bitcode by compiling the built-ins source code via clang.
add_custom_command(
        OUTPUT ${bc_file}
        COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
        COMMAND ${CLANG_BIN}
        ${clang_target_flag}
        ${BUILTINS_EXTRA_CLANG_FLAGS}
        -O2
        -emit-llvm
        -c ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
        -o ${bc_file}
        DEPENDS ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
        COMMENT "Generating LLVM bitcode for the built-in library"
        COMMAND_EXPAND_LISTS
)

# Convert the LLVM bitcode to an embedded source file using xxd.
add_custom_command(
        OUTPUT ${embedding_file}
        COMMAND xxd -i -n ${symbol_name} ${bc_file} > ${embedding_file}
        DEPENDS ${bc_file}
        COMMENT "Converting LLVM bitcode to embedded source"
)

set(BUILTINS_EMBEDS ${embedding_file})

add_custom_target(
        builtins_embeds ALL
        DEPENDS ${BUILTINS_EMBEDS}
)

add_custom_target(
        builtins_object_file
        SOURCES ${BUILTINS_SOURCE_DIR}/builtins_source.cpp
)
