# Tests for large packages

Tests:
  package_huge:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0