metadata:
  name: foo
  version: '1.0.0'

dependencies:
  bar:
    source:
      path: ../bar/
    conditions:
      package-features: [f]
    features:
      - b:
          package-features: [f]

features:
  f: []
