PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  @{duck-exe} init bar
  @{duck-exe} -C foo add bar --local=../bar
  echo "    conditions:
        package-features: []" >> foo/quackconfig.yaml

Tests:
  always-false-conditions:
    Description: checks "always_false_conditions" lint
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Err:
          String: |+
            warning: dependency \`bar\` is disabled, because it is conditioned on an empty features list [always_false_conditions]
        Output:
          Run: |+
            echo "info: starting synchronization of the package at \`$DIT_TMP_DIR/foo\`
            info: starting solving the dependency graph
            info: starting gathering the dependency graph
            info: running gathering
            info: starting the solver engine
            info: starting loading 1 package
            info: loaded source code of 1 package, 0 were downloaded, 1 was already present
            info: successfully synchronized venv \`foo\`"
        
