dir_name: ''
cause: ''
dep_name: ''
package_name: 'foo'
add_dep: 'false'
test_cmd: "@{at_tmp_env} duck -C @{dir_name} sync"
root_error: |+
  echo "error: when trying to parse the user manifest at \`${DIT_TMP_DIR}/@{dir_name}/quackconfig.yaml\`
  
    Caused by:
      when parsing the field \`metadata.name\`
  
    Caused by:
      package has an invalid name

    Caused by:
      @{cause}"
dep_error: |+
  echo "error: when trying to parse the user manifest at \`${DIT_TMP_DIR}/@{dir_name}/quackconfig.yaml\`
  
    Caused by:
      when parsing the field \`dependencies.@{dep_name}\`
  
    Caused by:
      dependency \`@{dep_name}\` has an invalid name

    Caused by:
      @{cause}"

PreCase: |+
  cd $DIT_TMP_DIR
  mkdir -p @{dir_name}
  echo "metadata:
    name: '@{package_name}'
    version: 1.0.0" > @{dir_name}/quackconfig.yaml

  if [ '@{add_dep}' == 'true' ]; then
    echo "dependencies:
      '@{dep_name}':
        version: 1" >> @{dir_name}/quackconfig.yaml
  fi
Tests:
  sync:
    Description: name-related errors
    Cases:
      main_package_name_cannot_be_empty:
        dir_name: empty_package_name
        package_name: ''
        cause: package name is empty
        ExitCode: 1
        Err:
          Run: "@{root_error}"
      package_name_starts_with_a_dash:
        dir_name: package_name_starts_with_a_dash
        cause: package name \`-a\` starts with an illegal character \`-\`
        package_name: '-a'
        ExitCode: 1
        Err:
          Run: "@{root_error}"
      package_name_starts_with_an_illegal_character:
        dir_name: package_name_starts_with_an_illegal_character
        cause: package name \`£a\` starts with an illegal character \`£\`
        package_name: '£a'
        ExitCode: 1
        Err:
          Run: "@{root_error}"
      package_name_contains_an_illegal_character:
        dir_name: package_name_contains_an_illegal_character
        cause: package name \`ab-£\` contains an illegal character \`£\`
        ExitCode: 1
        Err:
          Run: "@{root_error}"
      package_name_can_contain_a_dash:
        dir_name: package_name_can_contain_a_dash
        ExitCode: 0
        Output:
          String: 'info: successfully synchronized venv \`foo-bar\`\n'
      dependency_name_cannot_be_empty:
        dir_name: empty_dependency_name
        dep_name: ''
        add_dep: 'true'
        cause: package name is empty
        ExitCode: 1
        Err:
          Run: "@{dep_error}"
      dependency_name_starts_with_a_dash:
        dir_name: dependency_name_starts_with_a_dash
        dep_name: '-a'
        add_dep: 'true'
        cause: package name \`-a\` starts with an illegal character \`-\`
        ExitCode: 1
        Err:
          Run: "@{dep_error}"
      dependency_name_starts_with_an_illegal_character:
        dir_name: dependency_name_starts_with_an_illegal_character
        dep_name: '£a'
        add_dep: 'true'
        cause: package name \`£a\` starts with an illegal character \`£\`
        ExitCode: 1
        Err:
          Run: "@{dep_error}"
      dependency_name_contains_an_illegal_character:
        dir_name: dependency_name_contains_an_illegal_character
        dep_name: 'ab-£'
        add_dep: 'true'
        cause: package name \`ab-£\` contains an illegal character \`£\`
        ExitCode: 1
        Err:
          Run: "@{dep_error}"
