#!/usr/bin/env python3
"""Generate a large Duckling module used for compiler performance testing.

The generated module deliberately sticks to a basic, widely supported subset of
the language (see https://docs.duckling.pl/0.2/duckling/docs.html):

  * namespaces, `const` / `var` globals
  * classes with default-initialized fields, methods and `self` access
  * free functions, expression bodies, overloading
  * `if` / `else if` / `else`, ternary `if ... then ... else ...`
  * `while` loops, `for` over static arrays
  * static arrays, `i64` / `f64` / `bool` arithmetic, `as` casts
  * `and` / `or` / `not`, comparison chaining
  * `builtin_output_i64` / `builtin_output_f64` for output

Deliberately left out: imports, templates, lists, boxes/references, pointers,
FFI, macros, variants, destructors, move/copy semantics, strings.

Usage:
    ./generate_perf_module.py -o perf_large.dmf -l 5000
"""

import argparse
import random

MOD = 1000003


def emit_header(target_lines: int, seed: int) -> list[str]:
	return [
		"#{",
		"    Auto-generated Duckling module for compiler performance testing.",
		"",
		f"    Generated by scripts/perf/generate_perf_module.py (seed {seed},",
		f"    target {target_lines} lines). Do not edit by hand -- regenerate instead.",
		"",
		"    The module is a wide, shallow workload: many independent namespaces,",
		"    each with a couple of classes and a handful of functions exercising",
		"    arithmetic, branching, loops, static arrays, recursion and overloads.",
		"    Everything funnels into a small number of dispatchers called by main,",
		"    so the whole module is reachable and nothing is dead-code eliminated.",
		"#}",
		"",
		"const CHECKSUM_MOD: i64 = 1000003;",
		"const SEED_STEP: i64 = 7;",
		"const TABLE_SIZE: i64 = 8;",
		"",
		"var global_calls: i64 = 0;",
		"var global_accumulator: i64 = 0;",
		"",
	]


def emit_namespace(index: int, rng: random.Random) -> list[str]:
	k = index
	base = rng.randint(2, 97)
	lo = rng.randint(3, 40)
	mid = lo + rng.randint(10, 60)
	hi = mid + rng.randint(10, 120)
	step = rng.randint(2, 13)
	cap = rng.randint(5000, 90000)
	ring = rng.randint(101, 9973)
	scale = rng.randint(2, 9)
	weight = f"{rng.randint(1, 9)}.{rng.randint(1, 9)}"

	return [
		"# " + "-" * 76,
		f"# Module {k}",
		"# " + "-" * 76,
		f"namespace Mod{k} {{",
		f"    const BASE{k}: i64 = {base};",
		f"    const LIMIT{k}: i64 = {cap};",
		f"    var counter{k}: i64 = 0;",
		"",
		f"    class Vec{k} {{",
		f"        x: i64 = {base};",
		f"        y: i64 = {lo};",
		f"        z: i64 = {mid};",
		"",
		"        fun sum() -> i64 = {",
		"            return x + self.y + z;",
		"        }",
		"",
		"        fun scaled(f: i64) -> i64 = {",
		f"            return (x * f) + (self.y * {scale}) - z;",
		"        }",
		"",
		"        fun shift(d: i64) -> i64 = {",
		"            x = x + d;",
		"            self.y = y - d;",
		f"            z = z * {scale} - d;",
		"            return sum();",
		"        }",
		"",
		"        fun dot(o: Vec" + str(k) + ") -> i64 = {",
		"            return x * o.x + y * o.y + z * o.z;",
		"        }",
		"    }",
		"",
		f"    class Stat{k} {{",
		"        total: f64 = 0.0;",
		"        count: i64 = 0;",
		"",
		"        fun push(v: f64) -> f64 = {",
		f"            total = total + v * {weight};",
		"            self.count = count + 1;",
		"            return total;",
		"        }",
		"",
		"        fun mean() -> f64 = {",
		"            if (count == 0) {",
		"                return 0.0;",
		"            }",
		"            return total / (self.count as f64);",
		"        }",
		"    }",
		"",
		"    fun blend(a: i64, b: i64) -> i64 = {",
		f"        let t0 = a * {step} + b;",
		f"        let t1 = t0 - a * {scale};",
		f"        let t2 = (t1 + BASE{k}) * {rng.randint(2, 7)};",
		f"        return (t2 - b) % {ring};",
		"    }",
		"",
		"    fun classify(v: i64) -> i64 = {",
		f"        if (v > {hi}) {{",
		"            return 1;",
		f"        }} else if (v > {mid}) {{",
		"            return 2;",
		f"        }} else if (v > {lo}) {{",
		"            return 3;",
		"        } else if (v > 0) {",
		"            return 4;",
		"        } else {",
		"            return 5;",
		"        }",
		"    }",
		"",
		"    fun accumulate(n: i64) -> i64 = {",
		"        var i: i64 = 0;",
		f"        var acc: i64 = BASE{k};",
		"        while (i < n) {",
		f"            acc = acc + i * {step};",
		f"            if (acc > LIMIT{k}) {{",
		f"                acc = acc - LIMIT{k};",
		"            }",
		"            i = i + 1;",
		"        }",
		"        return acc;",
		"    }",
		"",
		"    fun tabulate(seed: i64) -> i64 = {",
		"        var table: i64[8];",
		"        var i: i64 = 0;",
		"        while (i < 8) {",
		f"            table[i] = seed + i * {step} + BASE{k};",
		"            i = i + 1;",
		"        }",
		"        var acc: i64 = 0;",
		"        for (v in table) {",
		f"            acc = acc + v % {ring};",
		"        }",
		"        return acc;",
		"    }",
		"",
		"    fun scan(seed: i64) -> i64 = {",
		"        var grid: i64[4][4];",
		"        var i: i64 = 0;",
		"        while (i < 4) {",
		"            var j: i64 = 0;",
		"            while (j < 4) {",
		f"                grid[i][j] = (seed + i * 4 + j) % {ring};",
		"                j = j + 1;",
		"            }",
		"            i = i + 1;",
		"        }",
		"        var acc: i64 = 0;",
		"        for (row in grid) {",
		"            for (cell in row) {",
		f"                if (cell > {lo}) {{",
		"                    acc = acc + cell;",
		"                } else {",
		"                    acc = acc - 1;",
		"                }",
		"            }",
		"        }",
		"        return acc;",
		"    }",
		"",
		"    fun descend(n: i64) -> i64 = {",
		"        if (n <= 0) {",
		f"            return BASE{k};",
		"        }",
		f"        return n + descend(n - 1) % {ring};",
		"    }",
		"",
		"    fun search(target: i64) -> i64 = {",
		"        var i: i64 = 0;",
		"        var found: i64 = -1;",
		f"        while (i < {hi} and found < 0) {{",
		f"            if (i * {step} % {ring} == target) {{",
		"                found = i;",
		"            }",
		"            i = i + 1;",
		"        }",
		"        return found;",
		"    }",
		"",
		"    fun inRange(v: i64) -> bool = {",
		f"        return v > {lo} and v < {hi} and not (v == {mid});",
		"    }",
		"",
		"    fun pick(v: i64) -> i64 = {",
		f"        return if inRange(v) then blend(v, {base}) else classify(v);",
		"    }",
		"",
		f"    fun combine(a: i64, b: i64) -> i64 = a + b * {step};",
		f"    fun combine(a: f64, b: f64) -> f64 = a + b * {weight};",
		"",
		"    fun measure(n: i64) -> f64 = {",
		f"        var s = Stat{k}();",
		"        var i: i64 = 0;",
		"        while (i < n) {",
		f"            s.push((i as f64) * {weight});",
		"            i = i + 1;",
		"        }",
		f"        return combine(s.mean(), {weight});",
		"    }",
		"",
		"    fun run(seed: i64) -> i64 = {",
		f"        var v = Vec{k}(seed, seed + 1, seed + 2);",
		f"        var w = Vec{k}();",
		"        var total: i64 = v.sum();",
		f"        total = total + v.scaled({scale});",
		f"        total = total + v.shift({step});",
		"        total = total + v.dot(w);",
		f"        total = total + blend(seed, {base});",
		f"        total = total + classify(total % {ring});",
		f"        total = total + accumulate(seed % 16 + {rng.randint(2, 12)});",
		"        total = total + tabulate(seed);",
		"        total = total + scan(seed);",
		"        total = total + descend(seed % 12);",
		f"        total = total + search(seed % {ring});",
		f"        total = total + pick(seed % {hi});",
		"        total = total + combine(total % 97, seed);",
		f"        total = total + (measure(seed % 8 + 2) as i64);",
		f"        counter{k} = counter{k} + total;",
		"        global_calls = global_calls + 1;",
		"        return total % CHECKSUM_MOD;",
		"    }",
		"",
		f"    fun report() -> i64 = counter{k} % CHECKSUM_MOD;",
		"}",
		"",
	]


def emit_dispatcher(index: int, members: list[int]) -> list[str]:
	lines = [
		"# " + "-" * 76,
		f"# Dispatcher {index}",
		"# " + "-" * 76,
		f"fun dispatch{index}(seed: i64) -> i64 = {{",
		"    var total: i64 = 0;",
		"    var local: i64 = seed;",
	]
	for k in members:
		lines.append(f"    total = total + Mod{k}.run(local);")
		lines.append("    local = local + SEED_STEP;")
	lines += [
		"    return total % CHECKSUM_MOD;",
		"}",
		"",
		f"fun collect{index}() -> i64 = {{",
		"    var total: i64 = 0;",
	]
	for k in members:
		lines.append(f"    total = total + Mod{k}.report();")
	lines += [
		"    return total % CHECKSUM_MOD;",
		"}",
		"",
	]
	return lines


def emit_main(dispatchers: list[int]) -> list[str]:
	lines = [
		"# " + "-" * 76,
		"# Entry point",
		"# " + "-" * 76,
		"fun main() -> i64 = {",
		"    var checksum: i64 = 0;",
		"    var seed: i64 = 1;",
		"",
	]
	for d in dispatchers:
		lines.append(f"    checksum = checksum + dispatch{d}(seed);")
		lines.append("    seed = seed + SEED_STEP;")
	lines += [
		"",
		"    var reports: i64 = 0;",
	]
	for d in dispatchers:
		lines.append(f"    reports = reports + collect{d}();")
	lines += [
		"",
		"    global_accumulator = (checksum + reports) % CHECKSUM_MOD;",
		"",
		"    builtin_output_i64(checksum % CHECKSUM_MOD);",
		"    builtin_output_i64(reports % CHECKSUM_MOD);",
		"    builtin_output_i64(global_calls);",
		"    builtin_output_i64(global_accumulator);",
		"    return 0;",
		"}",
		"",
	]
	return lines


def emit_tail(namespaces: list[int], per_dispatcher: int) -> list[str]:
	tail: list[str] = []
	dispatchers: list[int] = []
	for d, start in enumerate(range(0, len(namespaces), per_dispatcher)):
		tail += emit_dispatcher(d, namespaces[start : start + per_dispatcher])
		dispatchers.append(d)
	return tail + emit_main(dispatchers)


def generate(target_lines: int, seed: int, per_dispatcher: int) -> str:
	rng = random.Random(seed)
	header = emit_header(target_lines, seed)

	# A namespace is a fairly coarse unit (~200 lines), so grow one at a time
	# and keep whichever count lands closest to the requested size.
	blocks: list[list[str]] = []
	previous = len(header) + len(emit_tail([], per_dispatcher))
	while True:
		blocks.append(emit_namespace(len(blocks), rng))
		namespaces = list(range(len(blocks)))
		total = len(header) + sum(len(b) for b in blocks) + len(emit_tail(namespaces, per_dispatcher))
		if total >= target_lines:
			if total - target_lines > target_lines - previous:
				blocks.pop()
			break
		previous = total

	namespaces = list(range(len(blocks)))
	body = [line for block in blocks for line in block]
	return "\n".join(header + body + emit_tail(namespaces, per_dispatcher)) + "\n"


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("-o", "--output", default="perf_large.dmf", help="output file path")
	parser.add_argument("-l", "--lines", type=int, default=5000, help="approximate line count")
	parser.add_argument("-s", "--seed", type=int, default=20260824, help="RNG seed")
	parser.add_argument(
		"-d",
		"--per-dispatcher",
		type=int,
		default=8,
		help="namespaces grouped into a single dispatcher function",
	)
	args = parser.parse_args()

	text = generate(args.lines, args.seed, args.per_dispatcher)
	with open(args.output, "w", encoding="utf-8") as out:
		out.write(text)
	print(f"{args.output}: {text.count(chr(10))} lines")


if __name__ == "__main__":
	main()
