// Copyright 2026 DuckType LLC
//
// This file is part of the Duckling project, licensed under the DuckType
// Compiler License, Version 1.0. See the LICENSE or LICENSE.md file in the root
// of this repository or https://ducktype.org/licenses/DTCL-1.0

//! Layout of the QuackPack's artifacts directory.
//!
//! For main package:
//! <artifacts root>
//! ├── <profile name>/
//! │   ├── *root package artifacts*/
//! │   │   ├── artifacts/ # Duckc artifacts directory
//! │   │   ├── deps.json # JSON used to communicate between QuackPack and duckc.
//! │   │   └── .duck_lock
//! │   └── *useful artifacts of the root package* # artifacts like main executable, main binary, compiled scripts, etc
//! └── .duck_lock # Global artifacts lock
//!
//! For local dependencies:
//! <dependency artifacts root>
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock
//!
//! For git and registry dependencies:
//! <storage root>/pkg/<pkg>/.duck_build/
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock

use std::convert::Infallible;
use std::ops::ControlFlow;
use std::path::PathBuf;

use super::{ArtifactsLayout, DependencyLayout, ProfileLayout};
use crate::quackpack::core::compile::profiles::Profile;
use crate::quackpack::core::compile::unit::graph::{
    CompilationInput, GraphNodeId, UnitGraph, UnitGraphNode,
};
use crate::quackpack::core::compile::unit::graph_visitor::TryGraphVisitor;
use crate::util::file_locks::FileLockManager;
use crate::util::hash::Sha256Hasher;
use crate::{QuackError, QuackResult, qp_bail_internal};

/// Hash the profile value (without the name) and the subgraph of [`UnitGraph`] generated by some [`Unit`].
fn hash_subgraph_and_profile(
    unit_id_in_graph: GraphNodeId,
    graph: &UnitGraph,
    profile: Profile,
) -> QuackResult<String> {
    struct SubgraphHasher<'graph> {
        graph: &'graph UnitGraph,
        hasher: Sha256Hasher,
    }

    impl TryGraphVisitor for SubgraphHasher<'_> {
        type Err = QuackError;

        type Break = Infallible;

        fn try_visit(
            &mut self,
            node: &UnitGraphNode,
        ) -> Result<ControlFlow<Self::Break>, Self::Err> {
            let Some(CompilationInput::PackageSourceCode(identity)) = node.as_input() else {
                return Ok(ControlFlow::Continue(()));
            };
            let package = self
                .graph
                .package_data(*identity)
                .multipackage_schema_package(self.graph)?;
            self.hasher.update(serde_json::to_string(&package)?);
            Ok(ControlFlow::Continue(()))
        }
    }
    let mut hasher = SubgraphHasher {
        graph,
        hasher: Sha256Hasher::new(Some("-")),
    };
    let node = graph.node_for(unit_id_in_graph);
    node.try_accept(&mut hasher, graph)?;
    let mut hasher = hasher.hasher;
    hasher.update(profile.serialize_raw());
    Ok(hasher.into_string())
}

#[derive(Debug, Clone)]
/// Shared layout of the artifacts directory.
/// This means that we do not compile everything in the root unit's build directory,
/// but instead every dependency is compiled in its own build directory.
/// See the [module](super::shared_artifacts_layout) documentation.
pub struct SharedArtifactsLayout {
    root: FileLockManager,
}

impl SharedArtifactsLayout {
    /// Create a new [`SharedArtifactsLayout`].
    pub fn new(root: PathBuf) -> Self {
        Self {
            root: FileLockManager::new(root),
        }
    }
}

impl ArtifactsLayout for SharedArtifactsLayout {
    fn for_profile(&self, profile: Profile) -> Box<dyn ProfileLayout> {
        Box::new(SharedProfileLayout {
            root: self.root.join(profile.name),
            profile,
        })
    }

    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific profile.
pub struct SharedProfileLayout {
    root: FileLockManager,
    profile: Profile,
}

impl ProfileLayout for SharedProfileLayout {
    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }

    fn for_dependency(
        &self,
        unit_id_in_graph: GraphNodeId,
        graph: &UnitGraph,
    ) -> QuackResult<Box<dyn DependencyLayout>> {
        let node = graph.node_for(unit_id_in_graph);
        let Some(unit) = node.as_unit() else {
            qp_bail_internal!(
                "node {node:?} is not a unit, but called for dependency layout for it"
            )
        };
        let path = if graph.is_root(unit) {
            self.root_directory().join(unit.pkg_unique_name())
        } else {
            let hash = hash_subgraph_and_profile(unit_id_in_graph, graph, self.profile)?;
            unit.package()
                .artifacts_directory()
                .join(format!("shared-{hash}"))
        };
        Ok(Box::new(SharedDependencyLayout {
            root: FileLockManager::new(path),
        }))
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific dependency.
pub struct SharedDependencyLayout {
    root: FileLockManager,
}

impl DependencyLayout for SharedDependencyLayout {
    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }
}
