//! Layout of the QuackPack's artifacts directory.
//!
//! For main package:
//! <artifacts root>
//! ├── <profile name>/
//! │   ├── *root package artifacts*/
//! │   │   ├── artifacts/ # Duckc artifacts directory
//! │   │   ├── deps.json # JSON used to communicate between QuackPack and duckc.
//! │   │   └── .duck_lock
//! │   └── *useful artifacts of the root package* # artifacts like main executable, main binary, compiled scripts, etc
//! └── .duck_lock # Global artifacts lock
//!
//! For local dependencies:
//! <dependency artifacts root>
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock
//!
//! For local dependencies:
//! <storage root>/pkg/<pkg>/.duck_build/
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock

use std::path::{Path, PathBuf};

use crate::quackpack::core::compile::artifacts_layout::{
    ArtifactsLayout, DependencyLayout, ProfileLayout,
};
use crate::quackpack::core::compile::executor::collect_packages;
use crate::quackpack::core::compile::profiles::Profile;
use crate::quackpack::core::compile::unit::Unit;
use crate::quackpack::core::compile::unit::graph::UnitGraph;
use crate::util::file_locks::{FileLockManager, LockedFile};
use crate::util::hash::Sha256Hasher;
use crate::{DuckContext, QuackResult};

/// Hash the profile value (without the name) and the subgraph of [`UnitGraph`] generated by some [`Unit`].
fn hash_subgraph_and_profile(
    unit: &Unit,
    graph: &UnitGraph,
    profile: Profile,
) -> QuackResult<String> {
    let mut hasher = Sha256Hasher::new("-");
    for package in collect_packages(unit, graph)? {
        hasher.update(serde_json::to_string(&package)?);
    }
    hasher.update(profile.serialize_raw());
    Ok(hasher.into_string())
}

#[derive(Debug, Clone)]
/// Shared layout of the artifacts directory.
/// This means that we do not compile everythink in the root unit's build directory,
/// but instead every dependency is compiled in its own build directory.
/// See the [module](super::shared_artifacts_layout) documentation.
pub struct SharedArtifactsLayout {
    root: FileLockManager,
}

impl ArtifactsLayout for SharedArtifactsLayout {
    fn new(root: PathBuf) -> Self {
        Self {
            root: FileLockManager::new(root),
        }
    }

    fn root_directory(&self) -> &Path {
        self.root.not_locked_path()
    }

    fn acquire_global_lock(&self, ctx: &DuckContext) -> QuackResult<LockedFile> {
        self.root.open_exclusive(Self::GLOBAL_LOCK_NAME, ctx)
    }

    fn for_profile(&self, profile: Profile) -> impl ProfileLayout {
        SharedProfileLayout {
            root: self.root.join(profile.name),
            profile,
        }
    }

    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific profile.
pub struct SharedProfileLayout {
    root: FileLockManager,
    profile: Profile,
}

impl ProfileLayout for SharedProfileLayout {
    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }

    fn root_directory(&self) -> &Path {
        self.root.not_locked_path()
    }

    fn for_dependency(&self, unit: &Unit, graph: &UnitGraph) -> QuackResult<impl DependencyLayout> {
        let path = if graph.is_root(unit) {
            self.root_directory().join(unit.unique_name())
        } else {
            let hash = hash_subgraph_and_profile(unit, graph, self.profile)?;
            unit.root_package()
                .package()
                .artifacts_directory()
                .join(hash)
        };
        Ok(SharedDependencyLayout {
            root: FileLockManager::new(path),
        })
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific dependency.
pub struct SharedDependencyLayout {
    root: FileLockManager,
}

impl DependencyLayout for SharedDependencyLayout {
    const LOCK_NAME: &str = ".duck_lock";
    const JSON_NAME: &str = "deps.json";

    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }

    fn root_directory(&self) -> &Path {
        self.root.not_locked_path()
    }

    fn acquire_lock(&self, ctx: &DuckContext) -> QuackResult<LockedFile> {
        self.root.open_exclusive(Self::LOCK_NAME, ctx)
    }

    fn compiler_artifacts(&self) -> PathBuf {
        self.root_directory().join("artifacts")
    }

    fn dependency_json(&self, ctx: &DuckContext) -> QuackResult<LockedFile> {
        self.root.open_exclusive(Self::JSON_NAME, ctx)
    }

    fn dependency_json_path(&self) -> PathBuf {
        self.root_directory().join(Self::JSON_NAME)
    }
}
