//! Layout of the QuackPack's artifacts directory.
//!
//! For main package:
//! <artifacts root>
//! ├── <profile name>/
//! │   ├── *root package artifacts*/
//! │   │   ├── artifacts/ # Duckc artifacts directory
//! │   │   ├── deps.json # JSON used to communicate between QuackPack and duckc.
//! │   │   └── .duck_lock
//! │   └── *useful artifacts of the root package* # artifacts like main executable, main binary, compiled scripts, etc
//! └── .duck_lock # Global artifacts lock
//!
//! For local dependencies:
//! <dependency artifacts root>
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock
//!
//! For git and registry dependencies:
//! <storage root>/pkg/<pkg>/.duck_build/
//! └── <hash of unit subgraph and profile>/
//!     ├── *generated artifacts of the dependency*
//!     ├── artifacts/ # Duckc artifacts directory
//!     ├── deps.json # JSON used to communicate between QuackPack and duckc.
//!     └── .duck_lock # Per dependency lock

use std::path::PathBuf;

use crate::QuackResult;
use crate::quackpack::core::compile::artifacts_layout::{
    ArtifactsLayout, DependencyLayout, ProfileLayout,
};
use crate::quackpack::core::compile::profiles::Profile;
use crate::quackpack::core::compile::unit::Unit;
use crate::quackpack::core::compile::unit::graph::UnitGraph;
use crate::quackpack::core::compile::unit::unit_visitor::UnitVisitor;
use crate::util::file_locks::FileLockManager;
use crate::util::hash::Sha256Hasher;

/// Hash the profile value (without the name) and the subgraph of [`UnitGraph`] generated by some [`Unit`].
fn hash_subgraph_and_profile(
    unit: &Unit,
    graph: &UnitGraph,
    profile: Profile,
) -> QuackResult<String> {
    struct SubgraphHasher<'graph> {
        graph: &'graph UnitGraph,
        hasher: Sha256Hasher,
    }

    impl UnitVisitor for SubgraphHasher<'_> {
        fn visit(&mut self, unit: &Unit) -> QuackResult<()> {
            let package = unit.multipackage_schema_package(self.graph)?;
            self.hasher.update(serde_json::to_string(&package)?);
            Ok(())
        }
    }
    let mut hasher = SubgraphHasher {
        graph,
        hasher: Sha256Hasher::new(Some("-")),
    };
    unit.accept(&mut hasher, graph)?;
    let mut hasher = hasher.hasher;
    hasher.update(profile.serialize_raw());
    Ok(hasher.into_string())
}

#[derive(Debug, Clone)]
/// Shared layout of the artifacts directory.
/// This means that we do not compile everything in the root unit's build directory,
/// but instead every dependency is compiled in its own build directory.
/// See the [module](super::shared_artifacts_layout) documentation.
pub struct SharedArtifactsLayout {
    root: FileLockManager,
}

impl ArtifactsLayout for SharedArtifactsLayout {
    fn new(root: PathBuf) -> Self {
        Self {
            root: FileLockManager::new(root),
        }
    }

    fn for_profile(&self, profile: Profile) -> impl ProfileLayout {
        SharedProfileLayout {
            root: self.root.join(profile.name),
            profile,
        }
    }

    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific profile.
pub struct SharedProfileLayout {
    root: FileLockManager,
    profile: Profile,
}

impl ProfileLayout for SharedProfileLayout {
    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }

    fn for_dependency(&self, unit: &Unit, graph: &UnitGraph) -> QuackResult<impl DependencyLayout> {
        let path = if graph.is_root(unit) {
            self.root_directory().join(unit.unique_name())
        } else {
            let hash = hash_subgraph_and_profile(unit, graph, self.profile)?;
            unit.root_package()
                .package()
                .artifacts_directory()
                .join(format!("shared-{hash}"))
        };
        Ok(SharedDependencyLayout {
            root: FileLockManager::new(path),
        })
    }
}

#[derive(Debug, Clone)]
/// A struct responsible for a shared layout of a specific dependency.
pub struct SharedDependencyLayout {
    root: FileLockManager,
}

impl DependencyLayout for SharedDependencyLayout {
    fn file_lock_manager(&self) -> &FileLockManager {
        &self.root
    }
}
