Tests:
  init:
    Description: cannot reinitialise a project
    Cases:
      init:
        test_cmd: duck init foo --name bar
        PreCase: |+
          cd $DIT_TMP_DIR
          @{duck_exe} init foo
        ExitCode: 1
        Err:
          Run: |+
            echo "error: cannot reinitialize project \`foo\` at \`$DIT_TMP_DIR/foo\`"
