Tests:
  init:
    Description: cannot reinitialise a project
    Cases:
      init:
        test_cmd: duck init foo --name bar
        ExitCode: 1
        Err:
          Run: |+
            echo "error: cannot reinitialize project \`foo\` at \`$(pwd)/foo\`"
