// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: view.proto
// Protobuf C++ Version: 5.29.0

#ifndef view_2eproto_2epb_2eh
#define view_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_view_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_view_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_view_2eproto;
namespace view {
class ClickRequest;
struct ClickRequestDefaultTypeInternal;
extern ClickRequestDefaultTypeInternal _ClickRequest_default_instance_;
class ClickResponse;
struct ClickResponseDefaultTypeInternal;
extern ClickResponseDefaultTypeInternal _ClickResponse_default_instance_;
class Component;
struct ComponentDefaultTypeInternal;
extern ComponentDefaultTypeInternal _Component_default_instance_;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class ListComponent;
struct ListComponentDefaultTypeInternal;
extern ListComponentDefaultTypeInternal _ListComponent_default_instance_;
class TextComponent;
struct TextComponentDefaultTypeInternal;
extern TextComponentDefaultTypeInternal _TextComponent_default_instance_;
class TextEntry;
struct TextEntryDefaultTypeInternal;
extern TextEntryDefaultTypeInternal _TextEntry_default_instance_;
class ViewResponse;
struct ViewResponseDefaultTypeInternal;
extern ViewResponseDefaultTypeInternal _ViewResponse_default_instance_;
}  // namespace view
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace view {
enum TextDisplayType : int {
  PLAIN = 0,
  CODE = 1,
  TextDisplayType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TextDisplayType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TextDisplayType_IsValid(int value);
extern const uint32_t TextDisplayType_internal_data_[];
constexpr TextDisplayType TextDisplayType_MIN = static_cast<TextDisplayType>(0);
constexpr TextDisplayType TextDisplayType_MAX = static_cast<TextDisplayType>(1);
constexpr int TextDisplayType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
TextDisplayType_descriptor();
template <typename T>
const std::string& TextDisplayType_Name(T value) {
  static_assert(std::is_same<T, TextDisplayType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TextDisplayType_Name().");
  return TextDisplayType_Name(static_cast<TextDisplayType>(value));
}
template <>
inline const std::string& TextDisplayType_Name(TextDisplayType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TextDisplayType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool TextDisplayType_Parse(absl::string_view name, TextDisplayType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TextDisplayType>(
      TextDisplayType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class TextEntry final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.TextEntry) */ {
 public:
  inline TextEntry() : TextEntry(nullptr) {}
  ~TextEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TextEntry* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TextEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TextEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline TextEntry(const TextEntry& from) : TextEntry(nullptr, from) {}
  inline TextEntry(TextEntry&& from) noexcept
      : TextEntry(nullptr, std::move(from)) {}
  inline TextEntry& operator=(const TextEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextEntry& operator=(TextEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TextEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const TextEntry* internal_default_instance() {
    return reinterpret_cast<const TextEntry*>(
        &_TextEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TextEntry& a, TextEntry& b) { a.Swap(&b); }
  inline void Swap(TextEntry* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TextEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TextEntry* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TextEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TextEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TextEntry& from) { TextEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TextEntry* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.TextEntry"; }

 protected:
  explicit TextEntry(::google::protobuf::Arena* arena);
  TextEntry(::google::protobuf::Arena* arena, const TextEntry& from);
  TextEntry(::google::protobuf::Arena* arena, TextEntry&& from) noexcept
      : TextEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTextFieldNumber = 1,
    kTypeFieldNumber = 2,
    kGroupIdFieldNumber = 3,
  };
  // string text = 1;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* value);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  // .view.TextDisplayType type = 2;
  void clear_type() ;
  ::view::TextDisplayType type() const;
  void set_type(::view::TextDisplayType value);

  private:
  ::view::TextDisplayType _internal_type() const;
  void _internal_set_type(::view::TextDisplayType value);

  public:
  // int32 group_id = 3;
  void clear_group_id() ;
  ::int32_t group_id() const;
  void set_group_id(::int32_t value);

  private:
  ::int32_t _internal_group_id() const;
  void _internal_set_group_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:view.TextEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TextEntry& from_msg);
    ::google::protobuf::internal::ArenaStringPtr text_;
    int type_;
    ::int32_t group_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class Empty final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:view.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Empty* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Empty));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Empty(
      ::google::protobuf::internal::ConstantInitialized);

  inline Empty(const Empty& from) : Empty(nullptr, from) {}
  inline Empty(Empty&& from) noexcept
      : Empty(nullptr, std::move(from)) {}
  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
        &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(Empty& a, Empty& b) { a.Swap(&b); }
  inline void Swap(Empty* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Empty>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Empty& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Empty& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.Empty"; }

 protected:
  explicit Empty(::google::protobuf::Arena* arena);
  Empty(::google::protobuf::Arena* arena, const Empty& from);
  Empty(::google::protobuf::Arena* arena, Empty&& from) noexcept
      : Empty(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:view.Empty)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Empty& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class ClickResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.ClickResponse) */ {
 public:
  inline ClickResponse() : ClickResponse(nullptr) {}
  ~ClickResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ClickResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ClickResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ClickResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ClickResponse(const ClickResponse& from) : ClickResponse(nullptr, from) {}
  inline ClickResponse(ClickResponse&& from) noexcept
      : ClickResponse(nullptr, std::move(from)) {}
  inline ClickResponse& operator=(const ClickResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClickResponse& operator=(ClickResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClickResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClickResponse* internal_default_instance() {
    return reinterpret_cast<const ClickResponse*>(
        &_ClickResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(ClickResponse& a, ClickResponse& b) { a.Swap(&b); }
  inline void Swap(ClickResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClickResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClickResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ClickResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClickResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ClickResponse& from) { ClickResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ClickResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.ClickResponse"; }

 protected:
  explicit ClickResponse(::google::protobuf::Arena* arena);
  ClickResponse(::google::protobuf::Arena* arena, const ClickResponse& from);
  ClickResponse(::google::protobuf::Arena* arena, ClickResponse&& from) noexcept
      : ClickResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // string status = 1;
  void clear_status() ;
  const std::string& status() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_status(Arg_&& arg, Args_... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* value);

  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(
      const std::string& value);
  std::string* _internal_mutable_status();

  public:
  // @@protoc_insertion_point(class_scope:view.ClickResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      33, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ClickResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class ClickRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.ClickRequest) */ {
 public:
  inline ClickRequest() : ClickRequest(nullptr) {}
  ~ClickRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ClickRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ClickRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ClickRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ClickRequest(const ClickRequest& from) : ClickRequest(nullptr, from) {}
  inline ClickRequest(ClickRequest&& from) noexcept
      : ClickRequest(nullptr, std::move(from)) {}
  inline ClickRequest& operator=(const ClickRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClickRequest& operator=(ClickRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClickRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClickRequest* internal_default_instance() {
    return reinterpret_cast<const ClickRequest*>(
        &_ClickRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(ClickRequest& a, ClickRequest& b) { a.Swap(&b); }
  inline void Swap(ClickRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClickRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClickRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ClickRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClickRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ClickRequest& from) { ClickRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ClickRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.ClickRequest"; }

 protected:
  explicit ClickRequest(::google::protobuf::Arena* arena);
  ClickRequest(::google::protobuf::Arena* arena, const ClickRequest& from);
  ClickRequest(::google::protobuf::Arena* arena, ClickRequest&& from) noexcept
      : ClickRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectIdFieldNumber = 1,
  };
  // int32 object_id = 1;
  void clear_object_id() ;
  ::int32_t object_id() const;
  void set_object_id(::int32_t value);

  private:
  ::int32_t _internal_object_id() const;
  void _internal_set_object_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:view.ClickRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ClickRequest& from_msg);
    ::int32_t object_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class TextComponent final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.TextComponent) */ {
 public:
  inline TextComponent() : TextComponent(nullptr) {}
  ~TextComponent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TextComponent* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TextComponent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TextComponent(
      ::google::protobuf::internal::ConstantInitialized);

  inline TextComponent(const TextComponent& from) : TextComponent(nullptr, from) {}
  inline TextComponent(TextComponent&& from) noexcept
      : TextComponent(nullptr, std::move(from)) {}
  inline TextComponent& operator=(const TextComponent& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextComponent& operator=(TextComponent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TextComponent& default_instance() {
    return *internal_default_instance();
  }
  static inline const TextComponent* internal_default_instance() {
    return reinterpret_cast<const TextComponent*>(
        &_TextComponent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TextComponent& a, TextComponent& b) { a.Swap(&b); }
  inline void Swap(TextComponent* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TextComponent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TextComponent* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TextComponent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TextComponent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TextComponent& from) { TextComponent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TextComponent* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.TextComponent"; }

 protected:
  explicit TextComponent(::google::protobuf::Arena* arena);
  TextComponent(::google::protobuf::Arena* arena, const TextComponent& from);
  TextComponent(::google::protobuf::Arena* arena, TextComponent&& from) noexcept
      : TextComponent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEntriesFieldNumber = 1,
  };
  // repeated .view.TextEntry entries = 1;
  int entries_size() const;
  private:
  int _internal_entries_size() const;

  public:
  void clear_entries() ;
  ::view::TextEntry* mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField<::view::TextEntry>* mutable_entries();

  private:
  const ::google::protobuf::RepeatedPtrField<::view::TextEntry>& _internal_entries() const;
  ::google::protobuf::RepeatedPtrField<::view::TextEntry>* _internal_mutable_entries();
  public:
  const ::view::TextEntry& entries(int index) const;
  ::view::TextEntry* add_entries();
  const ::google::protobuf::RepeatedPtrField<::view::TextEntry>& entries() const;
  // @@protoc_insertion_point(class_scope:view.TextComponent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TextComponent& from_msg);
    ::google::protobuf::RepeatedPtrField< ::view::TextEntry > entries_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class Component final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.Component) */ {
 public:
  inline Component() : Component(nullptr) {}
  ~Component() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Component* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Component));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Component(
      ::google::protobuf::internal::ConstantInitialized);

  inline Component(const Component& from) : Component(nullptr, from) {}
  inline Component(Component&& from) noexcept
      : Component(nullptr, std::move(from)) {}
  inline Component& operator=(const Component& from) {
    CopyFrom(from);
    return *this;
  }
  inline Component& operator=(Component&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Component& default_instance() {
    return *internal_default_instance();
  }
  enum ComponentCase {
    kTextComponent = 1,
    kListComponent = 2,
    COMPONENT_NOT_SET = 0,
  };
  static inline const Component* internal_default_instance() {
    return reinterpret_cast<const Component*>(
        &_Component_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Component& a, Component& b) { a.Swap(&b); }
  inline void Swap(Component* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Component* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Component* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Component>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Component& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Component& from) { Component::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Component* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.Component"; }

 protected:
  explicit Component(::google::protobuf::Arena* arena);
  Component(::google::protobuf::Arena* arena, const Component& from);
  Component(::google::protobuf::Arena* arena, Component&& from) noexcept
      : Component(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 3,
    kTextComponentFieldNumber = 1,
    kListComponentFieldNumber = 2,
  };
  // int32 id = 3;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // .view.TextComponent text_component = 1;
  bool has_text_component() const;
  private:
  bool _internal_has_text_component() const;

  public:
  void clear_text_component() ;
  const ::view::TextComponent& text_component() const;
  PROTOBUF_NODISCARD ::view::TextComponent* release_text_component();
  ::view::TextComponent* mutable_text_component();
  void set_allocated_text_component(::view::TextComponent* value);
  void unsafe_arena_set_allocated_text_component(::view::TextComponent* value);
  ::view::TextComponent* unsafe_arena_release_text_component();

  private:
  const ::view::TextComponent& _internal_text_component() const;
  ::view::TextComponent* _internal_mutable_text_component();

  public:
  // .view.ListComponent list_component = 2;
  bool has_list_component() const;
  private:
  bool _internal_has_list_component() const;

  public:
  void clear_list_component() ;
  const ::view::ListComponent& list_component() const;
  PROTOBUF_NODISCARD ::view::ListComponent* release_list_component();
  ::view::ListComponent* mutable_list_component();
  void set_allocated_list_component(::view::ListComponent* value);
  void unsafe_arena_set_allocated_list_component(::view::ListComponent* value);
  ::view::ListComponent* unsafe_arena_release_list_component();

  private:
  const ::view::ListComponent& _internal_list_component() const;
  ::view::ListComponent* _internal_mutable_list_component();

  public:
  void clear_component();
  ComponentCase component_case() const;
  // @@protoc_insertion_point(class_scope:view.Component)
 private:
  class _Internal;
  void set_has_text_component();
  void set_has_list_component();
  inline bool has_component() const;
  inline void clear_has_component();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Component& from_msg);
    ::int32_t id_;
    union ComponentUnion {
      constexpr ComponentUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::view::TextComponent* text_component_;
      ::view::ListComponent* list_component_;
    } component_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class ListComponent final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.ListComponent) */ {
 public:
  inline ListComponent() : ListComponent(nullptr) {}
  ~ListComponent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListComponent* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListComponent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListComponent(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListComponent(const ListComponent& from) : ListComponent(nullptr, from) {}
  inline ListComponent(ListComponent&& from) noexcept
      : ListComponent(nullptr, std::move(from)) {}
  inline ListComponent& operator=(const ListComponent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListComponent& operator=(ListComponent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListComponent& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListComponent* internal_default_instance() {
    return reinterpret_cast<const ListComponent*>(
        &_ListComponent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ListComponent& a, ListComponent& b) { a.Swap(&b); }
  inline void Swap(ListComponent* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListComponent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListComponent* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListComponent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListComponent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListComponent& from) { ListComponent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListComponent* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.ListComponent"; }

 protected:
  explicit ListComponent(::google::protobuf::Arena* arena);
  ListComponent(::google::protobuf::Arena* arena, const ListComponent& from);
  ListComponent(::google::protobuf::Arena* arena, ListComponent&& from) noexcept
      : ListComponent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kComponentsFieldNumber = 1,
  };
  // repeated .view.Component components = 1;
  int components_size() const;
  private:
  int _internal_components_size() const;

  public:
  void clear_components() ;
  ::view::Component* mutable_components(int index);
  ::google::protobuf::RepeatedPtrField<::view::Component>* mutable_components();

  private:
  const ::google::protobuf::RepeatedPtrField<::view::Component>& _internal_components() const;
  ::google::protobuf::RepeatedPtrField<::view::Component>* _internal_mutable_components();
  public:
  const ::view::Component& components(int index) const;
  ::view::Component* add_components();
  const ::google::protobuf::RepeatedPtrField<::view::Component>& components() const;
  // @@protoc_insertion_point(class_scope:view.ListComponent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListComponent& from_msg);
    ::google::protobuf::RepeatedPtrField< ::view::Component > components_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};
// -------------------------------------------------------------------

class ViewResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:view.ViewResponse) */ {
 public:
  inline ViewResponse() : ViewResponse(nullptr) {}
  ~ViewResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ViewResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ViewResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ViewResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ViewResponse(const ViewResponse& from) : ViewResponse(nullptr, from) {}
  inline ViewResponse(ViewResponse&& from) noexcept
      : ViewResponse(nullptr, std::move(from)) {}
  inline ViewResponse& operator=(const ViewResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ViewResponse& operator=(ViewResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ViewResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ViewResponse* internal_default_instance() {
    return reinterpret_cast<const ViewResponse*>(
        &_ViewResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ViewResponse& a, ViewResponse& b) { a.Swap(&b); }
  inline void Swap(ViewResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ViewResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ViewResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ViewResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ViewResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ViewResponse& from) { ViewResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ViewResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "view.ViewResponse"; }

 protected:
  explicit ViewResponse(::google::protobuf::Arena* arena);
  ViewResponse(::google::protobuf::Arena* arena, const ViewResponse& from);
  ViewResponse(::google::protobuf::Arena* arena, ViewResponse&& from) noexcept
      : ViewResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kComponentFieldNumber = 1,
  };
  // .view.Component component = 1;
  bool has_component() const;
  void clear_component() ;
  const ::view::Component& component() const;
  PROTOBUF_NODISCARD ::view::Component* release_component();
  ::view::Component* mutable_component();
  void set_allocated_component(::view::Component* value);
  void unsafe_arena_set_allocated_component(::view::Component* value);
  ::view::Component* unsafe_arena_release_component();

  private:
  const ::view::Component& _internal_component() const;
  ::view::Component* _internal_mutable_component();

  public:
  // @@protoc_insertion_point(class_scope:view.ViewResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ViewResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::view::Component* component_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_view_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TextEntry

// string text = 1;
inline void TextEntry::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
}
inline const std::string& TextEntry::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.TextEntry.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TextEntry::set_text(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:view.TextEntry.text)
}
inline std::string* TextEntry::mutable_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:view.TextEntry.text)
  return _s;
}
inline const std::string& TextEntry::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void TextEntry::_internal_set_text(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline std::string* TextEntry::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline std::string* TextEntry::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:view.TextEntry.text)
  return _impl_.text_.Release();
}
inline void TextEntry::set_allocated_text(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:view.TextEntry.text)
}

// .view.TextDisplayType type = 2;
inline void TextEntry::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::view::TextDisplayType TextEntry::type() const {
  // @@protoc_insertion_point(field_get:view.TextEntry.type)
  return _internal_type();
}
inline void TextEntry::set_type(::view::TextDisplayType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:view.TextEntry.type)
}
inline ::view::TextDisplayType TextEntry::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::view::TextDisplayType>(_impl_.type_);
}
inline void TextEntry::_internal_set_type(::view::TextDisplayType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// int32 group_id = 3;
inline void TextEntry::clear_group_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_id_ = 0;
}
inline ::int32_t TextEntry::group_id() const {
  // @@protoc_insertion_point(field_get:view.TextEntry.group_id)
  return _internal_group_id();
}
inline void TextEntry::set_group_id(::int32_t value) {
  _internal_set_group_id(value);
  // @@protoc_insertion_point(field_set:view.TextEntry.group_id)
}
inline ::int32_t TextEntry::_internal_group_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.group_id_;
}
inline void TextEntry::_internal_set_group_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_id_ = value;
}

// -------------------------------------------------------------------

// TextComponent

// repeated .view.TextEntry entries = 1;
inline int TextComponent::_internal_entries_size() const {
  return _internal_entries().size();
}
inline int TextComponent::entries_size() const {
  return _internal_entries_size();
}
inline void TextComponent::clear_entries() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entries_.Clear();
}
inline ::view::TextEntry* TextComponent::mutable_entries(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:view.TextComponent.entries)
  return _internal_mutable_entries()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::view::TextEntry>* TextComponent::mutable_entries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:view.TextComponent.entries)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_entries();
}
inline const ::view::TextEntry& TextComponent::entries(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.TextComponent.entries)
  return _internal_entries().Get(index);
}
inline ::view::TextEntry* TextComponent::add_entries() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::view::TextEntry* _add = _internal_mutable_entries()->Add();
  // @@protoc_insertion_point(field_add:view.TextComponent.entries)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::view::TextEntry>& TextComponent::entries() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:view.TextComponent.entries)
  return _internal_entries();
}
inline const ::google::protobuf::RepeatedPtrField<::view::TextEntry>&
TextComponent::_internal_entries() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entries_;
}
inline ::google::protobuf::RepeatedPtrField<::view::TextEntry>*
TextComponent::_internal_mutable_entries() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.entries_;
}

// -------------------------------------------------------------------

// ListComponent

// repeated .view.Component components = 1;
inline int ListComponent::_internal_components_size() const {
  return _internal_components().size();
}
inline int ListComponent::components_size() const {
  return _internal_components_size();
}
inline void ListComponent::clear_components() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.components_.Clear();
}
inline ::view::Component* ListComponent::mutable_components(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:view.ListComponent.components)
  return _internal_mutable_components()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::view::Component>* ListComponent::mutable_components()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:view.ListComponent.components)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_components();
}
inline const ::view::Component& ListComponent::components(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.ListComponent.components)
  return _internal_components().Get(index);
}
inline ::view::Component* ListComponent::add_components() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::view::Component* _add = _internal_mutable_components()->Add();
  // @@protoc_insertion_point(field_add:view.ListComponent.components)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::view::Component>& ListComponent::components() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:view.ListComponent.components)
  return _internal_components();
}
inline const ::google::protobuf::RepeatedPtrField<::view::Component>&
ListComponent::_internal_components() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.components_;
}
inline ::google::protobuf::RepeatedPtrField<::view::Component>*
ListComponent::_internal_mutable_components() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.components_;
}

// -------------------------------------------------------------------

// Component

// int32 id = 3;
inline void Component::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t Component::id() const {
  // @@protoc_insertion_point(field_get:view.Component.id)
  return _internal_id();
}
inline void Component::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:view.Component.id)
}
inline ::int32_t Component::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Component::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .view.TextComponent text_component = 1;
inline bool Component::has_text_component() const {
  return component_case() == kTextComponent;
}
inline bool Component::_internal_has_text_component() const {
  return component_case() == kTextComponent;
}
inline void Component::set_has_text_component() {
  _impl_._oneof_case_[0] = kTextComponent;
}
inline void Component::clear_text_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (component_case() == kTextComponent) {
    if (GetArena() == nullptr) {
      delete _impl_.component_.text_component_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.component_.text_component_);
    }
    clear_has_component();
  }
}
inline ::view::TextComponent* Component::release_text_component() {
  // @@protoc_insertion_point(field_release:view.Component.text_component)
  if (component_case() == kTextComponent) {
    clear_has_component();
    auto* temp = _impl_.component_.text_component_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.component_.text_component_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::view::TextComponent& Component::_internal_text_component() const {
  return component_case() == kTextComponent ? *_impl_.component_.text_component_ : reinterpret_cast<::view::TextComponent&>(::view::_TextComponent_default_instance_);
}
inline const ::view::TextComponent& Component::text_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.Component.text_component)
  return _internal_text_component();
}
inline ::view::TextComponent* Component::unsafe_arena_release_text_component() {
  // @@protoc_insertion_point(field_unsafe_arena_release:view.Component.text_component)
  if (component_case() == kTextComponent) {
    clear_has_component();
    auto* temp = _impl_.component_.text_component_;
    _impl_.component_.text_component_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Component::unsafe_arena_set_allocated_text_component(::view::TextComponent* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_component();
  if (value) {
    set_has_text_component();
    _impl_.component_.text_component_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:view.Component.text_component)
}
inline ::view::TextComponent* Component::_internal_mutable_text_component() {
  if (component_case() != kTextComponent) {
    clear_component();
    set_has_text_component();
    _impl_.component_.text_component_ =
        ::google::protobuf::Message::DefaultConstruct<::view::TextComponent>(GetArena());
  }
  return _impl_.component_.text_component_;
}
inline ::view::TextComponent* Component::mutable_text_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::view::TextComponent* _msg = _internal_mutable_text_component();
  // @@protoc_insertion_point(field_mutable:view.Component.text_component)
  return _msg;
}

// .view.ListComponent list_component = 2;
inline bool Component::has_list_component() const {
  return component_case() == kListComponent;
}
inline bool Component::_internal_has_list_component() const {
  return component_case() == kListComponent;
}
inline void Component::set_has_list_component() {
  _impl_._oneof_case_[0] = kListComponent;
}
inline void Component::clear_list_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (component_case() == kListComponent) {
    if (GetArena() == nullptr) {
      delete _impl_.component_.list_component_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.component_.list_component_);
    }
    clear_has_component();
  }
}
inline ::view::ListComponent* Component::release_list_component() {
  // @@protoc_insertion_point(field_release:view.Component.list_component)
  if (component_case() == kListComponent) {
    clear_has_component();
    auto* temp = _impl_.component_.list_component_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.component_.list_component_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::view::ListComponent& Component::_internal_list_component() const {
  return component_case() == kListComponent ? *_impl_.component_.list_component_ : reinterpret_cast<::view::ListComponent&>(::view::_ListComponent_default_instance_);
}
inline const ::view::ListComponent& Component::list_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.Component.list_component)
  return _internal_list_component();
}
inline ::view::ListComponent* Component::unsafe_arena_release_list_component() {
  // @@protoc_insertion_point(field_unsafe_arena_release:view.Component.list_component)
  if (component_case() == kListComponent) {
    clear_has_component();
    auto* temp = _impl_.component_.list_component_;
    _impl_.component_.list_component_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Component::unsafe_arena_set_allocated_list_component(::view::ListComponent* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_component();
  if (value) {
    set_has_list_component();
    _impl_.component_.list_component_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:view.Component.list_component)
}
inline ::view::ListComponent* Component::_internal_mutable_list_component() {
  if (component_case() != kListComponent) {
    clear_component();
    set_has_list_component();
    _impl_.component_.list_component_ =
        ::google::protobuf::Message::DefaultConstruct<::view::ListComponent>(GetArena());
  }
  return _impl_.component_.list_component_;
}
inline ::view::ListComponent* Component::mutable_list_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::view::ListComponent* _msg = _internal_mutable_list_component();
  // @@protoc_insertion_point(field_mutable:view.Component.list_component)
  return _msg;
}

inline bool Component::has_component() const {
  return component_case() != COMPONENT_NOT_SET;
}
inline void Component::clear_has_component() {
  _impl_._oneof_case_[0] = COMPONENT_NOT_SET;
}
inline Component::ComponentCase Component::component_case() const {
  return Component::ComponentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ViewResponse

// .view.Component component = 1;
inline bool ViewResponse::has_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.component_ != nullptr);
  return value;
}
inline void ViewResponse::clear_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.component_ != nullptr) _impl_.component_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::view::Component& ViewResponse::_internal_component() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::view::Component* p = _impl_.component_;
  return p != nullptr ? *p : reinterpret_cast<const ::view::Component&>(::view::_Component_default_instance_);
}
inline const ::view::Component& ViewResponse::component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.ViewResponse.component)
  return _internal_component();
}
inline void ViewResponse::unsafe_arena_set_allocated_component(::view::Component* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.component_);
  }
  _impl_.component_ = reinterpret_cast<::view::Component*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:view.ViewResponse.component)
}
inline ::view::Component* ViewResponse::release_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::view::Component* released = _impl_.component_;
  _impl_.component_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::view::Component* ViewResponse::unsafe_arena_release_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:view.ViewResponse.component)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::view::Component* temp = _impl_.component_;
  _impl_.component_ = nullptr;
  return temp;
}
inline ::view::Component* ViewResponse::_internal_mutable_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.component_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::view::Component>(GetArena());
    _impl_.component_ = reinterpret_cast<::view::Component*>(p);
  }
  return _impl_.component_;
}
inline ::view::Component* ViewResponse::mutable_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::view::Component* _msg = _internal_mutable_component();
  // @@protoc_insertion_point(field_mutable:view.ViewResponse.component)
  return _msg;
}
inline void ViewResponse::set_allocated_component(::view::Component* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.component_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.component_ = reinterpret_cast<::view::Component*>(value);
  // @@protoc_insertion_point(field_set_allocated:view.ViewResponse.component)
}

// -------------------------------------------------------------------

// ClickRequest

// int32 object_id = 1;
inline void ClickRequest::clear_object_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_ = 0;
}
inline ::int32_t ClickRequest::object_id() const {
  // @@protoc_insertion_point(field_get:view.ClickRequest.object_id)
  return _internal_object_id();
}
inline void ClickRequest::set_object_id(::int32_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:view.ClickRequest.object_id)
}
inline ::int32_t ClickRequest::_internal_object_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.object_id_;
}
inline void ClickRequest::_internal_set_object_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_id_ = value;
}

// -------------------------------------------------------------------

// ClickResponse

// string status = 1;
inline void ClickResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.ClearToEmpty();
}
inline const std::string& ClickResponse::status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:view.ClickResponse.status)
  return _internal_status();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ClickResponse::set_status(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:view.ClickResponse.status)
}
inline std::string* ClickResponse::mutable_status() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:view.ClickResponse.status)
  return _s;
}
inline const std::string& ClickResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_.Get();
}
inline void ClickResponse::_internal_set_status(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.Set(value, GetArena());
}
inline std::string* ClickResponse::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.status_.Mutable( GetArena());
}
inline std::string* ClickResponse::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:view.ClickResponse.status)
  return _impl_.status_.Release();
}
inline void ClickResponse::set_allocated_status(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:view.ClickResponse.status)
}

// -------------------------------------------------------------------

// Empty

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace view


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::view::TextDisplayType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::view::TextDisplayType>() {
  return ::view::TextDisplayType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // view_2eproto_2epb_2eh
