// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: view.proto
// Protobuf C++ Version: 5.29.0

#include "view.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace view {

inline constexpr TextEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::view::TextDisplayType >(0)},
        group_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TextEntry::TextEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TextEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TextEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TextEntryDefaultTypeInternal() {}
  union {
    TextEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TextEntryDefaultTypeInternal _TextEntry_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;

inline constexpr ClickResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClickResponse::ClickResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClickResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClickResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClickResponseDefaultTypeInternal() {}
  union {
    ClickResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClickResponseDefaultTypeInternal _ClickResponse_default_instance_;

inline constexpr ClickRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : object_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClickRequest::ClickRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClickRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClickRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClickRequestDefaultTypeInternal() {}
  union {
    ClickRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClickRequestDefaultTypeInternal _ClickRequest_default_instance_;

inline constexpr TextComponent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entries_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TextComponent::TextComponent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TextComponentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TextComponentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TextComponentDefaultTypeInternal() {}
  union {
    TextComponent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TextComponentDefaultTypeInternal _TextComponent_default_instance_;

inline constexpr Component::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        component_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Component::Component(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ComponentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ComponentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ComponentDefaultTypeInternal() {}
  union {
    Component _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ComponentDefaultTypeInternal _Component_default_instance_;

inline constexpr ListComponent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : components_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListComponent::ListComponent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListComponentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListComponentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListComponentDefaultTypeInternal() {}
  union {
    ListComponent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListComponentDefaultTypeInternal _ListComponent_default_instance_;

inline constexpr ViewResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        component_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ViewResponse::ViewResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ViewResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ViewResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ViewResponseDefaultTypeInternal() {}
  union {
    ViewResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ViewResponseDefaultTypeInternal _ViewResponse_default_instance_;
}  // namespace view
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_view_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_view_2eproto = nullptr;
const ::uint32_t
    TableStruct_view_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::TextEntry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::TextEntry, _impl_.text_),
        PROTOBUF_FIELD_OFFSET(::view::TextEntry, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::view::TextEntry, _impl_.group_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::TextComponent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::TextComponent, _impl_.entries_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::ListComponent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::ListComponent, _impl_.components_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::Component, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::view::Component, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::Component, _impl_.id_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::view::Component, _impl_.component_),
        PROTOBUF_FIELD_OFFSET(::view::ViewResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::view::ViewResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::ViewResponse, _impl_.component_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::ClickRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::ClickRequest, _impl_.object_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::ClickResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::view::ClickResponse, _impl_.status_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::view::Empty, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::view::TextEntry)},
        {11, -1, -1, sizeof(::view::TextComponent)},
        {20, -1, -1, sizeof(::view::ListComponent)},
        {29, -1, -1, sizeof(::view::Component)},
        {41, 50, -1, sizeof(::view::ViewResponse)},
        {51, -1, -1, sizeof(::view::ClickRequest)},
        {60, -1, -1, sizeof(::view::ClickResponse)},
        {69, -1, -1, sizeof(::view::Empty)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::view::_TextEntry_default_instance_._instance,
    &::view::_TextComponent_default_instance_._instance,
    &::view::_ListComponent_default_instance_._instance,
    &::view::_Component_default_instance_._instance,
    &::view::_ViewResponse_default_instance_._instance,
    &::view::_ClickRequest_default_instance_._instance,
    &::view::_ClickResponse_default_instance_._instance,
    &::view::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_view_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nview.proto\022\004view\"P\n\tTextEntry\022\014\n\004text\030"
    "\001 \001(\t\022#\n\004type\030\002 \001(\0162\025.view.TextDisplayTy"
    "pe\022\020\n\010group_id\030\003 \001(\005\"1\n\rTextComponent\022 \n"
    "\007entries\030\001 \003(\0132\017.view.TextEntry\"4\n\rListC"
    "omponent\022#\n\ncomponents\030\001 \003(\0132\017.view.Comp"
    "onent\"\202\001\n\tComponent\022\n\n\002id\030\003 \001(\005\022-\n\016text_"
    "component\030\001 \001(\0132\023.view.TextComponentH\000\022-"
    "\n\016list_component\030\002 \001(\0132\023.view.ListCompon"
    "entH\000B\013\n\tcomponent\"2\n\014ViewResponse\022\"\n\tco"
    "mponent\030\001 \001(\0132\017.view.Component\"!\n\014ClickR"
    "equest\022\021\n\tobject_id\030\001 \001(\005\"\037\n\rClickRespon"
    "se\022\016\n\006status\030\001 \001(\t\"\007\n\005Empty*&\n\017TextDispl"
    "ayType\022\t\n\005PLAIN\020\000\022\010\n\004CODE\020\0012k\n\013ViewServi"
    "ce\022*\n\007GetView\022\013.view.Empty\032\022.view.ViewRe"
    "sponse\0220\n\005Click\022\022.view.ClickRequest\032\023.vi"
    "ew.ClickResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_view_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_view_2eproto = {
    false,
    false,
    624,
    descriptor_table_protodef_view_2eproto,
    "view.proto",
    &descriptor_table_view_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_view_2eproto::offsets,
    file_level_enum_descriptors_view_2eproto,
    file_level_service_descriptors_view_2eproto,
};
namespace view {
const ::google::protobuf::EnumDescriptor* TextDisplayType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_view_2eproto);
  return file_level_enum_descriptors_view_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TextDisplayType_internal_data_[] = {
    131072u, 0u, };
bool TextDisplayType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class TextEntry::_Internal {
 public:
};

TextEntry::TextEntry(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.TextEntry)
}
inline PROTOBUF_NDEBUG_INLINE TextEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::TextEntry& from_msg)
      : text_(arena, from.text_),
        _cached_size_{0} {}

TextEntry::TextEntry(
    ::google::protobuf::Arena* arena,
    const TextEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TextEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, group_id_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::group_id_));

  // @@protoc_insertion_point(copy_constructor:view.TextEntry)
}
inline PROTOBUF_NDEBUG_INLINE TextEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : text_(arena),
        _cached_size_{0} {}

inline void TextEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, group_id_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::group_id_));
}
TextEntry::~TextEntry() {
  // @@protoc_insertion_point(destructor:view.TextEntry)
  SharedDtor(*this);
}
inline void TextEntry::SharedDtor(MessageLite& self) {
  TextEntry& this_ = static_cast<TextEntry&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TextEntry::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TextEntry(arena);
}
constexpr auto TextEntry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TextEntry),
                                            alignof(TextEntry));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TextEntry::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TextEntry_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TextEntry::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TextEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TextEntry::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TextEntry>(), &TextEntry::ByteSizeLong,
            &TextEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TextEntry, _impl_._cached_size_),
        false,
    },
    &TextEntry::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TextEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 27, 2> TextEntry::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::TextEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string text = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.text_)}},
    // .view.TextDisplayType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TextEntry, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.type_)}},
    // int32 group_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TextEntry, _impl_.group_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.group_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string text = 1;
    {PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .view.TextDisplayType type = 2;
    {PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 group_id = 3;
    {PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.group_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\16\4\0\0\0\0\0\0"
    "view.TextEntry"
    "text"
  }},
};

PROTOBUF_NOINLINE void TextEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:view.TextEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.group_id_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.group_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TextEntry::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TextEntry& this_ = static_cast<const TextEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TextEntry::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TextEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.TextEntry)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string text = 1;
          if (!this_._internal_text().empty()) {
            const std::string& _s = this_._internal_text();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "view.TextEntry.text");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .view.TextDisplayType type = 2;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_type(), target);
          }

          // int32 group_id = 3;
          if (this_._internal_group_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_group_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.TextEntry)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TextEntry::ByteSizeLong(const MessageLite& base) {
          const TextEntry& this_ = static_cast<const TextEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TextEntry::ByteSizeLong() const {
          const TextEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.TextEntry)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string text = 1;
            if (!this_._internal_text().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_text());
            }
            // .view.TextDisplayType type = 2;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // int32 group_id = 3;
            if (this_._internal_group_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_group_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TextEntry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TextEntry*>(&to_msg);
  auto& from = static_cast<const TextEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:view.TextEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_group_id() != 0) {
    _this->_impl_.group_id_ = from._impl_.group_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TextEntry::CopyFrom(const TextEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.TextEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TextEntry::InternalSwap(TextEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.group_id_)
      + sizeof(TextEntry::_impl_.group_id_)
      - PROTOBUF_FIELD_OFFSET(TextEntry, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata TextEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TextComponent::_Internal {
 public:
};

TextComponent::TextComponent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.TextComponent)
}
inline PROTOBUF_NDEBUG_INLINE TextComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::TextComponent& from_msg)
      : entries_{visibility, arena, from.entries_},
        _cached_size_{0} {}

TextComponent::TextComponent(
    ::google::protobuf::Arena* arena,
    const TextComponent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TextComponent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:view.TextComponent)
}
inline PROTOBUF_NDEBUG_INLINE TextComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entries_{visibility, arena},
        _cached_size_{0} {}

inline void TextComponent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TextComponent::~TextComponent() {
  // @@protoc_insertion_point(destructor:view.TextComponent)
  SharedDtor(*this);
}
inline void TextComponent::SharedDtor(MessageLite& self) {
  TextComponent& this_ = static_cast<TextComponent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TextComponent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TextComponent(arena);
}
constexpr auto TextComponent::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TextComponent, _impl_.entries_) +
          decltype(TextComponent::_impl_.entries_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TextComponent), alignof(TextComponent), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TextComponent::PlacementNew_,
                                 sizeof(TextComponent),
                                 alignof(TextComponent));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TextComponent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TextComponent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TextComponent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TextComponent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TextComponent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TextComponent>(), &TextComponent::ByteSizeLong,
            &TextComponent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TextComponent, _impl_._cached_size_),
        false,
    },
    &TextComponent::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TextComponent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> TextComponent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::TextComponent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .view.TextEntry entries = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TextComponent, _impl_.entries_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .view.TextEntry entries = 1;
    {PROTOBUF_FIELD_OFFSET(TextComponent, _impl_.entries_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::view::TextEntry>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void TextComponent::Clear() {
// @@protoc_insertion_point(message_clear_start:view.TextComponent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entries_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TextComponent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TextComponent& this_ = static_cast<const TextComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TextComponent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TextComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.TextComponent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .view.TextEntry entries = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_entries_size());
               i < n; i++) {
            const auto& repfield = this_._internal_entries().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.TextComponent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TextComponent::ByteSizeLong(const MessageLite& base) {
          const TextComponent& this_ = static_cast<const TextComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TextComponent::ByteSizeLong() const {
          const TextComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.TextComponent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .view.TextEntry entries = 1;
            {
              total_size += 1UL * this_._internal_entries_size();
              for (const auto& msg : this_._internal_entries()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TextComponent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TextComponent*>(&to_msg);
  auto& from = static_cast<const TextComponent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:view.TextComponent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entries()->MergeFrom(
      from._internal_entries());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TextComponent::CopyFrom(const TextComponent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.TextComponent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TextComponent::InternalSwap(TextComponent* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entries_.InternalSwap(&other->_impl_.entries_);
}

::google::protobuf::Metadata TextComponent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListComponent::_Internal {
 public:
};

ListComponent::ListComponent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.ListComponent)
}
inline PROTOBUF_NDEBUG_INLINE ListComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::ListComponent& from_msg)
      : components_{visibility, arena, from.components_},
        _cached_size_{0} {}

ListComponent::ListComponent(
    ::google::protobuf::Arena* arena,
    const ListComponent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListComponent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:view.ListComponent)
}
inline PROTOBUF_NDEBUG_INLINE ListComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : components_{visibility, arena},
        _cached_size_{0} {}

inline void ListComponent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListComponent::~ListComponent() {
  // @@protoc_insertion_point(destructor:view.ListComponent)
  SharedDtor(*this);
}
inline void ListComponent::SharedDtor(MessageLite& self) {
  ListComponent& this_ = static_cast<ListComponent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ListComponent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListComponent(arena);
}
constexpr auto ListComponent::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListComponent, _impl_.components_) +
          decltype(ListComponent::_impl_.components_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ListComponent), alignof(ListComponent), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListComponent::PlacementNew_,
                                 sizeof(ListComponent),
                                 alignof(ListComponent));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListComponent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListComponent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListComponent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ListComponent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListComponent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ListComponent>(), &ListComponent::ByteSizeLong,
            &ListComponent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListComponent, _impl_._cached_size_),
        false,
    },
    &ListComponent::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListComponent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ListComponent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::ListComponent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .view.Component components = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListComponent, _impl_.components_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .view.Component components = 1;
    {PROTOBUF_FIELD_OFFSET(ListComponent, _impl_.components_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::view::Component>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ListComponent::Clear() {
// @@protoc_insertion_point(message_clear_start:view.ListComponent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.components_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ListComponent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ListComponent& this_ = static_cast<const ListComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ListComponent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ListComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.ListComponent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .view.Component components = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_components_size());
               i < n; i++) {
            const auto& repfield = this_._internal_components().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.ListComponent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ListComponent::ByteSizeLong(const MessageLite& base) {
          const ListComponent& this_ = static_cast<const ListComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ListComponent::ByteSizeLong() const {
          const ListComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.ListComponent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .view.Component components = 1;
            {
              total_size += 1UL * this_._internal_components_size();
              for (const auto& msg : this_._internal_components()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ListComponent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListComponent*>(&to_msg);
  auto& from = static_cast<const ListComponent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:view.ListComponent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_components()->MergeFrom(
      from._internal_components());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListComponent::CopyFrom(const ListComponent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.ListComponent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListComponent::InternalSwap(ListComponent* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.components_.InternalSwap(&other->_impl_.components_);
}

::google::protobuf::Metadata ListComponent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Component::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::view::Component, _impl_._oneof_case_);
};

void Component::set_allocated_text_component(::view::TextComponent* text_component) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_component();
  if (text_component) {
    ::google::protobuf::Arena* submessage_arena = text_component->GetArena();
    if (message_arena != submessage_arena) {
      text_component = ::google::protobuf::internal::GetOwnedMessage(message_arena, text_component, submessage_arena);
    }
    set_has_text_component();
    _impl_.component_.text_component_ = text_component;
  }
  // @@protoc_insertion_point(field_set_allocated:view.Component.text_component)
}
void Component::set_allocated_list_component(::view::ListComponent* list_component) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_component();
  if (list_component) {
    ::google::protobuf::Arena* submessage_arena = list_component->GetArena();
    if (message_arena != submessage_arena) {
      list_component = ::google::protobuf::internal::GetOwnedMessage(message_arena, list_component, submessage_arena);
    }
    set_has_list_component();
    _impl_.component_.list_component_ = list_component;
  }
  // @@protoc_insertion_point(field_set_allocated:view.Component.list_component)
}
Component::Component(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.Component)
}
inline PROTOBUF_NDEBUG_INLINE Component::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::Component& from_msg)
      : component_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Component::Component(
    ::google::protobuf::Arena* arena,
    const Component& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Component* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;
  switch (component_case()) {
    case COMPONENT_NOT_SET:
      break;
      case kTextComponent:
        _impl_.component_.text_component_ = ::google::protobuf::Message::CopyConstruct<::view::TextComponent>(arena, *from._impl_.component_.text_component_);
        break;
      case kListComponent:
        _impl_.component_.list_component_ = ::google::protobuf::Message::CopyConstruct<::view::ListComponent>(arena, *from._impl_.component_.list_component_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:view.Component)
}
inline PROTOBUF_NDEBUG_INLINE Component::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : component_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Component::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Component::~Component() {
  // @@protoc_insertion_point(destructor:view.Component)
  SharedDtor(*this);
}
inline void Component::SharedDtor(MessageLite& self) {
  Component& this_ = static_cast<Component&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_component()) {
    this_.clear_component();
  }
  this_._impl_.~Impl_();
}

void Component::clear_component() {
// @@protoc_insertion_point(one_of_clear_start:view.Component)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (component_case()) {
    case kTextComponent: {
      if (GetArena() == nullptr) {
        delete _impl_.component_.text_component_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.component_.text_component_);
      }
      break;
    }
    case kListComponent: {
      if (GetArena() == nullptr) {
        delete _impl_.component_.list_component_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.component_.list_component_);
      }
      break;
    }
    case COMPONENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = COMPONENT_NOT_SET;
}


inline void* Component::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Component(arena);
}
constexpr auto Component::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Component),
                                            alignof(Component));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Component::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Component_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Component::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Component>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Component::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Component>(), &Component::ByteSizeLong,
            &Component::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Component, _impl_._cached_size_),
        false,
    },
    &Component::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Component::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2> Component::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::Component>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Component, _impl_.id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Component, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .view.TextComponent text_component = 1;
    {PROTOBUF_FIELD_OFFSET(Component, _impl_.component_.text_component_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .view.ListComponent list_component = 2;
    {PROTOBUF_FIELD_OFFSET(Component, _impl_.component_.list_component_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 id = 3;
    {PROTOBUF_FIELD_OFFSET(Component, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::view::TextComponent>()},
    {::_pbi::TcParser::GetTable<::view::ListComponent>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Component::Clear() {
// @@protoc_insertion_point(message_clear_start:view.Component)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  clear_component();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Component::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Component& this_ = static_cast<const Component&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Component::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Component& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.Component)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.component_case()) {
            case kTextComponent: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.component_.text_component_, this_._impl_.component_.text_component_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kListComponent: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.component_.list_component_, this_._impl_.component_.list_component_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          // int32 id = 3;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.Component)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Component::ByteSizeLong(const MessageLite& base) {
          const Component& this_ = static_cast<const Component&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Component::ByteSizeLong() const {
          const Component& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.Component)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 id = 3;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          switch (this_.component_case()) {
            // .view.TextComponent text_component = 1;
            case kTextComponent: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.component_.text_component_);
              break;
            }
            // .view.ListComponent list_component = 2;
            case kListComponent: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.component_.list_component_);
              break;
            }
            case COMPONENT_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Component::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Component*>(&to_msg);
  auto& from = static_cast<const Component&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:view.Component)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_component();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kTextComponent: {
        if (oneof_needs_init) {
          _this->_impl_.component_.text_component_ =
              ::google::protobuf::Message::CopyConstruct<::view::TextComponent>(arena, *from._impl_.component_.text_component_);
        } else {
          _this->_impl_.component_.text_component_->MergeFrom(from._internal_text_component());
        }
        break;
      }
      case kListComponent: {
        if (oneof_needs_init) {
          _this->_impl_.component_.list_component_ =
              ::google::protobuf::Message::CopyConstruct<::view::ListComponent>(arena, *from._impl_.component_.list_component_);
        } else {
          _this->_impl_.component_.list_component_->MergeFrom(from._internal_list_component());
        }
        break;
      }
      case COMPONENT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Component::CopyFrom(const Component& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.Component)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Component::InternalSwap(Component* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
  swap(_impl_.component_, other->_impl_.component_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Component::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ViewResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ViewResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ViewResponse, _impl_._has_bits_);
};

ViewResponse::ViewResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.ViewResponse)
}
inline PROTOBUF_NDEBUG_INLINE ViewResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::ViewResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ViewResponse::ViewResponse(
    ::google::protobuf::Arena* arena,
    const ViewResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ViewResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.component_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::view::Component>(
                              arena, *from._impl_.component_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:view.ViewResponse)
}
inline PROTOBUF_NDEBUG_INLINE ViewResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ViewResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.component_ = {};
}
ViewResponse::~ViewResponse() {
  // @@protoc_insertion_point(destructor:view.ViewResponse)
  SharedDtor(*this);
}
inline void ViewResponse::SharedDtor(MessageLite& self) {
  ViewResponse& this_ = static_cast<ViewResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.component_;
  this_._impl_.~Impl_();
}

inline void* ViewResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ViewResponse(arena);
}
constexpr auto ViewResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ViewResponse),
                                            alignof(ViewResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ViewResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ViewResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ViewResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ViewResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ViewResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ViewResponse>(), &ViewResponse::ByteSizeLong,
            &ViewResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ViewResponse, _impl_._cached_size_),
        false,
    },
    &ViewResponse::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ViewResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ViewResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ViewResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::ViewResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .view.Component component = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ViewResponse, _impl_.component_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .view.Component component = 1;
    {PROTOBUF_FIELD_OFFSET(ViewResponse, _impl_.component_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::view::Component>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ViewResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:view.ViewResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.component_ != nullptr);
    _impl_.component_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ViewResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ViewResponse& this_ = static_cast<const ViewResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ViewResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ViewResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.ViewResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .view.Component component = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.component_, this_._impl_.component_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.ViewResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ViewResponse::ByteSizeLong(const MessageLite& base) {
          const ViewResponse& this_ = static_cast<const ViewResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ViewResponse::ByteSizeLong() const {
          const ViewResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.ViewResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .view.Component component = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.component_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ViewResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ViewResponse*>(&to_msg);
  auto& from = static_cast<const ViewResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:view.ViewResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.component_ != nullptr);
    if (_this->_impl_.component_ == nullptr) {
      _this->_impl_.component_ =
          ::google::protobuf::Message::CopyConstruct<::view::Component>(arena, *from._impl_.component_);
    } else {
      _this->_impl_.component_->MergeFrom(*from._impl_.component_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ViewResponse::CopyFrom(const ViewResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.ViewResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ViewResponse::InternalSwap(ViewResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.component_, other->_impl_.component_);
}

::google::protobuf::Metadata ViewResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClickRequest::_Internal {
 public:
};

ClickRequest::ClickRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.ClickRequest)
}
ClickRequest::ClickRequest(
    ::google::protobuf::Arena* arena, const ClickRequest& from)
    : ClickRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ClickRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ClickRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.object_id_ = {};
}
ClickRequest::~ClickRequest() {
  // @@protoc_insertion_point(destructor:view.ClickRequest)
  SharedDtor(*this);
}
inline void ClickRequest::SharedDtor(MessageLite& self) {
  ClickRequest& this_ = static_cast<ClickRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ClickRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClickRequest(arena);
}
constexpr auto ClickRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ClickRequest),
                                            alignof(ClickRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClickRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClickRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClickRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClickRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClickRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClickRequest>(), &ClickRequest::ByteSizeLong,
            &ClickRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClickRequest, _impl_._cached_size_),
        false,
    },
    &ClickRequest::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClickRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ClickRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::ClickRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 object_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ClickRequest, _impl_.object_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ClickRequest, _impl_.object_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 object_id = 1;
    {PROTOBUF_FIELD_OFFSET(ClickRequest, _impl_.object_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ClickRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:view.ClickRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.object_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClickRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClickRequest& this_ = static_cast<const ClickRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClickRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClickRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.ClickRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 object_id = 1;
          if (this_._internal_object_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_object_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.ClickRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClickRequest::ByteSizeLong(const MessageLite& base) {
          const ClickRequest& this_ = static_cast<const ClickRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClickRequest::ByteSizeLong() const {
          const ClickRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.ClickRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 object_id = 1;
            if (this_._internal_object_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_object_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClickRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClickRequest*>(&to_msg);
  auto& from = static_cast<const ClickRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:view.ClickRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_object_id() != 0) {
    _this->_impl_.object_id_ = from._impl_.object_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClickRequest::CopyFrom(const ClickRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.ClickRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClickRequest::InternalSwap(ClickRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.object_id_, other->_impl_.object_id_);
}

::google::protobuf::Metadata ClickRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClickResponse::_Internal {
 public:
};

ClickResponse::ClickResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:view.ClickResponse)
}
inline PROTOBUF_NDEBUG_INLINE ClickResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::view::ClickResponse& from_msg)
      : status_(arena, from.status_),
        _cached_size_{0} {}

ClickResponse::ClickResponse(
    ::google::protobuf::Arena* arena,
    const ClickResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClickResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:view.ClickResponse)
}
inline PROTOBUF_NDEBUG_INLINE ClickResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : status_(arena),
        _cached_size_{0} {}

inline void ClickResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClickResponse::~ClickResponse() {
  // @@protoc_insertion_point(destructor:view.ClickResponse)
  SharedDtor(*this);
}
inline void ClickResponse::SharedDtor(MessageLite& self) {
  ClickResponse& this_ = static_cast<ClickResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.status_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ClickResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClickResponse(arena);
}
constexpr auto ClickResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ClickResponse),
                                            alignof(ClickResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClickResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClickResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClickResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClickResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClickResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClickResponse>(), &ClickResponse::ByteSizeLong,
            &ClickResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClickResponse, _impl_._cached_size_),
        false,
    },
    &ClickResponse::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClickResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> ClickResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::ClickResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string status = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClickResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string status = 1;
    {PROTOBUF_FIELD_OFFSET(ClickResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\6\0\0\0\0\0\0"
    "view.ClickResponse"
    "status"
  }},
};

PROTOBUF_NOINLINE void ClickResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:view.ClickResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClickResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClickResponse& this_ = static_cast<const ClickResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClickResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClickResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:view.ClickResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string status = 1;
          if (!this_._internal_status().empty()) {
            const std::string& _s = this_._internal_status();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "view.ClickResponse.status");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:view.ClickResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClickResponse::ByteSizeLong(const MessageLite& base) {
          const ClickResponse& this_ = static_cast<const ClickResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClickResponse::ByteSizeLong() const {
          const ClickResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:view.ClickResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string status = 1;
            if (!this_._internal_status().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClickResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClickResponse*>(&to_msg);
  auto& from = static_cast<const ClickResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:view.ClickResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClickResponse::CopyFrom(const ClickResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:view.ClickResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClickResponse::InternalSwap(ClickResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
}

::google::protobuf::Metadata ClickResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:view.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:view.Empty)
}

inline void* Empty::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Empty(arena);
}
constexpr auto Empty::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Empty),
                                            alignof(Empty));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Empty::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Empty_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Empty::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Empty>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Empty::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Empty>(), &Empty::ByteSizeLong,
            &Empty::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Empty, _impl_._cached_size_),
        false,
    },
    &Empty::kDescriptorMethods,
    &descriptor_table_view_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Empty::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Empty::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::view::Empty>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace view
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_view_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
