// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: view.proto
#ifndef GRPC_view_2eproto__INCLUDED
#define GRPC_view_2eproto__INCLUDED

#include "view.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace view {

class ViewService final {
 public:
  static constexpr char const* service_full_name() {
    return "view.ViewService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetView(::grpc::ClientContext* context, const ::view::Empty& request, ::view::ViewResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>> AsyncGetView(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>>(AsyncGetViewRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>> PrepareAsyncGetView(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>>(PrepareAsyncGetViewRaw(context, request, cq));
    }
    virtual ::grpc::Status Click(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::view::ClickResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>> AsyncClick(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>>(AsyncClickRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>> PrepareAsyncClick(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>>(PrepareAsyncClickRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>* AsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::view::ViewResponse>* PrepareAsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>* AsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::view::ClickResponse>* PrepareAsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetView(::grpc::ClientContext* context, const ::view::Empty& request, ::view::ViewResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>> AsyncGetView(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>>(AsyncGetViewRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>> PrepareAsyncGetView(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>>(PrepareAsyncGetViewRaw(context, request, cq));
    }
    ::grpc::Status Click(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::view::ClickResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>> AsyncClick(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>>(AsyncClickRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>> PrepareAsyncClick(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>>(PrepareAsyncClickRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, std::function<void(::grpc::Status)>) override;
      void GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, std::function<void(::grpc::Status)>) override;
      void Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>* AsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::view::ViewResponse>* PrepareAsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>* AsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::view::ClickResponse>* PrepareAsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetView_;
    const ::grpc::internal::RpcMethod rpcmethod_Click_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetView(::grpc::ServerContext* context, const ::view::Empty* request, ::view::ViewResponse* response);
    virtual ::grpc::Status Click(::grpc::ServerContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetView() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetView(::grpc::ServerContext* context, ::view::Empty* request, ::grpc::ServerAsyncResponseWriter< ::view::ViewResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Click() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClick(::grpc::ServerContext* context, ::view::ClickRequest* request, ::grpc::ServerAsyncResponseWriter< ::view::ClickResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetView<WithAsyncMethod_Click<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetView() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::view::Empty, ::view::ViewResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::view::Empty* request, ::view::ViewResponse* response) { return this->GetView(context, request, response); }));}
    void SetMessageAllocatorFor_GetView(
        ::grpc::MessageAllocator< ::view::Empty, ::view::ViewResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::view::Empty, ::view::ViewResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetView(
      ::grpc::CallbackServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Click() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::view::ClickRequest, ::view::ClickResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response) { return this->Click(context, request, response); }));}
    void SetMessageAllocatorFor_Click(
        ::grpc::MessageAllocator< ::view::ClickRequest, ::view::ClickResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::view::ClickRequest, ::view::ClickResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Click(
      ::grpc::CallbackServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetView<WithCallbackMethod_Click<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetView() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Click() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetView() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetView(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Click() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClick(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetView() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetView(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetView(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Click() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Click(context, request, response); }));
    }
    ~WithRawCallbackMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Click(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetView : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetView() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::view::Empty, ::view::ViewResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::view::Empty, ::view::ViewResponse>* streamer) {
                       return this->StreamedGetView(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetView() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetView(::grpc::ServerContext* /*context*/, const ::view::Empty* /*request*/, ::view::ViewResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetView(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::view::Empty,::view::ViewResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Click : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Click() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::view::ClickRequest, ::view::ClickResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::view::ClickRequest, ::view::ClickResponse>* streamer) {
                       return this->StreamedClick(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Click() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Click(::grpc::ServerContext* /*context*/, const ::view::ClickRequest* /*request*/, ::view::ClickResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClick(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::view::ClickRequest,::view::ClickResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetView<WithStreamedUnaryMethod_Click<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetView<WithStreamedUnaryMethod_Click<Service > > StreamedService;
};

}  // namespace view


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_view_2eproto__INCLUDED
