// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: view.proto

#include "view.pb.h"
#include "view.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace view {

static const char* ViewService_method_names[] = {
  "/view.ViewService/GetView",
  "/view.ViewService/Click",
};

std::unique_ptr< ViewService::Stub> ViewService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ViewService::Stub> stub(new ViewService::Stub(channel, options));
  return stub;
}

ViewService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetView_(ViewService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Click_(ViewService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ViewService::Stub::GetView(::grpc::ClientContext* context, const ::view::Empty& request, ::view::ViewResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::view::Empty, ::view::ViewResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetView_, context, request, response);
}

void ViewService::Stub::async::GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::view::Empty, ::view::ViewResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetView_, context, request, response, std::move(f));
}

void ViewService::Stub::async::GetView(::grpc::ClientContext* context, const ::view::Empty* request, ::view::ViewResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetView_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::view::ViewResponse>* ViewService::Stub::PrepareAsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::view::ViewResponse, ::view::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetView_, context, request);
}

::grpc::ClientAsyncResponseReader< ::view::ViewResponse>* ViewService::Stub::AsyncGetViewRaw(::grpc::ClientContext* context, const ::view::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetViewRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ViewService::Stub::Click(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::view::ClickResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::view::ClickRequest, ::view::ClickResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Click_, context, request, response);
}

void ViewService::Stub::async::Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::view::ClickRequest, ::view::ClickResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Click_, context, request, response, std::move(f));
}

void ViewService::Stub::async::Click(::grpc::ClientContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Click_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::view::ClickResponse>* ViewService::Stub::PrepareAsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::view::ClickResponse, ::view::ClickRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Click_, context, request);
}

::grpc::ClientAsyncResponseReader< ::view::ClickResponse>* ViewService::Stub::AsyncClickRaw(::grpc::ClientContext* context, const ::view::ClickRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClickRaw(context, request, cq);
  result->StartCall();
  return result;
}

ViewService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ViewService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ViewService::Service, ::view::Empty, ::view::ViewResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ViewService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::view::Empty* req,
             ::view::ViewResponse* resp) {
               return service->GetView(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ViewService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ViewService::Service, ::view::ClickRequest, ::view::ClickResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ViewService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::view::ClickRequest* req,
             ::view::ClickResponse* resp) {
               return service->Click(ctx, req, resp);
             }, this)));
}

ViewService::Service::~Service() {
}

::grpc::Status ViewService::Service::GetView(::grpc::ServerContext* context, const ::view::Empty* request, ::view::ViewResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ViewService::Service::Click(::grpc::ServerContext* context, const ::view::ClickRequest* request, ::view::ClickResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace view

