# Tests for basic operations in REPL

ans:  => 4\n

Tests:
  plain_output:
    Run: "@{duckc_path} repl --plain-output --custom-std-artifacts-path @{case_std_artifacts}"
    Cases:
      expression-result:
        Input:
          File: "simple_numeric/simple_numeric1.rtf"
        Output:
          String: "4\n"
      unit-result:
        Input:
          File: "standard_library/std.rtf"
        Output:
          String: "42\n"
      exit-command:
        Input:
          String: "/exit\n"
        Output:
          String: ""
      reset-replay:
        TimeOut: 40
        Run: "cd \"$DIT_TMP_DIR\" && @{duckc_path} repl --plain-output --custom-std-artifacts-path @{case_std_artifacts}"
        Input:
          String: "2 + 2\n3 + 3\n/reset 1\n"
        Output:
          String: "4\n6\n4\n"

  simple_numeric:
    Cases:
      with_semicolon:
        Input: 
          File: "simple_numeric/simple_numeric1.rtf"
        Output:
          String: "@{beginning}\n=> 4\n@{end}"
      without_semicolon:
        Input:
          File: "simple_numeric/simple_numeric2.rtf"
        Output:
          String: "@{beginning}\n=> 17878\n@{end}"
      resilience:
        Run: "@{duckc_path} repl --plain-output --custom-std-artifacts-path @{case_std_artifacts}"
        Input:
          File: "simple_numeric/resilience.rtf"
        Output:
          String: "4\n42\n"
  multiple_numeric:
    Cases:
      manymen:
        Input:
          File: "multiple_numeric/multiple_numeric.rtf"
        Output:
          String: "@{beginning}\n@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{ans}@{end}"
  standard_library:
    Cases:
      function_works:
        Input:
          File: "standard_library/std.rtf"
        Output:
          String: "@{beginning}\n42\nFunction executed.\n@{end}"
