# Writes `version/commit_info.hpp` with the date of the commit the build is running against and
# whether the worktree was modified. Run at BUILD time (`cmake -P`) by the VersionCommitInfo
# target, never at configure time.
#
# Expects:
#   OUTPUT_FILE  - the header to write
#   GIT_WORK_DIR - a directory inside the worktree to ask git about

set(commit_date "")
set(is_dirty "false")

find_package(Git QUIET)

if(GIT_FOUND)
	execute_process(
		COMMAND ${GIT_EXECUTABLE} log -1 --format=%cd --date=short
		WORKING_DIRECTORY ${GIT_WORK_DIR}
		RESULT_VARIABLE git_log_result
		OUTPUT_VARIABLE git_log_output
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)

	# The exit code is the only reliable "there is no git here" signal: the git root is the
	# repository root while CMake's source tree starts one level below it, in `dev/`, so looking
	# for a `.git` entry next to the sources would always answer "no".
	if(git_log_result EQUAL 0)
		set(commit_date "${git_log_output}")

		# `-uno` ignores untracked files: a normal worktree has build directories and other
		# untracked leftovers in it, and those do not make the build differ from the commit.
		execute_process(
			COMMAND ${GIT_EXECUTABLE} status --porcelain -uno
			WORKING_DIRECTORY ${GIT_WORK_DIR}
			RESULT_VARIABLE git_status_result
			OUTPUT_VARIABLE git_status_output
			ERROR_QUIET
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)

		if(git_status_result EQUAL 0 AND NOT git_status_output STREQUAL "")
			set(is_dirty "true")
		endif()
	endif()
endif()

set(header_content
"// Generated by dev/src/common/version/GenerateCommitInfo.cmake - do not edit.
#pragma once

#define DUCKLING_COMMIT_DATE \"${commit_date}\"
#define DUCKLING_IS_DIRTY ${is_dirty}
")

# Write next to the real header first and only move it over when the content actually changed,
# so an unchanged build does not force version.cpp to recompile.
set(staging_file "${OUTPUT_FILE}.in")
file(WRITE "${staging_file}" "${header_content}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${staging_file}" "${OUTPUT_FILE}")
file(REMOVE "${staging_file}")
