# Writes `version/commit_info.hpp` with the hash and date of the commit the build is running
# against. Run at BUILD time (`cmake -P`) by the VersionCommitInfo target, never at configure time.
#
# Expects:
#   OUTPUT_FILE  - the header to write
#   GIT_WORK_DIR - a directory inside the worktree to ask git about

set(commit_hash "")
set(commit_date "")

find_package(Git QUIET)

if(GIT_FOUND)
	execute_process(
		COMMAND ${GIT_EXECUTABLE} rev-parse --short=9 HEAD
		WORKING_DIRECTORY ${GIT_WORK_DIR}
		RESULT_VARIABLE git_hash_result
		OUTPUT_VARIABLE git_hash_output
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)

	if(git_hash_result EQUAL 0)
		set(commit_hash "${git_hash_output}")
	endif()

	execute_process(
		COMMAND ${GIT_EXECUTABLE} log -1 --format=%cd --date=short
		WORKING_DIRECTORY ${GIT_WORK_DIR}
		RESULT_VARIABLE git_log_result
		OUTPUT_VARIABLE git_log_output
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)

	if(git_log_result EQUAL 0)
		set(commit_date "${git_log_output}")
	endif()
endif()

set(header_content
"// Generated by dev/src/common/version/GenerateCommitInfo.cmake - do not edit.
#pragma once

#define DUCKLING_COMMIT_HASH \"${commit_hash}\"
#define DUCKLING_COMMIT_DATE \"${commit_date}\"
")

# Write next to the real header first and only move it over when the content actually changed,
# so an unchanged build does not force version.cpp to recompile.
set(staging_file "${OUTPUT_FILE}.in")
file(WRITE "${staging_file}" "${header_content}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${staging_file}" "${OUTPUT_FILE}")
file(REMOVE "${staging_file}")
