#include "dk_emitter.hpp"

#include "type_mapper.hpp"

#include <algorithm>
#include <sstream>
#include <unordered_map>
#include <variant>

namespace c_import {

	namespace {

		/** Skip reasons reach the output as `#` comments, so they must stay single-line. */
		std::string sanitize(std::string text) {
			std::ranges::replace(text, '\n', ' ');
			std::ranges::replace(text, '\r', ' ');
			return text;
		}

		bool belongsInExternBlock(const std::string& kind) {
			return kind == "function" || kind == "record" || kind == "union";
		}

		void emitSkipped(std::ostringstream& out, const CSkipped& skipped, bool indented) {
			if (indented) out << '\t';
			out << "# skipped " << skipped.kind << " `" << skipped.name
				<< "`: " << sanitize(skipped.reason) << '\n';
		}

		void emitRecord(std::ostringstream& out, const CRecord& record) {
			out << "\tclass " << record.emitted_name << " {";
			for (const auto& field: record.fields)
				out << ' ' << field.name << ": " << renderType(field.type) << ';';
			out << " }\n";
		}

		void emitFunction(std::ostringstream& out, const CFunction& function) {
			out << "\tfundecl " << function.name << '(';
			for (std::size_t i = 0; i < function.params.size(); i++) {
				if (i != 0) out << ", ";
				out << function.params[i].name << ": " << renderType(function.params[i].type);
			}
			out << ')';
			// A C function returning void is written without a return type: an explicit
			// `-> void` on an `extern("C") fundecl` miscompiles and crashes when called (#3646).
			if (function.return_type != nullptr) out << " -> " << renderType(*function.return_type);
			out << ";\n";
		}

		void collectRecordNames(const CType& type, std::vector<std::string>& out) {
			std::visit(
				[&out](const auto& kind) {
					using T = std::decay_t<decltype(kind)>;
					if constexpr (std::is_same_v<T, RecordType>) {
						out.push_back(kind.emitted_name);
					} else if constexpr (std::is_same_v<T, PointerType>) {
						if (kind.pointee != nullptr) collectRecordNames(*kind.pointee, out);
					} else if constexpr (std::is_same_v<T, ArrayType>) {
						if (kind.element != nullptr) collectRecordNames(*kind.element, out);
					}
				},
				type.kind
			);
		}

		std::vector<std::string> referencedRecords(const CDecl& decl) {
			std::vector<std::string> names;
			std::visit(
				[&names](const auto& value) {
					using T = std::decay_t<decltype(value)>;
					if constexpr (std::is_same_v<T, CRecord>) {
						for (const auto& field: value.fields) collectRecordNames(field.type, names);
					} else if constexpr (std::is_same_v<T, CFunction>) {
						for (const auto& param: value.params) collectRecordNames(param.type, names);
						if (value.return_type != nullptr)
							collectRecordNames(*value.return_type, names);
					} else if constexpr (std::is_same_v<T, CAlias>) {
						names.push_back(value.target);
					}
				},
				decl
			);
			return names;
		}

		std::string originOfDecl(const CDecl& decl) {
			return std::visit([](const auto& value) { return value.origin; }, decl);
		}

		void emitBanner(std::ostringstream& out, const EmitterInput& input) {
			out << "#{\n";
			out << "    Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n";
			out << "\n";
			for (const auto& header: input.headers) out << "    Header: " << header << '\n';
			if (!input.clang_args.empty()) {
				out << "    clang args:";
				for (const auto& arg: input.clang_args) out << ' ' << arg;
				out << '\n';
			}
			out << "\n";
			out << "    C `const` is dropped. C `char` maps to i8/u8 so sub-word arguments keep\n";
			out << "    the right extension, while `char *` stays `cptr char`.\n";
			out << "#}\n\n";
		}

	}

	namespace {

		/** Writes the `extern("C")` block and the declarations that follow it. */
		void emitDecls(std::ostringstream& out, const std::vector<CDecl>& decls) {
			out << "extern(\"C\") {\n";
			for (const auto& decl: decls) {
				std::visit(
					[&out](const auto& value) {
						using T = std::decay_t<decltype(value)>;
						if constexpr (std::is_same_v<T, CRecord>) {
							emitRecord(out, value);
						} else if constexpr (std::is_same_v<T, CFunction>) {
							emitFunction(out, value);
						} else if constexpr (std::is_same_v<T, CSkipped>) {
							if (belongsInExternBlock(value.kind)) emitSkipped(out, value, true);
						}
					},
					decl
				);
			}
			out << "}\n";

			std::ostringstream tail;
			for (const auto& decl: decls) {
				std::visit(
					[&tail](const auto& value) {
						using T = std::decay_t<decltype(value)>;
						if constexpr (std::is_same_v<T, CAlias>) {
							tail << "const " << value.name << " = " << value.target << ";\n";
						} else if constexpr (std::is_same_v<T, CConst>) {
							tail << "const " << value.name << ": " << value.type << " = "
								 << value.literal << ";\n";
						} else if constexpr (std::is_same_v<T, CSkipped>) {
							if (!belongsInExternBlock(value.kind)) emitSkipped(tail, value, false);
						}
					},
					decl
				);
			}

			if (!tail.view().empty()) out << '\n' << tail.view();
		}

	}

	std::string emitBindings(const EmitterInput& input) {
		std::ostringstream out;
		emitBanner(out, input);
		emitDecls(out, input.model.decls);
		return out.str();
	}

	std::vector<SplitModule> emitSplitBindings(
		const EmitterInput& input, const std::string& package_name
	) {
		// Grouped in first-appearance order so the output stays deterministic.
		std::vector<std::string>                            order;
		std::unordered_map<std::string, std::vector<CDecl>> grouped;
		std::unordered_map<std::string, std::string>        owner_of_record;

		for (const auto& decl: input.model.decls) {
			std::string origin = originOfDecl(decl);
			if (origin.empty()) origin = "bindings";

			if (!grouped.contains(origin)) order.push_back(origin);
			grouped[origin].push_back(decl);

			if (const auto* record = std::get_if<CRecord>(&decl))
				owner_of_record.emplace(record->emitted_name, origin);
		}

		const auto direct_dependencies = [&](const std::string& name) {
			std::vector<std::string> dependencies;
			for (const auto& decl: grouped.at(name))
				for (const auto& referenced: referencedRecords(decl)) {
					const auto owner = owner_of_record.find(referenced);
					if (owner == owner_of_record.end() || owner->second == name) continue;
					if (std::ranges::find(dependencies, owner->second) == dependencies.end())
						dependencies.push_back(owner->second);
				}
			return dependencies;
		};

		// Two headers whose records point at each other depend on each other, because a record
		// only has to be complete *somewhere* in the translation unit to be named. Duckling has
		// no cyclic imports, so every group of mutually dependent modules is merged into one.
		std::unordered_map<std::string, std::vector<std::string>> reachable;
		for (const auto& name: order) reachable[name] = direct_dependencies(name);

		bool grew = true;
		while (grew) {
			grew = false;
			for (const auto& name: order) {
				auto& from = reachable[name];
				for (std::size_t i = 0; i < from.size(); i++)
					for (const auto& next: reachable[from[i]])
						if (std::ranges::find(from, next) == from.end()) {
							from.push_back(next);
							grew = true;
						}
			}
		}

		// Component representative for each module: the first member in discovery order.
		std::unordered_map<std::string, std::string> representative;
		for (const auto& name: order) {
			std::string chosen = name;
			for (const auto& other: order) {
				if (other == name) break;
				const bool mutually_dependent
					= std::ranges::find(reachable[name], other) != reachable[name].end()
				   && std::ranges::find(reachable[other], name) != reachable[other].end();
				if (mutually_dependent) {
					chosen = representative[other];
					break;
				}
			}
			representative[name] = chosen;
		}

		std::vector<std::string>                                  merged_order;
		std::unordered_map<std::string, std::vector<CDecl>>       merged;
		std::unordered_map<std::string, std::vector<std::string>> absorbed;
		for (const auto& name: order) {
			const std::string& into = representative[name];
			if (!merged.contains(into)) merged_order.push_back(into);
			auto& target = merged[into];
			target.insert(target.end(), grouped[name].begin(), grouped[name].end());
			if (into != name) absorbed[into].push_back(name);
		}

		for (auto& [record, owner]: owner_of_record) owner = representative[owner];

		std::vector<SplitModule> modules;
		modules.reserve(merged_order.size());

		for (const auto& name: merged_order) {
			const auto& decls = merged.at(name);

			std::vector<std::string> dependencies;
			for (const auto& decl: decls)
				for (const auto& referenced: referencedRecords(decl)) {
					const auto owner = owner_of_record.find(referenced);
					if (owner == owner_of_record.end() || owner->second == name) continue;
					if (std::ranges::find(dependencies, owner->second) == dependencies.end())
						dependencies.push_back(owner->second);
				}
			std::ranges::sort(dependencies);

			std::ostringstream out;
			emitBanner(out, input);

			// Without this the missing module is a mystery: `import <pkg>.<header>;` fails with
			// a lookup error and nothing says where those declarations went.
			if (const auto merged_in = absorbed.find(name); merged_in != absorbed.end()) {
				out << "# Also holds the declarations of ";
				for (std::size_t i = 0; i < merged_in->second.size(); i++) {
					if (i != 0) out << ", ";
					out << merged_in->second[i];
				}
				out << ", merged because they depend on each other.\n\n";
			}

			if (!dependencies.empty()) {
				for (const auto& dependency: dependencies)
					out << "import " << package_name << '.' << dependency << ";\n";
				for (const auto& dependency: dependencies) out << "using " << dependency << ".*;\n";
				out << '\n';
			}
			emitDecls(out, decls);

			modules.push_back(SplitModule{ .name = name, .contents = out.str() });
		}

		return modules;
	}

	std::string emitAggregateModule(
		const std::string& package_name, const std::vector<SplitModule>& modules
	) {
		std::ostringstream out;
		out << "#{\n";
		out << "    Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n";
		out << "\n";
		out << "    One module per translated header. `using` binds locally rather than\n";
		out << "    re-exporting, so import the module you need directly, for example\n";
		if (!modules.empty())
			out << "    `import " << package_name << '.' << modules.front().name << ".*;`.\n";
		out << "#}\n\n";

		for (const auto& module: modules)
			out << "import " << package_name << '.' << module.name << ";\n";
		for (const auto& module: modules) out << "using " << module.name << ".*;\n";

		return out.str();
	}

	std::string emitRootModule(const std::string& package_name) {
		std::ostringstream out;
		out << "#{\n";
		out << "    Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n";
		out << "\n";
		out << "    A directory without a main module file is not a module, so this file has to\n";
		out << "    exist. The bindings live in the `" << package_name << "` submodule next to\n";
		out << "    it, so they are reached with `import " << package_name << '.' << package_name
			<< ";`.\n";
		out << "#}\n";
		return out.str();
	}

}
