#include "manifest_emitter.hpp"

#include <sstream>

namespace c_import {

	namespace {

		// `links` reaches the linker as one shell string, so a path containing a space would
		// be split into separate arguments.
		bool hasSpace(const std::string& text) { return text.find(' ') != std::string::npos; }

	}

	ManifestResult emitManifest(const ManifestInput& input) {
		if (input.package_name.empty()) return { .yaml = {}, .error = "package name is empty" };

		for (const auto& library: input.dvm_shared_libs)
			if (hasSpace(library))
				return { .yaml = {}, .error = "shared library path contains a space: " + library };

		std::ostringstream out;
		out << "# Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n";
		out << "metadata:\n";
		out << "  name: " << input.package_name << '\n';
		out << "  version: '" << input.version << "'\n";
		out << "  description: 'Duckling bindings for " << input.package_name
			<< ", generated by duck_c_import'\n";

		if (!input.links.empty()) out << "  links: '" << input.links << "'\n";

		if (!input.dvm_shared_libs.empty()) {
			out << "  dvm-shared-libs:\n";
			for (const auto& library: input.dvm_shared_libs) out << "    - '" << library << "'\n";
		}

		return { .yaml = out.str(), .error = {} };
	}

}
