#include "manifest_emitter.hpp"

#include <sstream>

namespace c_import {

	namespace {

		/** Quotes a scalar for YAML. A single quote is escaped by doubling it. */
		std::string quoted(const std::string& text) {
			std::string out = "'";
			for (const char character: text) {
				out.push_back(character);
				if (character == '\'') out.push_back('\'');
			}
			out.push_back('\'');
			return out;
		}

	}

	ManifestResult emitManifest(const ManifestInput& input) {
		if (input.package_name.empty()) return { .yaml = {}, .error = "package name is empty" };

		std::ostringstream out;
		out << "# Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n";
		out << "metadata:\n";
		out << "  name: " << input.package_name << '\n';
		out << "  version: " << quoted(input.version) << '\n';
		out << "  description: "
			<< quoted("Duckling bindings for " + input.package_name + ", generated by duck_c_import")
			<< '\n';

		// `links` is handed to the linker as one shell string, so it may legitimately hold
		// several arguments; the DVM entries become `ffi object "<path>"`, where a space is fine.
		if (!input.links.empty()) out << "  links: " << quoted(input.links) << '\n';

		if (!input.dvm_shared_libs.empty()) {
			out << "  dvm-shared-libs:\n";
			for (const auto& library: input.dvm_shared_libs)
				out << "    - " << quoted(library) << '\n';
		}

		return { .yaml = out.str(), .error = {} };
	}

}
