# Tests for user-defined and default copy constructors.
Tests:
  aggregates:
    Cases:
      all:
        backend: all
        Output:
          String: "1\n3\n4\n7\n"
        ExitCode: 0

  boxes_and_refs:
    Cases:
      all:
        backend: all
        Output:
          String: "1\n7\n2\n9\n2\n3\n9\n4\n5\n7\n5\n9\n5\n100\n6\n100\n"
        ExitCode: 0

  function_calls:
    Cases:
      all:
        backend: all
        Output:
          String: "0\n1\n1\n"
        ExitCode: 0

  list_copies:
    Cases:
      all:
        backend: all
        Output:
          String: "3\n6\n6\n40\n5\n"
        ExitCode: 0
