PostCase: "python3 check.py; s1=$?; rm -r foo; s2=$?; [ $s1 -eq 0 ] && [ $s2 -eq 0 ]"

Tests:
  init:
    Description: can initialise a new project
    Cases:
      init:
        test_cmd: init foo --name bar && cd foo && git rev-parse --show-toplevel 
        Output:
          Run: |+
            printf "info: successfully created a new project \`bar\` at \`$(pwd)/foo\`\n$(pwd)/foo\n"
