PostCase: python3 check.py

Tests:
  init:
    Description: can initialise a new project
    Cases:
      init:
        test_cmd: duck init foo --name bar
        Output:
          Run: |+
            echo "info: successfully created a new project \`bar\` at \`$(pwd)/foo\`"
