folder: "basic_tests"

Tests:
  simple_addition:
    Cases:
      direct:
        mode: direct
        Output: &out_simple_addition
          String: "42\n"
      vm:
        mode: vm
        Output: *out_simple_addition

  function_declaration:
    Cases:
      direct:
        mode: direct
        Output: &out_function_declaration
          String: "42\n"
      vm:
        mode: vm
        Output: *out_function_declaration

  simple_loop:
    Cases:
      direct:
        mode: direct
        Output: &out_simple_loop
          String: "6\n5\n4\n3\n2\n1\n"
      vm:
        mode: vm
        Output: *out_simple_loop
