# Tests for imports

Tests:
  named_simple_imports:
    Cases:
      all:
        backend: all
        Output:
          String: "1\n"
        ExitCode: 0

  unnamed_simple_imports:
    Cases:
      all:
        backend: all
        Output:
          String: "1\n"
        ExitCode: 0

