# Tests for imports
# @TODO: #2476 Enable DVM cases.

Tests:
  named_simple_imports:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "1\n"
        ExitCode: 0

  unnamed_simple_imports:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "1\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "1\n"
        ExitCode: 0
