# Compilation tests

clean_cmd: "rm -rf build"
compile_gcc_sample: "gcc -c -o build/c_lib.o c_lib.c"
Clean: "@{clean_cmd}"
PreTest: "@{clean_cmd} && mkdir build && @{compile_gcc_sample} && @{duckc_path} compile_package ffi -a build -n package_ffi --additional-link-options build/c_lib.o"
Run: "./build/package_llvm.exe"

Tests:
  base:
    Cases:
      default:
        Output:
          String: "Hello from C!\nHello from C!\n1\nHello from C!\n"
        ExitCode: 0

