Tests:
  test-basic-errors:
    Description: Checks a lot of basic errors
    Cases:
      autofix-fail:
        test_cmd: x
        ExitCode: 1
        Err:
          String: |
            error: No such command as \`x\`. Did you mean:
                   - \`b\`
                   - \`r\`?

      invalid-subcmd:
        test_cmd: not-a-subcmd
        ExitCode: 1
        Err:
          String: 'error: No such command: \`not-a-subcmd\`\n'

      invalid-config:
        before_cmd: export DUCK_HOME=.
        test_cmd: "not-a-command 2>&1 | head -n4 " # Get first for lines, but we lose exit code and stderr
        ExitCode: 0
        Output:
          String: |
            error: when trying to check the maximum typos fixing distance

              Caused by:
                the key \`security.typos.max_distance\` expects an integer, not a string
