Tests:
  debug_adapter_lifecycle:
    Run: "python3 dap_runner.py"
    TimeOut: 5 
    Cases:
      initialize_launch_disconnect:
        Input:
          String: "" 
        Output:
          File: "dap.out"