#pragma once

/**
 * @file builtins_registry.hpp
 * Builtin LLVM bitcode blobs for different targets.
 *
 * The definitions are generated by compiling ../buitlins/builtins_source.cpp to
 * LLVM bitcode by clang, and then converting the bitcode to a C array with xxd.
 * This process is defined in ../../../builtins.cmake.
 *
 * We may want to generate this file via CMake at some point.
 * This is because a single release build cannot handle all targets,
 * because some targets (such as for Apple) may require SDKs that are only
 * accessible on specific hosts (such as Apple itself), requiring releases for those hosts.
 */

#include <span>

// x86_64-linux-gnu builtins
extern unsigned char builtins_x86_64_linux_gnu_bc[];  // NOLINT
extern unsigned int  builtins_x86_64_linux_gnu_bc_len;

// ARM64 Apple Darwin builtins
extern unsigned char builtins_arm64_apple_darwin_bc[];  // NOLINT
extern unsigned int  builtins_arm64_apple_darwin_bc_len;

// x86_64 Apple Darwin builtins
extern unsigned char builtins_x86_64_apple_darwin_bc[];  // NOLINT
extern unsigned int  builtins_x86_64_apple_darwin_bc_len;

inline std::span<unsigned char> getBuiltinsX8664LinuxGnuBCSpan() {
	return {
		static_cast<unsigned char*>(builtins_x86_64_linux_gnu_bc),
		builtins_x86_64_linux_gnu_bc_len,
	};
}

inline std::span<unsigned char> getBuiltinsArm64AppleDarwinBCSpan() {
	return {
		static_cast<unsigned char*>(builtins_arm64_apple_darwin_bc),
		builtins_arm64_apple_darwin_bc_len,
	};
}

inline std::span<unsigned char> getBuiltinsX8664AppleDarwinBCSpan() {
	return {
		static_cast<unsigned char*>(builtins_x86_64_apple_darwin_bc),
		builtins_x86_64_apple_darwin_bc_len,
	};
}

// Get the appropriate builtins for the current platform
inline std::span<unsigned char> getNativeBuiltinsBCSpan() {
#if defined(__APPLE__)
	#if defined(__aarch64__)
	return getBuiltinsArm64AppleDarwinBCSpan();
	#else
	return getBuiltinsX8664AppleDarwinBCSpan();
	#endif
#else
	// Linux and other platforms
	return getBuiltinsX8664LinuxGnuBCSpan();
#endif
}
