#pragma once

/**
 * @file builtins_registry.hpp
 * Builtin LLVM bitcode blob for the native target.
 *
 * The definitions are generated by compiling ../buitlins/builtins_source.cpp to
 * LLVM bitcode by clang, and then converting the bitcode to a C array with xxd.
 * This process is defined in ../../../builtins.cmake.
 *
 * The bitcode is compiled for the target Clang defaults to, i.e. the host the
 * compiler is built on (overridable via the BUILTINS_TARGET CMake variable).
 * A single build therefore cannot handle all targets, because some targets
 * (such as for Apple) may require SDKs that are only accessible on specific
 * hosts (such as Apple itself), requiring releases for those hosts.
 *
 * We may want to generate this file via CMake at some point.
 */

#include <span>

extern unsigned char builtins_native_bc[];  // NOLINT
extern unsigned int  builtins_native_bc_len;

inline std::span<unsigned char> getBuiltinsNativeBCSpan() {
	return {
		static_cast<unsigned char*>(builtins_native_bc),
		builtins_native_bc_len,
	};
}
