#pragma once

/**
 * @file builtins_registry.hpp
 * Builtin LLVM bitcode blobs for different targets.
 * Currently, we support only the x86_64-linux-gnu target.
 *
 * The definitions are generated by compiling ../buitlins/builtins_source.cpp to
 * LLVM bitcode by clang, and then converting the bitcode to a C array with xxd.
 * This process is defined in ../../../builtins.cmake.
 *
 * We may want to generate this file via CMake at some point.
 * This is because a single release build cannot handle all targets,
 * because some targets (such as for Apple) may require SDKs that are only
 * accessible on specific hosts (such as Apple itself), requiring releases for those hosts.
 */

#include <span>

extern unsigned char builtins_x86_64_linux_gnu_bc[];  // NOLINT
extern unsigned int  builtins_x86_64_linux_gnu_bc_len;

inline std::span<unsigned char> getBuiltinsX8664LinuxGnuBCSpan() {
	return {
		static_cast<unsigned char*>(builtins_x86_64_linux_gnu_bc),
		builtins_x86_64_linux_gnu_bc_len,
	};
}
