/**
 * @file hout.hpp
 * @note This file is a placeholder for HOUT structures
 * that will be added in the future.
 */

#pragma once

#include "elements/expr.hpp"  // IWYU pragma: export @TODO: #404 relax it to forward declaration
#include "hout_fd.hpp"        // IWYU pragma: keep

#include <ctv/ctv.hpp>
#include <helios/hout/origin.hpp>
#include <helios/symbols/symbol_id.hpp>

#include <base/pointers/box.hpp>
#include <base/pointers/box_or_ref.hpp>

#include <string_id/string_id.hpp>

#include <memory>
#include <ostream>
#include <variant>
#include <vector>

namespace compiler::repl {
	// for friend:
	struct ImplementationOf_QueryReplExpressionWrapper;
	struct ImplementationOf_QueryReplInstructionWrapper;
	struct ScriptMainWrapperBuilder;
}

namespace compiler::helios {

	// for friend:
	struct ImplementationOf_QueryDeclOfFun;

	namespace defgen {
		struct ImplementationOf_QueryImplicitClassConstructor;
		struct ImplementationOf_QueryDefaultClassConstructor;
		struct ImplementationOf_QueryDefaultStaticArrayConstructor;
		struct ImplementationOf_QueryTuplePackConstructor;
	}

	namespace code {
		// Forward declaration:
		struct CodeBlock;
		struct Parameter;
	}

	/**
	 * @brief Storage of information coming from function declaration without processing its body.
	 */
	struct HOUTFunctionDeclaration final {
		// @TODO: decide if HOUT functions declarations should contain its HELIOS SymID
		// - flags like "pure", "thread safe", "shared-thread-function", etc

		HOUTFunctionDeclaration() = delete;

		HOUTFunctionDeclaration(const HOUTFunctionDeclaration&) = delete;
		HOUTFunctionDeclaration(HOUTFunctionDeclaration&&)      = default;

		/**
		 * @note it is used for hashes
		 * @note For now, it works,
		 * but in the future with generics, and templates it might not
		 * We might want to add actual hash?
		 */
		SymID original_symbol;

		base::StrID original_name;

		tsh::SymbolType<> return_type;

		std::vector<code::Parameter> parameters;

		code::ElementOrigin origin;

		[[nodiscard]]
		u64 queryUnstablePerfectHash() const;

		void debugPrint(std::ostream& out) const;

	private:
		HOUTFunctionDeclaration(
			SymID                        symbol,
			tsh::SymbolType<>            ret_type,
			std::vector<code::Parameter> parameters,
			code::ElementOrigin          origin
		);
		friend ImplementationOf_QueryDeclOfFun;
		friend compiler::repl::ImplementationOf_QueryReplExpressionWrapper;
		friend compiler::repl::ImplementationOf_QueryReplInstructionWrapper;
	};

	/**
	 * @brief HOUT representation for function, etc. It is declaration extended by function content.
	 * @note it should be used for all function-like entities (macros, methods, etc.)
	 */
	struct HOUTFunction final {
	private:
		HOUTFunction(
			code::ElementOrigin origin,
			CRef<HOUTFunctionDeclaration>,
			const std::shared_ptr<const code::CodeBlock>& body
		);
		friend struct ImplementationOf_QueryCodeOfFun;
		friend defgen::ImplementationOf_QueryImplicitClassConstructor;
		friend defgen::ImplementationOf_QueryTuplePackConstructor;
		friend defgen::ImplementationOf_QueryDefaultClassConstructor;
		friend defgen::ImplementationOf_QueryDefaultStaticArrayConstructor;
		friend compiler::repl::ImplementationOf_QueryReplExpressionWrapper;
		friend compiler::repl::ImplementationOf_QueryReplInstructionWrapper;
		friend compiler::repl::ScriptMainWrapperBuilder;

	public:
		HOUTFunction() = delete;

		/**
		 * @brief The information about how the function was created from code,
		 * if it was created from the PST function (with the reference to the PST node)
		 * or if it was generated by the compiler.
		 */
		code::ElementOrigin origin;

		CRef<HOUTFunctionDeclaration> declaration;

		/**
		 * @note use of shared_ptr's is intentional, as they
		 * work well for incomplete types, and fit the use case.
		 * In the future we might optimize it to single (or zero) shared_ptr, but
		 * that will require some boilerplate.
		 */
		std::shared_ptr<const code::CodeBlock> body;

		[[nodiscard]]
		u64 queryUnstablePerfectHash() const;

		void debugPrint(std::ostream& out) const;
	};

	enum class HOUTGlobalDataType { Constant, Variable };

	struct HOUTGlobalConst final {
		ctv::CompileTimeValue value;
	};

	class HOUTGlobalVariable final {
	public:
		BoxOrCRef<code::Expr> initial_value;  ///< The initial value of the variable.

		HOUTGlobalVariable(BoxOrCRef<code::Expr> initial_value):
			  initial_value(std::move(initial_value)) {}
	};

	/**
	 * @brief Represents global data in the HOUT module.
	 *
	 * This structure is used to store information about global constants and variables
	 * in the HOUT representation of a module. It supports two types of global data:
	 * constants and variables, distinguished by the `data_type` field.
	 *
	 * - Constants are represented using `HOUTGlobalConst`.
	 * - Variables are represented using `HOUTGlobalVariable`.
	 *
	 * The `value` field is a variant that holds either a constant or a variable,
	 * depending on the `data_type`. This structure also includes metadata such as
	 * the original name, symbol ID, and type of the global data.
	 */
	struct HOUTGlobalData final {
		// @TODO: decide if HOUT functions global data contain its HELIOS SymID
		// Currently it is here for pretty printing
		SymID helios_symbol;

		code::ElementOrigin origin;

		base::StrID original_name;

		HOUTGlobalDataType data_type;

		std::variant<HOUTGlobalConst, HOUTGlobalVariable> value;

		tsh::SymbolType<> type;

		void debugPrint(query::Context& ctx, std::ostream& out) const;
	};

	/**
	 * @brief Structure representing single HOUTUnit.
	 *
	 * HOUT unit is an arbitrary code collections represented in HOUT IR.
	 *
	 * There are typically created for a given module, but there is no
	 * constract on what any given HOUTUnit should contain.
	 */
	struct HOUTUnit final {
		// all first class citizens of module should be here:
		// * types (in some way?)
		// * required baked template list?
		// * functions / methods / macros
		// * defined templates
		// * vector/references to hout of submodules? -- not necessarily needed
		// * what else?

		std::vector<CRef<HOUTGlobalData>> glob_data;

		std::vector<CRef<HOUTFunction>> functions;

		void debugPrint(query::Context& ctx, std::ostream& out) const;

		HOUTUnit()                          = default;
		HOUTUnit(const HOUTUnit&)           = delete;
		HOUTUnit operator=(const HOUTUnit&) = delete;
		HOUTUnit(HOUTUnit&&)                = default;
		HOUTUnit& operator=(HOUTUnit&&)     = default;
	};
}
