#pragma once

#include <diagnostic_interactive/stable_position.hpp>
#include <frontend/pst_parser/access.hpp>

#include <base/collections/optional.hpp>

namespace compiler::helios::code {

	class ElementOrigin final {
		/**
		 * @brief The source position of the origin, if it is available.
		 *
		 * If the origin was generated, it may (or may not) have the source position,
		 * which is the position of the code that it was generated from.
		 *
		 * If element was created from multiple PST elements,
		 * the position is the merged position of all of them.
		 */
		base::Optional<dia_int::StablePosition> source_position;

		/**
		 * @brief The hash of the PST element that this
		 * origin corresponds to, if it corresponds to a specific PST element.
		 * If the origin corresponds to multiple PST elements, this will be empty.
		 * If the origin is generated, this will also be empty.
		 */
		base::Optional<dia_int::StablePosition::HashType> pst_element;

		/**
		 * @brief Whether the element is generated by HOUT or not.
		 */
		bool is_generated;

		ElementOrigin(
			base::Optional<dia_int::StablePosition>           source_position,
			base::Optional<dia_int::StablePosition::HashType> pst_element_hash,
			bool                                              is_generated
		):
			  source_position(source_position),
			  pst_element(pst_element_hash),
			  is_generated(is_generated) {}

	public:
		/**
		 * @brief Get the source position of the origin, if it is available.
		 * Note that the generated elements can have the source position,
		 * if we know where they are generated from.
		 * The position is empty if they do not have position in the code.
		 */
		[[nodiscard]] base::Optional<dia::SourcePosition> getSourcePosition(query::Context& ctx
		) const;

		/**
		 * @brief Get the stable source position of the origin, if it is available.
		 * Same as @p getSourcePosition, but returns the stable position instead of the active
		 * position.
		 */
		[[nodiscard]] base::Optional<dia_int::StablePosition> getStablePosition() const;

		/**
		 * @brief Get the PST element that this origin corresponds to, if it corresponds to a
		 * specific PST element.
		 */
		[[nodiscard]] base::Optional<pst::AccessLocked<pst::LangElement>> getPSTElement() const;

		/**
		 * @brief Helper function that creates a new origin based on the current one but marked as
		 * generated. Used for example when the `deref expr` or `cast expr` is generated based on an
		 * existing expression.
		 */
		[[nodiscard]] ElementOrigin generatedFrom() const;

		[[nodiscard]] bool isGenerated() const { return is_generated; }

		friend ElementOrigin generatedOrigin();
		friend ElementOrigin pstOrigin(pst::Access<pst::LangElement> pst_element);
		friend ElementOrigin pstOriginOrdered(
			const ElementOrigin& origin, pst::Access<pst::LangElement> pst_element
		);
		friend ElementOrigin multiplePstOriginOrdered(
			const std::vector<pst::Access<pst::LangElement>>& pst_elements
		);
		friend ElementOrigin elementOriginOrdered(
			const ElementOrigin& left, const ElementOrigin& right
		);

		operator base::Optional<dia_int::StablePosition>() const { return getStablePosition(); }
	};

	/**
	 * @brief Creates an ElementOrigin for a HOUT-generated element.
	 */
	ElementOrigin generatedOrigin();

	/**
	 * @brief Creates a non-generated ElementOrigin from a single PST element.
	 */
	ElementOrigin pstOrigin(pst::Access<pst::LangElement> pst_element);

	/**
	 * @brief Creates a non-generated ElementOrigin from some existing origin and pst element.
	 * @warning The order of the elements should be the same in every compilation.
	 */
	ElementOrigin pstOriginOrdered(
		const ElementOrigin& origin, pst::Access<pst::LangElement> element_to_the_right
	);

	/**
	 * @brief Creates an ElementOrigin from two existing origins.
	 * @warning The order of the elements should be the same in every compilation.
	 */
	ElementOrigin elementOriginOrdered(const ElementOrigin& left, const ElementOrigin& right);

	/**
	 * @brief Creates a non-generated ElementOrigin from multiple PST elements.
	 * @warning The order of the elements should be the same in every compilation.
	 */
	ElementOrigin multiplePstOriginOrdered(
		const std::vector<pst::Access<pst::LangElement>>& ordered_pst_elements
	);
}
