# Playground
add_executable(char_testing char_testing.cpp)
add_executable(file_testing file_testing.cpp)
add_executable(lexer_testing lexer_testing.cpp)
add_executable(elements_testing elements_testing.cpp)
add_executable(pst_graph pst_graph.cpp)
add_executable(frontend_testing frontend_testing.cpp)
add_executable(helios_testing helios_testing.cpp)
add_executable(mir_testing mir_testing.cpp)
add_executable(lir_testing lir_testing.cpp)
add_executable(json_testing json_testing.cpp)
add_executable(llvm_testing llvm_testing.cpp)

target_link_libraries(file_testing Filesystem)
target_link_libraries(char_testing Lexer Diagnostic)
target_link_libraries(lexer_testing Lexer TokenFile)
target_link_libraries(elements_testing Lexer PstParser)
target_link_libraries(pst_graph Lexer PstParser gvc cgraph cdt)
target_link_libraries(json_testing Lexer PstParser)
target_link_libraries(frontend_testing Filesystem ModuleTree Clap)
target_link_libraries(helios_testing Base ModuleTree Clap HELIOS)
target_link_libraries(mir_testing Base ModuleTree Clap HELIOS QueryFramework MIR PstParser)
target_link_libraries(lir_testing Base ModuleTree Clap HELIOS QueryFramework MIR PstParser LIR)
target_link_libraries(llvm_testing Base ModuleTree Clap HELIOS QueryFramework MIR PstParser LIR LLVMBackend)
