Tests:
  # We test if using std works by default.
  default_std:
    module_to_compile: "uses_std"
    Cases:
      uses_std:
        backend: all
        Output:
          String: "10\n"

  # We test if not using std when disabling it in the compiler works.
  no_std:
    module_to_compile: "no_std"
    compile_dvm_options: "--no-std"
    compile_llvm_options: "--no-std"
    Cases:
      all:
        backend: all

  # In custom std instead of the default one we have a different implementation
  # of builtin_output that output 20 for the same `no_std` user code.
  custom_std:

    enable_conc_deterministic_tests: "false"
    module_to_compile: "uses_std"
    compile_dvm_options: "--custom-std-path custom_std"
    compile_llvm_options: "--custom-std-path custom_std"
    Cases:
      all:
        backend: llvm
        Output:
          String: "20\n"

  # We test if disabling the std and using it in the user code causes the expected compile error.
  no_std_fails:
    module_to_compile: "uses_std"
    PreCase: "@{clean_cmd} && mkdir build"
    Cases:
      dvm:
        Run: "@{duckc_path} compile_package duck_modules/@{module_to_compile} -a build -n package_@{module_to_compile} -w @{duckc_worker_count} --no-std --dvm-backend"
        ExitCode: 1
      llvm:
        Run: "@{duckc_path} compile_package duck_modules/@{module_to_compile} -a build -n package_@{module_to_compile} -w @{duckc_worker_count} --no-std"
        ExitCode: 1

  both_options_fail:
    module_to_compile: "no_std"
    PreCase: "@{clean_cmd} && mkdir build"
    Cases:
      dvm:
        Run: "@{duckc_path} compile_package duck_modules/@{module_to_compile} -a build -n package_@{module_to_compile} -w @{duckc_worker_count} --no-std --custom-std-path custom_std --dvm-backend"
        ExitCode: 1
      llvm:
        Run: "@{duckc_path} compile_package duck_modules/@{module_to_compile} -a build -n package_@{module_to_compile} -w @{duckc_worker_count} --no-std --custom-std-path custom_std"
        ExitCode: 1
  
  compile_packages_default_std:
    module_to_compile: "uses_std"
    compile_dvm_only_cmd: "@{duckc_path} compile_packages duck_modules/@{module_to_compile}/manifest.json -a build"
    compile_llvm_only_cmd: "@{duckc_path} compile_packages duck_modules/@{module_to_compile}/manifest.json -a build"
    Cases:
      all:
        backend: all
        Output:
          String: "10\n"
