#include <base/ints.hpp>
#include <chrono>

#include <code_data/instruction.hpp>
#include <code_data/code.hpp>
#include <code_data/frame.hpp>
#include <services_data/type_metadata/type.hpp>
#include <supervisor/vcpu.hpp>
#include "op_case.hpp"
#include "executor.hpp"

#include <iostream>

#include <base/exceptions.hpp>
#include <base/optional.hpp>
#include <utility>

// @TODO: Go through linting messages here with regards to optimisation
// NOLINTBEGIN: Linting might impact optimizations here

namespace vm {

	void Executor::handleExecutionStrategy() {
		std::unique_lock lock(external_api_mutex);
		if (execution_strategy == ExecutionStrategy::Paused) setStatus(api::Paused{});
		pause_cv.wait(lock, [this] { return execution_strategy != ExecutionStrategy::Paused; });
		setStatus(api::Running{});
		if (execution_strategy == ExecutionStrategy::Stoped) throw KillCoreException{};
		if (execution_strategy == ExecutionStrategy::StepByStep)
			execution_strategy = ExecutionStrategy::Paused;
	}

	__attribute__((always_inline)) void inline Executor::handleExecutionStrategyIfNeeded() {
		if (isRunning) return;
		handleExecutionStrategy();
	}

	Frame Executor::internalInitFrame(
		base::Optional<Frame&> previous_frame, const FuncData& function, VLADataReference vla_ref
	) {
		return Frame{
			.previous = previous_frame,
			// .function = function,
			.bc                  = function.bc,
			.continue_execution  = true,
			.instruction_pointer = 0,

			.regs      = Registers{ .p64_reg_0 = 0, .pointer_reg_0 = memory.nullPtr() },
			.flags     = FlagData{ .flag = false },
			.ret_val   = 0,
			.next_args = { 0, memory.nullPtr() },

			.vla_data_reference = vla_ref,
		};
	}

	// arguments can be passed in temp values in caller
	// return values must somehow be passed to caller
	// Idea:
	// Stack works like this:
	// [locals][temp]
	// locals are stack-like independently
	// temp are stack-like independently
	// when function call happens, following stuff happen:
	// r := callee ret size
	// a := callee a size
	// R := temp reserve r-bytes
	// A := temp reserve a-bytes
	// set arguments
	// callee receives pointer temp [R|A]
	// callee does its stuff, and puts stuff into R (memcpy to local if needed)
	// callee returns
	// temp pop A
	// temp use R
	//
	// Or stack like this:
	// [rets][args][locals][temp] + memcpy between callee and caller

	cpp::result<base::ModRawView, std::string> Executor::internalDerefPointer(Pointer pointer) {
		auto block_id = pointer.getBlock();
		auto offset   = pointer.getOffset();

		auto block_result = memory.getBlock(block_id);
		if (block_result.has_error()) {
			// @TODO: executor error
			RIFT_PANIC(base::strConcat("Bad block access: ", block_result.error()));
		} else {
			auto block        = block_result.value();
			auto type         = block->innerType();
			auto deref_result = block->deref(type, offset);
			if (deref_result.has_error()) {
				// @TODO: executor error
				RIFT_PANIC("Bad deref access");
			} else {
				base::ModRawView view = deref_result.value();
				RIFT_ASSERT(view.size() == type->getSize(), "Bad deref size");
				return view;
			}
		}
	}

	template<typename T>
	__attribute__((always_inline)) inline static T& derefStack(std::byte stack[], i64 position) {
		return *(reinterpret_cast<T*>(&stack[position]));
	}

	__attribute__((always_inline)) void inline static peekNextInstruction(
		const std::span<const vm::Fix8Instruction>& bc,
		usize&                                      instruction_pointer,
		OpcodeFix8&                                 opcode
	) {
		Fix8Instruction instr = bc[instruction_pointer];

		opcode = static_cast<OpcodeFix8>(instr.opcode);
	}

#if defined(__clang__)
	// @TODO: suppress code deduplication in Clang
#elif defined(__GNUG__)
	#pragma GCC push_options
	#pragma GCC optimize("-fno-crossjumping")
#endif

	i64 Executor::internalCallFunction(
		base::Optional<Frame&> previous_frame, const FuncData& function, StandardFunctionArgs args
	) {
		// @TODO: sanity check should be added to see if function.stack_size is sensible small
		// @TODO: some generic code should be added to work with that does not support VLA
		std::byte local_stack[function.stack_size];
		u64       local_stack_head = 0;

		// @TODO: static code analysis could be done to determine the smallest
		// possible stack size for block_ids of variables
		BlockId block_id_stack[function.stack_size];
		u64     block_id_stack_head = 0;

		// @TODO: frame should hold pointers to data only, when
		// USE_FLAT_FRAME is on
		// This will be best made with code generation

#ifdef USE_FLAT_FRAME
		// Keeping these lines in, even if USE_FLAT_FRAME is off
		// for some very strange reason speeds up program by 10-20 %
		// It probably pokes compiler optimization in just the right way

		// @TODO: this should be autogenerated

		// Flat frame should technically allow for better compiler optimizations
		// but in practice are slower for some reason
		u64                  p64_reg_0           = 0;
		Pointer              pointer_reg_0       = memory.nullPtr();
		bool                 flag                = false;
		const auto           bc                  = function.bc;
		usize                instruction_pointer = 0;
		u64                  ret_val             = 0;
		StandardFunctionArgs next_args           = { 0, memory.nullPtr() };
#else
		Frame frame = internalInitFrame(previous_frame, function, { local_stack });
#endif

// Computed gotos labales:
#ifdef USE_COMPUTED_GOTO
		constexpr static void* opcode_label[] = { LABEL_PTR(mov_l64_imm),

			                                      LABEL_PTR(mov_l64_l64),
			                                      LABEL_PTR(cmov_l64_l64),

			                                      LABEL_PTR(mov_l64_r0),
			                                      LABEL_PTR(mov_r0_l64),

			                                      LABEL_PTR(mov_l64_pFuncArg),
			                                      LABEL_PTR(mov_lptr_ptrFuncArg),

			                                      LABEL_PTR(add_l64_l64),
			                                      LABEL_PTR(add_l64_imm),

			                                      LABEL_PTR(sub_l64_l64),
			                                      LABEL_PTR(sub_l64_imm),

			                                      // LABEL_PTR(mul_l64_l64),
			                                      LABEL_PTR(mul_l64_imm),

			                                      LABEL_PTR(mod_l64_l64),
			                                      LABEL_PTR(mod_l64_imm),

			                                      LABEL_PTR(div_l64_imm),

			                                      LABEL_PTR(cmpEq_l64_l64),
			                                      LABEL_PTR(cmpEq_l64_imm),
			                                      LABEL_PTR(cmpG_l64_l64),
			                                      LABEL_PTR(cmpG_l64_imm),

			                                      LABEL_PTR(jmpRel_label),
			                                      LABEL_PTR(jmpRelIf_label),
			                                      LABEL_PTR(jmpRelNotIf_label),

			                                      LABEL_PTR(setPArg_l64),
			                                      LABEL_PTR(setPtrArg_lptr),
			                                      LABEL_PTR(call_func),

			                                      LABEL_PTR(ret_l64),
			                                      LABEL_PTR(ret_imm),

			                                      LABEL_PTR(init_type),
			                                      LABEL_PTR(deinit),

			                                      LABEL_PTR(input_l64),
			                                      LABEL_PTR(output_l64),

			                                      LABEL_PTR(nop),

			                                      LABEL_PTR(alloc_lptr_type),
			                                      LABEL_PTR(free_lptr),
			                                      LABEL_PTR(load_l64_lptr_ofs),
			                                      LABEL_PTR(store_lptr_l64_ofs) };
#endif

		IF_NOT_CG(while (true)) {
			IF_CG(DISPATCH_OPCODE());

			if constexpr (!IGNORE_EXECUTION_STRATEGY) handleExecutionStrategyIfNeeded();

			IF_NOT_CG(switch (static_cast<OpcodeFix8>(FRAME(bc)[FRAME(instruction_pointer)].opcode))
			) {
				OP_CASE(mov_l64_imm, { derefStack<u64>(local_stack, instr.arg0) = instr.arg1; })

				OP_CASE(mov_l64_l64, {
					derefStack<u64>(local_stack, instr.arg0)
						= derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(cmov_l64_l64, {
					if (FRAME_FLAGS(flag))
						derefStack<u64>(local_stack, instr.arg0)
							= derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(mov_l64_r0, {
					derefStack<u64>(local_stack, instr.arg0) = FRAME_REGS(p64_reg_0);
				})

				OP_CASE(mov_r0_l64, {
					FRAME_REGS(p64_reg_0) = derefStack<u64>(local_stack, instr.arg0);
				})

				OP_CASE(mov_l64_pFuncArg, {
					derefStack<u64>(local_stack, instr.arg0) = args.p64_arg;
				})

				OP_CASE(mov_lptr_ptrFuncArg, {
					derefStack<Pointer>(local_stack, instr.arg0) = args.pointer_arg;
				})

				OP_CASE(add_l64_l64, {
					derefStack<u64>(local_stack, instr.arg0)
						+= derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(add_l64_imm, { derefStack<u64>(local_stack, instr.arg0) += instr.arg1; })

				OP_CASE(sub_l64_l64, {
					derefStack<u64>(local_stack, instr.arg0)
						-= derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(sub_l64_imm, { derefStack<u64>(local_stack, instr.arg0) -= instr.arg1; })

				OP_CASE(mul_l64_imm, {
					// @TODO: check types
					derefStack<u64>(local_stack, instr.arg0) *= instr.arg1;
				})

				OP_CASE(mod_l64_imm, { derefStack<u64>(local_stack, instr.arg0) %= instr.arg1; })

				OP_CASE(mod_l64_l64, {
					derefStack<u64>(local_stack, instr.arg0)
						%= derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(div_l64_imm, { derefStack<u64>(local_stack, instr.arg0) /= instr.arg1; })

				OP_CASE(cmpEq_l64_l64, {
					FRAME_FLAGS(flag) = derefStack<u64>(local_stack, instr.arg0)
					                 == derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(cmpEq_l64_imm, {
					FRAME_FLAGS(flag) = derefStack<u64>(local_stack, instr.arg0) == instr.arg1;
				})

				OP_CASE(cmpG_l64_l64, {
					FRAME_FLAGS(flag) = derefStack<u64>(local_stack, instr.arg0)
					                  > derefStack<u64>(local_stack, instr.arg1);
				})

				OP_CASE(cmpG_l64_imm, {
					FRAME_FLAGS(flag) = derefStack<u64>(local_stack, instr.arg0) > instr.arg1;
				})

				OP_CASE(jmpRel_label, { FRAME(instruction_pointer) += instr.arg0; })

				OP_CASE(jmpRelIf_label, {
					if (FRAME_FLAGS(flag)) FRAME(instruction_pointer) += instr.arg0;
				})

				OP_CASE(jmpRelNotIf_label, {
					if (!FRAME_FLAGS(flag)) FRAME(instruction_pointer) += instr.arg0;
				})

				OP_CASE(setPtrArg_lptr, {
					FRAME(next_args.pointer_arg) = derefStack<Pointer>(local_stack, instr.arg0);
				})

				OP_CASE(setPArg_l64, {
					FRAME(next_args.p64_arg) = derefStack<i64>(local_stack, instr.arg0);
				})

				OP_CASE(call_func, {
					auto function_id      = instr.arg0;
					FRAME_REGS(p64_reg_0) = internalCallFunction(
						// @TODO: this is not correct with flat frame
						IF_NOT_FF(frame) IF_FF({}),
						executing_code->functions[function_id],
						FRAME(next_args)
					);
				})

				OP_CASE(ret_l64, {
					FRAME(ret_val) = derefStack<u64>(local_stack, instr.arg0);
					goto End;
				});

				OP_CASE(ret_imm, {
					FRAME(ret_val) = 0;
					goto End;
				});

				OP_CASE(init_type, {
					auto             type      = types.getType(vm::TypeId(instr.arg0));
					auto             type_size = type->getSize();
					base::ModRawView data(&local_stack[local_stack_head], type_size);
					local_stack_head += type_size;
					auto block = stack_allocator.makeTypeBlock(type, data);
					block_id_stack[block_id_stack_head++] = block;
				})

				OP_CASE(deinit, {
					auto block = block_id_stack[--block_id_stack_head];
					stack_allocator.deleteBlock(block);
				})

				OP_CASE(input_l64, {
					setStatus(api::WaitingForInput{});
					derefStack<i64>(local_stack, instr.arg0) = vcpu.getInput<i64>();
					setStatus(api::Running{});
				});

				OP_CASE(output_l64, {
					vcpu.writeOutput(derefStack<u64>(local_stack, instr.arg0));
				});

				OP_CASE(nop, {});

				OP_CASE(alloc_lptr_type, {
					auto    type = types.getType(vm::TypeId(instr.arg1));
					BlockId block;
					if (type->getKind() == vm::Type::Kind::StaticTable) {
						// @TODO: As noted in type.hpp, interface used below may change
						auto inner_type = type->getInnerType().value();
						auto table_size = type->getStaticTableSize().value();

						// @TODO: It is possible to access memory of the array via
						// mov_l64_imm, which should be at least detected, if not illegal
						block = dynamic_allocator.makeArrayBlock(inner_type, table_size);
					} else {
						block = dynamic_allocator.makeTypeBlock(type);
					}
					derefStack<Pointer>(local_stack, instr.arg0) = Pointer(block, 0);
				})

				OP_CASE(free_lptr, {
					dynamic_allocator.deleteBlock(
						derefStack<Pointer>(local_stack, instr.arg0).getBlock()
					);
				})

				OP_CASE(load_l64_lptr_ofs, {
					auto pointer      = derefStack<Pointer>(local_stack, instr.arg1);
					auto deref_result = internalDerefPointer(pointer);
					if (deref_result.has_error()) {
						// @TODO: executor error
						// RIFT_PANIC("Bad deref access");
					} else {
						OpcodeFix8 opcode;
						peekNextInstruction(FRAME(bc), FRAME(instruction_pointer), opcode);
						u64 idx;
						if (opcode == OpcodeFix8::ext_l64) {
							auto arg3 = FRAME(bc)[FRAME(instruction_pointer)++].arg0;
							idx       = derefStack<u64>(local_stack, arg3);
						} else
							idx = 0;
						auto view = deref_result.value();
						RIFT_ASSERT(view.size() == 8, "bad type");
						std::memcpy(
							&local_stack[instr.arg0],
							view.getBegin() + idx * view.size(),
							view.size()
						);
					}
				})

				OP_CASE(store_lptr_l64_ofs, {
					auto pointer      = derefStack<Pointer>(local_stack, instr.arg0);
					auto deref_result = internalDerefPointer(pointer);
					if (deref_result.has_error()) {
						// @TODO: executor error
						// RIFT_PANIC("Bad deref access");
					} else {
						OpcodeFix8 opcode;
						peekNextInstruction(FRAME(bc), FRAME(instruction_pointer), opcode);
						u64 idx;
						if (opcode == OpcodeFix8::ext_l64) {
							auto arg3 = FRAME(bc)[FRAME(instruction_pointer)++].arg0;
							idx       = derefStack<u64>(local_stack, arg3);
						} else
							idx = 0;
						auto view = deref_result.value();
						RIFT_ASSERT(view.size() == 8, "bad type");
						std::memcpy(
							view.getBegin() + idx * view.size(),
							&local_stack[instr.arg1],
							view.size()
						);
					}
				})

				IF_NOT_CG(default
				          : {
							  // RIFT_PANIC("Unknown operator:", u64(instr.opcode));
						  })
			}
		}

	End:

		return FRAME(ret_val);
	}

#if defined(__clang__)
	// @TODO: suppress code deduplication in Clang
#elif defined(__GNUG__)
	#pragma GCC pop_options
#endif

	void Executor::run(const Code& code) {
		// @TODO: ensure correct status

		setStatus(api::Running{});

		executing_code = &code;
		try {
			internalCallFunction(
				base::Optional<Frame&>(),
				executing_code->functions[code.main_id],
				{ 0, memory.nullPtr() }
			);
			setStatus(api::NotStarted{});
		} catch (KillCoreException) { setStatus(api::NotStarted{}); }
	}

	void Executor::prestart() {
		std::unique_lock lock(external_api_mutex);
		if (execution_strategy == ExecutionStrategy::Stoped) {
			isRunning          = true;
			execution_strategy = ExecutionStrategy::Normal;
		}
	}

	void Executor::stop() {
		std::unique_lock lock(external_api_mutex);
		isRunning          = false;
		execution_strategy = ExecutionStrategy::Stoped;
		pause_cv.notify_all();
	}

	bool Executor::resume() {
		std::unique_lock lock(external_api_mutex);
		if (execution_strategy == ExecutionStrategy::Stoped
		    || execution_strategy == ExecutionStrategy::Normal) {
			return false;
		}
		isRunning          = true;
		execution_strategy = ExecutionStrategy::Normal;
		pause_cv.notify_all();
		return true;
	}

	bool Executor::pause() {
		std::unique_lock lock(external_api_mutex);
		if (execution_strategy == ExecutionStrategy::Stoped
		    || execution_strategy == ExecutionStrategy::Paused) {
			return false;
		} else if (execution_strategy == ExecutionStrategy::StepByStep) {
			return true;
		}
		isRunning          = false;
		execution_strategy = ExecutionStrategy::Paused;
		std::cout << "Set strategy to paused\n";
		return true;
	}

	bool Executor::step() {
		std::unique_lock lock(external_api_mutex);
		if (execution_strategy == ExecutionStrategy::Stoped)
			return false;
		else if (execution_strategy != ExecutionStrategy::Paused)
			return true;
		isRunning          = false;
		execution_strategy = ExecutionStrategy::StepByStep;
		pause_cv.notify_all();
		return true;
	}

	void Executor::setStatus(vm::api::ExecStatus new_status) {
		// @TODO: check if change is legal
		this->status = std::move(new_status);
		vcpu.onEvent(api::Executing(status));
	}

	bool Executor::isPaused() {
		std::unique_lock lock(external_api_mutex);
		return execution_strategy == ExecutionStrategy::Paused;
	}

	bool Executor::isAlive() {
		std::unique_lock lock(external_api_mutex);
		return execution_strategy != ExecutionStrategy::Stoped;
	}

	void Executor::notifyPaused() { pause_cv.notify_all(); }
}  // namespace vm

   // NOLINTEND
