Tests:
  recursive_comp_time_eval:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0
  comp_time_references:
    Cases:
      # @TODO: #1849 Add a DVM case when this is fixed.
      llvm:
        backend: llvm
        Output:
          String: "124\n"
        ExitCode: 0