Tests:
  recursive_comp_time_eval:
    Cases:
      dvm:
        backend: dvm
        Output:
          String: ""
        ExitCode: 0
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 0
  type_evaluation:
    Cases:
      #Issue: #2431 Enable DVM on this test
      llvm:
        backend: llvm
        Output:
          String: ""
        ExitCode: 42     
