
# We don't run the actual duckling programs in this test, 
# instead we test that the compiler produces the expected diagnostics when compiling invalid code.

Run: "
  case '@{backend}' in
    dvm) @{dvm_path} run @{compiled_to_dvm}       ;;
    llvm)
      if [ '@{valgrind}' = 'true' ]; then
        valgrind --leak-check=full --error-exitcode=1 @{compiled_to_llvm};
      else
        @{compiled_to_llvm};
      fi
      ;;
    nobackend) echo \"Backend undefined\"; exit 1 ;;
    *)         echo \"Unknown backend\";   exit 1 ;;
  esac;"

Tests:
  no_main_source_file:
    Cases:
      llvm:
        backend: llvm
        ExitCode: 3
