add_subdirectory(pst_parser)
add_subdirectory(frontend)
add_subdirectory(typesystem)
add_subdirectory(helios)
add_subdirectory(mir)
add_subdirectory(lir)
add_subdirectory(backends)

add_subdirectory(lsp_interface)

add_subdirectory(config)
add_subdirectory(main)

add_subdirectory(playground)

add_subdirectory(rift_snippets)

