post-check-action: ''
PostCase: python3 check.py @{post-check-action} && @{cleanup_tmp_env}

Tests:
  duck/init/venvconfig-flags:
    Description: can initialise a new project with different venvconfig flags
    Cases:
      expose-freezefile:
        test-cmd: duck init --expose-freezefile foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        post-check-action: expose-freezefile
      ephemeral:
        test-cmd: duck init --ephemeral foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        post-check-action: ephemeral
      local-storage:
        test-cmd: duck init --local-storage foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        post-check-action: local-storage
