#include <c_import/c_decls.hpp>
#include <c_import/dk_emitter.hpp>
#include <c_import/manifest_emitter.hpp>

#include <tester/tester.hpp>

#include <memory>
#include <string>

using namespace c_import;

namespace {

	CFunction makeFunction(std::string name, std::vector<CParam> params, CType return_type) {
		return CFunction{ .name        = std::move(name),
			              .params      = std::move(params),
			              .return_type = std::make_shared<const CType>(std::move(return_type)) };
	}

	EmitterInput sampleInput() {
		TranslationUnitModel model;
		model.decls.emplace_back(CRecord{
			.emitted_name = "struct_mylib_point",
			.fields       = { CField{ .name = "x", .type = makeScalar(Scalar::Int32) },
		                      CField{ .name = "y", .type = makeScalar(Scalar::Int32) } } });
		model.decls.emplace_back(makeFunction(
			"mylib_point_sum",
			{ CParam{ .name = "p", .type = makeRecord("struct_mylib_point") } },
			makeScalar(Scalar::Int32)
		));
		model.decls.emplace_back(CSkipped{
			.kind = "union", .name = "mylib_bad", .reason = "unions have no C ABI support" });
		model.decls.emplace_back(CAlias{ .name = "mylib_point_t", .target = "struct_mylib_point" });
		model.decls.emplace_back(CConst{ .name = "MYLIB_BLUE", .type = "u32", .literal = "7u32" });
		model.decls.emplace_back(CSkipped{
			.kind = "macro", .name = "MYLIB_ORIGIN", .reason = "not a numeric literal" });

		return EmitterInput{ .model      = std::move(model),
			                 .headers    = { "/abs/mylib.h" },
			                 .clang_args = { "-I/abs" } };
	}

}

class CImportEmitterTest final: public tester::TestSuite {
#undef TESTER_CLASS
#define TESTER_CLASS CImportEmitterTest

public:
	TESTER_TEST_SIMPLE_CONSTRUCTOR() {
		TESTER_ADD_TEST(bindingsTest);
		TESTER_ADD_TEST(determinismTest);
		TESTER_ADD_TEST(voidReturnTest);
		TESTER_ADD_TEST(manifestTest);
		TESTER_ADD_TEST(splitTest);
	}

private:
	void bindingsTest() {
		const std::string expected
			= "#{\n"
			  "    Generated by duck_c_import. DO NOT EDIT - regenerate instead.\n"
			  "\n"
			  "    Header: /abs/mylib.h\n"
			  "    clang args: -I/abs\n"
			  "\n"
			  "    C `const` is dropped. C `char` maps to i8/u8 so sub-word arguments keep\n"
			  "    the right extension, while `char *` stays `cptr char`.\n"
			  "#}\n"
			  "\n"
			  "extern(\"C\") {\n"
			  "\tclass struct_mylib_point { x: i32; y: i32; }\n"
			  "\tfundecl mylib_point_sum(p: struct_mylib_point) -> i32;\n"
			  "\t# skipped union `mylib_bad`: unions have no C ABI support\n"
			  "}\n"
			  "\n"
			  "const mylib_point_t = struct_mylib_point;\n"
			  "const MYLIB_BLUE: u32 = 7u32;\n"
			  "# skipped macro `MYLIB_ORIGIN`: not a numeric literal\n";

		ASSERT_EQUAL_PRINT(expected, emitBindings(sampleInput()));
	}

	void determinismTest() {
		ASSERT_EQUAL(emitBindings(sampleInput()), emitBindings(sampleInput()));
	}

	void voidReturnTest() {
		TranslationUnitModel model;
		model.decls.emplace_back(CFunction{
			.name        = "mylib_free",
			.params      = { CParam{ .name = "p", .type = makeOpaquePointer() } },
			.return_type = nullptr });

		const std::string emitted = emitBindings(EmitterInput{
			.model = std::move(model), .headers = {}, .clang_args = {} });
		ASSERT_TRUE(emitted.contains("\tfundecl mylib_free(p: cptr u8) -> void;\n"));
	}

	void splitTest() {
		TranslationUnitModel model;

		CRecord point{ .emitted_name = "struct_alpha_point",
			           .fields = { CField{ .name = "x", .type = makeScalar(Scalar::Int32) } } };
		point.origin = "alpha";
		model.decls.emplace_back(point);

		// `beta` names a record owned by `alpha`, so it has to pull it in.
		CRecord box{ .emitted_name = "struct_beta_box",
			         .fields
			         = { CField{ .name = "origin", .type = makeRecord("struct_alpha_point") } } };
		box.origin = "beta";
		model.decls.emplace_back(box);

		const auto modules = emitSplitBindings(
			EmitterInput{ .model = std::move(model), .headers = {}, .clang_args = {} }, "shapes"
		);

		ASSERT_EQUAL(std::size_t{ 2 }, modules.size());
		ASSERT_EQUAL(std::string("alpha"), modules[0].name);
		ASSERT_EQUAL(std::string("beta"), modules[1].name);

		// A sibling module is reached through the package name; the import binds its last
		// segment, which is what the `using` then names.
		ASSERT_TRUE(modules[1].contents.contains("import shapes.alpha;\n"));
		ASSERT_TRUE(modules[1].contents.contains("using alpha.*;\n"));
		ASSERT_TRUE(modules[1].contents.contains("class struct_beta_box"));

		// `alpha` depends on nothing, so it imports nothing.
		ASSERT_EQUAL(false, modules[0].contents.contains("import "));

		const auto aggregate = emitAggregateModule("shapes", modules);
		ASSERT_TRUE(aggregate.contains("import shapes.alpha;\n"));
		ASSERT_TRUE(aggregate.contains("using beta.*;\n"));
	}

	void manifestTest() {
		const auto result
			= emitManifest(ManifestInput{ .package_name    = "mylib",
		                                  .version         = "1.0.0",
		                                  .links           = "/abs/mylib.o",
		                                  .dvm_shared_libs = { "/abs/libmylib.so" } });

		ASSERT_TRUE(result.error.empty());
		ASSERT_TRUE(result.yaml.contains("  name: mylib\n"));
		ASSERT_TRUE(result.yaml.contains("  version: '1.0.0'\n"));
		ASSERT_TRUE(result.yaml.contains("  links: '/abs/mylib.o'\n"));
		ASSERT_TRUE(result.yaml.contains("    - '/abs/libmylib.so'\n"));

		// A space would be split into separate linker arguments.
		const auto spaced = emitManifest(ManifestInput{ .package_name    = "mylib",
		                                                .version         = "1.0.0",
		                                                .links           = {},
		                                                .dvm_shared_libs = { "/abs/my lib.so" } });
		ASSERT_EQUAL(false, spaced.error.empty());
	}
};

TESTER_COMMON_MAIN("/src/tools/c_import/tests/c_import_emitter_test.cpp")
