PostCase: python3 check.py && @{cleanup_tmp_env}
PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo

Tests:
  duck/sync/basic:
    Description: can sync a new project
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
