Tests:
  debugger_cli_advanced:
    Run: "python3 runner.py @{build_dir}"
    TimeOut: 5 
    Cases:
      simple:
        Input:
          String: "simple.dbc" 
        Output:
          File: "simple.out"