PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  @{duck-exe} init bar
  @{duck-exe} -C foo sync
  @{duck-exe} -C bar sync

Tests:
  basic:
    Description: can get a list of venvs
    Cases:
      basic:
        Run: "@{expect_output} --out-regex \"@{stdout_regex}\" --err-regex \"@{stderr_regex}\" @{duck-exe} -C $DIT_TMP_DIR/foo list"
        stderr_regex: ""
        stdout_regex: 'bar:\n  last-location: $DIT_TMP_DIR/bar\n  last-access: @{date-regex}\n  last-modification: @{date-regex}\n  not ephemeral\n\nfoo:\n  last-location: $DIT_TMP_DIR/foo\n  last-access: @{date-regex}\n  last-modification: @{date-regex}\n  not ephemeral'
