Tests:
  while-test:
    Description: Minimal working dummy test.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "5\n4\n5\n4\n5\n4\n5\n4\n2\n1\n5\n4\n2\n1\n5\n4\n2\n1\n"
        ExitCode: 3

