
Tests:
  simple_class_templates:
    Cases:
      all:
        backend: all
        Output:
          String: "5\n3.14\n42\n"
        ExitCode: 0

  simple_function_template:
    Cases:
      all:
        backend: all
        Output:
          String: "2\n2\nabc\n"
        ExitCode: 0


  templates_and_macros:
    Cases:
      all:
        backend: all
        Output:
          String: "42\n42\n"
        ExitCode: 0

  more_templates:
    Cases:
      all:
        backend: all
        Output:
          String: "3\n3\n3\n"
        ExitCode: 0

