
Tests:
  simple_class_templates:
    # enable_conc_deterministic_tests: "false"
    Cases:
      all:
        backend: all
        Output:
          String: "10\n20\n15\n35\n15\n35\n"
        ExitCode: 0
