#pragma once

#include <base/collections/optional.hpp>

#include <string>
#include <string_view>

namespace compiler::helios::mangler {

	/**
	 * @brief Turns a mangled symbol name back into a human-readable one, e.g. `_Q_M8manglingG1A`
	 * becomes `mangling.A`.
	 *
	 * The result mirrors duckling's own spelling of things - dotted paths, `name(a: i32) -> i32`
	 * signatures and the type names printed by `tsh::SymbolType::toString` - so it is meant for
	 * humans (comments in generated bytecode, dumps, diagnostics). It is lossy and is not meant to
	 * be mangled back.
	 *
	 * @note Only the constructs the mangler actually emits are understood; see mangling-scheme.md
	 * for the parts that are still `@future` (back-references, punycode, template instantiations).
	 * @return The readable name, or an empty optional when the name was not produced by the mangler
	 * (e.g. a C-linkage symbol) or uses a construct this demangler cannot parse.
	 */
	base::Optional<std::string> tryDemangle(std::string_view mangled_name);

	/**
	 * @brief Same as tryDemangle, but returns `mangled_name` unchanged when it cannot be demangled.
	 */
	std::string demangle(std::string_view mangled_name);
}
