[project]
name = "common"
version = "0.1.0"
description = "Common code for Duckling package management"
readme = "README.md"
authors = [
    { name = "Ignacy Gębuś", email = "ig448499@students.mimuw.edu.pl" },
    { name = "Tymoteusz Kucharek", email = "tk448520@students.mimuw.edu.pl" },
    { name = "Stanisław Wiśniewski", email = "sw448598@students.mimuw.edu.pl" },
    { name = "Artur Wojtuszkiewicz", email = "aw448602@students.mimuw.edu.pl" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "./"
venv = ".venv/"
typeCheckingMode = "strict"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.7",
]
