PostCase: python3 check.py && @{cleanup_tmp_env}

PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo --expose-freezefile

Tests:
  exposed-freezefile:
    Description: can sync a new project which exposes a freezefile
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
