# Tests for static array types
Tests:
  simple_arrays:
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "100\n200\n300\n600\n20\n88888888\n42\n11\n13\n3.25\n"
        ExitCode: 0
