//! Layout of a generated C package on disk.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::recipe::CBindingsRecipe;
use super::resolve::Resolved;
use crate::{QuackResult, QuackResultContext};

/// Directory under `src/` owned by `duck translate-c regen`.
pub const GENERATED_DIR: &str = "generated";

const MANIFEST_HEADER: &str = "\
# Generated by `duck translate-c` for the C library installed on this machine. Regenerate it on
# each machine with `duck translate-c regen` rather than committing or sharing it.
# `metadata` is rewritten on every regen: change `c-bindings` instead.
";

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct ManifestMetadata {
    name: String,
    version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    links: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    dvm_shared_libs: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct GeneratedManifest {
    metadata: ManifestMetadata,
    c_bindings: CBindingsRecipe,
}

/// The parts of an existing generated package that a regen keeps.
pub struct ExistingPackage {
    pub name: String,
    pub version: String,
    pub recipe: CBindingsRecipe,
}

/// Paths inside a generated package rooted at `root`.
pub struct PackagePaths {
    pub root: PathBuf,
}

impl PackagePaths {
    pub fn manifest(&self) -> PathBuf {
        self.root.join("quackconfig.yaml")
    }

    pub fn src(&self) -> PathBuf {
        self.root.join("src")
    }

    pub fn generated(&self) -> PathBuf {
        self.src().join(GENERATED_DIR)
    }
}

/// Reads the name, version and recipe of the generated package at `paths`.
pub fn read_existing(paths: &PackagePaths) -> QuackResult<ExistingPackage> {
    let manifest = paths.manifest();
    let text = fs::read_to_string(&manifest)
        .with_context(|| format!("failed to read `{}`", manifest.display()))?;
    let parsed: GeneratedManifest = serde_yaml_ng::from_str(&text).with_context(|| {
        format!(
            "`{}` is not a package generated by `duck translate-c` (it needs `metadata` and `c-bindings`)",
            manifest.display()
        )
    })?;
    Ok(ExistingPackage {
        name: parsed.metadata.name,
        version: parsed.metadata.version,
        recipe: parsed.c_bindings,
    })
}

/// Writes `quackconfig.yaml` from the recipe and what it resolved to.
pub fn write_manifest(
    paths: &PackagePaths,
    name: &str,
    version: &str,
    recipe: &CBindingsRecipe,
    resolved: &Resolved,
) -> QuackResult<()> {
    let manifest = GeneratedManifest {
        metadata: ManifestMetadata {
            name: name.to_owned(),
            version: version.to_owned(),
            links: resolved.links.clone(),
            dvm_shared_libs: resolved.dvm_shared_libs.clone(),
        },
        c_bindings: recipe.clone(),
    };
    let yaml = serde_yaml_ng::to_string(&manifest).context("failed to serialize the manifest")?;
    write(&paths.manifest(), &format!("{MANIFEST_HEADER}{yaml}"))
}

/// Writes `src/src.dk` re-exporting the bindings, unless the package already has one: it belongs
/// to the user from then on.
pub fn write_root_module_if_missing(paths: &PackagePaths, name: &str) -> QuackResult<()> {
    let root_module = paths.src().join("src.dk");
    if root_module.exists() {
        return Ok(());
    }
    write(
        &root_module,
        &format!(
            "# Re-exports the generated bindings, so `import {name}.*;` reaches them. This file is \
             never\n# regenerated: helpers written here or in other files next to it are kept.\n\
             import {name}.{GENERATED_DIR}.{name}.*;\n"
        ),
    )
}

/// The main module of `src/generated/`, without which the directory is not a module.
pub fn generated_root_module(banner: &[String]) -> String {
    banner.iter().map(|line| format!("# {line}\n")).collect()
}

pub fn write(path: &Path, content: &str) -> QuackResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create `{}`", parent.display()))?;
    }
    fs::write(path, content).with_context(|| format!("failed to write `{}`", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_round_trips() {
        let dir = tempfile::tempdir().unwrap();
        let paths = PackagePaths {
            root: dir.path().to_path_buf(),
        };
        let recipe = CBindingsRecipe {
            headers: vec!["SDL3/SDL.h".into()],
            pkg_config: vec!["sdl3".into()],
            include: vec!["SDL_*".into()],
            ..Default::default()
        };
        let resolved = Resolved {
            links: Some("-lSDL3".into()),
            dvm_shared_libs: vec!["libSDL3.so.0".into()],
            ..Default::default()
        };
        write_manifest(&paths, "sdl3", "3.4.16", &recipe, &resolved).unwrap();

        let text = fs::read_to_string(paths.manifest()).unwrap();
        assert!(
            text.starts_with("# Generated by `duck translate-c`"),
            "{text}"
        );
        assert!(text.contains("dvm-shared-libs:"), "{text}");
        assert!(text.contains("pkg-config:"), "{text}");

        let existing = read_existing(&paths).unwrap();
        assert_eq!(existing.name, "sdl3");
        assert_eq!(existing.version, "3.4.16");
        assert_eq!(existing.recipe, recipe);
    }
}
