from collections import defaultdict
from dataclasses import dataclass

from treelib.tree import Tree

from quackpack.core.storage.files import VenvFreeze
from quackpack.core.storage.storage import get_freeze
from quackpack.core.types.package import Package
from quackpack.util.global_context import GlobalContext
from quackpack.util.logger import get_logger
from quackpack.util.types.pkgid import GitPackageId, LocalPackageId, PackageId

logger = get_logger(__name__)


@dataclass(frozen=True, kw_only=True)
class TreeOptions:
    ctx: GlobalContext

    source: Package
    """ 
    Project for which the dependency graph is to be shown.
    """

    max_depth: int | None
    """
    Maximal depth of the tree.
    """

    expand_visited: bool
    """
    Whether to display substrees for nodes which have already apeeared somewhere else.
    """


def _node_output(alias: str, node: PackageId, show_star: bool) -> str:
    if isinstance(node.inner, LocalPackageId):
        name = f"{alias} at {node.inner.path}"
    elif isinstance(node.inner, GitPackageId):
        name = f"{alias} from {node.inner.url} commit {node.inner.commit}"
    else:
        name = f"{node.inner.id} v{node.inner.version} from {node.inner.url}"
        if node.inner.id.root != alias:
            name += f" aliased {alias}"
    if show_star:
        name += " (*)"
    return name


type VisitsCounter = defaultdict[PackageId, int]


def _show_one_package(
    tree: Tree,
    depth: int,
    parent_tree_id: str,
    alias: str,
    node: PackageId,
    visits: VisitsCounter,
    opts: TreeOptions,
    freeze: VenvFreeze,
) -> None:
    visits[node] += 1

    # String shown to the user.
    node_output = _node_output(alias, node, not opts.expand_visited and visits[node] > 1)

    # Id in a tree to set parent atribute in create_node.
    node_tree_id = str(node) + f" {visits[node]}"

    tree.create_node(node_output, node_tree_id, parent=parent_tree_id)
    if (opts.max_depth is not None and depth == opts.max_depth) or (
        not opts.expand_visited and visits[node] > 1
    ):
        return
    for child_alias, child_id in freeze.dependencies[node].dependencies.items():
        _show_one_package(tree, depth + 1, node_tree_id, child_alias.root, child_id, visits, opts, freeze)


def tree(opts: TreeOptions) -> None:
    freeze = get_freeze(opts.ctx, opts.source)
    if freeze is None:
        opts.ctx.console.warn(
            "There is no freezefile generated by the package",
            "Run [cyan]qp sync[/cyan] to resolve the dependencies and create the freezefile",
        )
        return

    tree = Tree()
    visits: VisitsCounter = defaultdict(int)
    main_project_id = LocalPackageId(path=opts.source.package_root)
    visits[main_project_id.upcast()] = 1

    tree.create_node(str(opts.source.manifest.summary.name), str(main_project_id))
    for alias, package in freeze.direct_dependencies.items():
        _show_one_package(tree, 1, str(main_project_id), alias.root, package, visits, opts, freeze)

    opts.ctx.console.print(tree.show(stdout=False))
