PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo
  @{duck_exe} init foo_but_different_dir --name foo
  @{duck_exe} -C foo sync
Tests:
  sync:
    Description: 
    Cases:
      sync:
        test_cmd: duck -C foo_but_different_dir sync
        Err:
          Run: |+
            echo "error: tried to overwrite an existing virtual environment from another location
            
              Caused by:
                synchronizing the package at \`${DIT_TMP_DIR}/foo_but_different_dir\` would overwrite the venv of the package at \`${DIT_TMP_DIR}/foo\`

              Caused by:
                the packages share the same name \`foo\`
            
            hint: use \`--overwrite\` to force an overwrite"
        ExitCode: 1
        
