Tests:
  sync:
    Description: 
    Cases:
      sync:
        test_cmd: duck -C foo sync && duck -C foo_but_different_dir sync
        Err:
          Run: |+
            echo "error: tried to overwrite an existing virtual environment from another location
            
              Caused by:
                synchronizing the package at \`$(pwd)/foo_but_different_dir\` would overwrite the venv of the package at \`$(pwd)/foo\`

              Caused by:
                the packages share the same name \`foo\`
            
            hint: use \`--overwrite\` to force an overwrite"
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        ExitCode: 1
        
