from pathlib import Path
import re

from ...helpers import log_warning


# Temporary files generated by concurrent mode.
GENERATED_COPY_STEM_RE = re.compile(r"^concurrent_copy\d+_.+")

# We rewrite only the first module segment in import statements.
# Example: in `import foo.bar.baz` we match `foo`.
IMPORT_RE = re.compile(r"^(\s*import\s+)([A-Za-z_]\w*)(?=[\s\.;]|$)")

# We rename `fun main(...)` in temporary copies.
MAIN_FUN_RE = re.compile(r"(\bfun\s+)main(\s*\()")


def is_copy_file(path: Path) -> bool:
    return path.suffix == ".dmf" and GENERATED_COPY_STEM_RE.match(path.stem) is not None


def iter_original_dmf_files(package_dir: Path) -> list[Path]:
    return sorted([file for file in package_dir.rglob("*.dmf") if not is_copy_file(file)])


def get_child_module_names(main_module_file: Path) -> set[str]:
    parent_dir = main_module_file.parent
    main_name = main_module_file.stem
    child_names = set()

    for child in parent_dir.iterdir():
        if child.is_file() and child.suffix == ".dmf" and not is_copy_file(child):
            if child.stem != main_name:
                child_names.add(child.stem)
            continue

        if child.is_dir() and any(
            nested.suffix == ".dmf" and not is_copy_file(nested) for nested in child.rglob("*.dmf")
        ):
            child_names.add(child.name)

    return child_names


def rewrite_import_line_if_needed(
    line: str,
    main_module_name: str,
    child_module_names: set[str],
) -> str:
    newline = "\n" if line.endswith("\n") else ""
    line_without_newline = line[:-1] if newline else line

    match = IMPORT_RE.match(line_without_newline)
    if not match:
        return line

    first_segment = match.group(2)

    if first_segment not in child_module_names:
        return line

    if first_segment == main_module_name:
        return line

    first_segment_start, first_segment_end = match.span(2)
    rewritten = (
        f"{line_without_newline[:first_segment_start]}"
        f"{main_module_name}.{line_without_newline[first_segment_start:first_segment_end]}"
        f"{line_without_newline[first_segment_end:]}"
    )
    return f"{rewritten}{newline}"


def rewrite_for_copy(
    source_text: str,
    source_file: Path,
    copy_index: int,
    rename_main_in_copies: bool,
) -> str:

    # To make duplication work correctly, we do two things:
    # 1) rename main in copies to avoid "Multiple main functions" during linking,
    # 2) rewrite imports in copied main-module files from child imports to main.<child>
    #    so the copied file resolves children as its submodules instead of siblings.

    rewritten = source_text

    if rename_main_in_copies:
        rewritten = MAIN_FUN_RE.sub(rf"\1main_copy{copy_index}\2", rewritten)

    if source_file.stem != source_file.parent.name:
        return rewritten

    main_module_name = source_file.stem
    child_module_names = get_child_module_names(source_file)

    rewritten_lines = [
        rewrite_import_line_if_needed(
            line,
            main_module_name,
            child_module_names,
        )
        for line in rewritten.splitlines(keepends=True)
    ]
    return "".join(rewritten_lines)


def duplicate_package_modules(
    package_dir: Path,
    copy_count: int,
    rename_main_in_copies: bool,
) -> list[Path]:
    created_files: list[Path] = []

    if not package_dir.exists():
        log_warning(f"Package dir not found: {package_dir}")
        return created_files

    originals = iter_original_dmf_files(package_dir)
    for source_file in originals:
        source_text = source_file.read_text()
        sanitized_source_stem = source_file.stem.replace("-", "_")
        for copy_index in range(1, copy_count + 1):
            target = source_file.with_name(f"concurrent_copy{copy_index}_{sanitized_source_stem}.dmf")
            rewritten = rewrite_for_copy(
                source_text,
                source_file,
                copy_index,
                rename_main_in_copies,
            )
            target.write_text(rewritten)
            created_files.append(target)

    return created_files


def remove_files(paths: list[Path]):
    for file in reversed(paths):
        try:
            if file.exists():
                file.unlink()
        except OSError as error:
            log_warning(f"Failed to remove temp file '{file}': {error}")
