PostCase: '@{set_python_path} && python3 check.py'

Tests:
  sync:
    Description: can sync a project with flags
    Cases:
      sync:
        test_cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
