add_subdirectory(api)
add_subdirectory(bytecode)
add_subdirectory(core)
add_subdirectory(exceptions)
add_subdirectory(events)
add_subdirectory(loader)
add_subdirectory(services)
add_subdirectory(services_data)
set(vm_common_sources ${vm_common_sources} PARENT_SCOPE)
set(vm_config_dependent_sources ${vm_config_dependent_sources} PARENT_SCOPE)
