# Tests for declaration of functions in REPL

Tests:
  basic_declarations:
    Cases:
      basic_declarations:
        Input:
          File: "basic_declarations/basic_declarations.rtf"
        Output: 
          String : "@{beginning}\n=> 7\n@{end}"

  nested_calls:
    Cases:
      nested_calls:
        Input:
          File: "interactions/nested_calls.rtf"
        Output:
          String: "@{beginning}\n=> 42\n@{end}"
      resilience:
        Run: "@{duckc_path} repl --plain-output --custom-std-artifacts-path @{case_std_artifacts}"
        Input:
          File: "interactions/resilience.rtf"
        Output:
          String: "4\n4\n"
