# Tests for declaration of functions in REPL
# @TODO: Add an option to ignore eventual error.

Tests:
  basic_declarations:
    Cases:
      basic_declarations:
        Input:
          File: "basic_declarations/basic_declarations.rtf"
        Output: 
          String : "@{beginning}\n=> 7\n@{end}"

  nested_calls:
    Cases:
      nested_calls:
        Input:
          File: "interactions/nested_calls.rtf"
        Output:
          String: "@{beginning}\n=> 42\n@{end}"
      # resilience:
      #   Input:
      #     File: "interactions/resilience.rtf"
      #   Output:
      #     String: "@{beginning}\nduckling> => 4\nduckling> duckling> => 4\n@{end}"
