PostCase: python3 check.py && @{cleanup_tmp_env}

PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo
  @{duck_exe} init bar
  echo "dependencies:
    bar:
      source:
        path: ../bar
      features: [b]

  features:
    f: []" >> foo/quackconfig.yaml

  echo "features:
    b: []" >> bar/quackconfig.yaml

Tests:
  duck/sync/with-a-single-local-dep-and-flags2:
    Description: can sync a project with dependency, conditions and flags
    Cases:
      sync:
        test_cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
