# Test configuration for simple-chars
# Tests char type, escape sequences, char-to-integer conversion, and char comparisons

Tests:
  simple_chars_test:
    Description: Tests for char type.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "65\n90\n48\n57\n1\n2\n3\n4\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "65\n90\n48\n57\n1\n2\n3\n4\n"
        ExitCode: 0

  char_escapes_test:
    Description: Tests for char escape sequences.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "10\n9\n13\n92\n39\n34\n1\n2\n32\n3\n4\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "10\n9\n13\n92\n39\n34\n1\n2\n32\n3\n4\n"
        ExitCode: 0

  chars_borrowed_test:
    Description: Test taken straight from compiler tests directory.
    Cases:
      llvm:
        backend: llvm
        Input:
          String: "Xd;"
        Output:
          String: "Enter a character: The provided character is uppercase.\nIts lowercase counterpart is: x\nEnter a character: The provided character is lowercase.\nIts uppercase counterpart is: D\nEnter a character: The provided character is not a letter.\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Input:
          String: "Xd;"
        Output:
          String: "Enter a character: The provided character is uppercase.\nIts lowercase counterpart is: x\nEnter a character: The provided character is lowercase.\nIts uppercase counterpart is: D\nEnter a character: The provided character is not a letter.\n"
        ExitCode: 0
