name: Download duck dependencies
description: Download pkg-config and libsqlite3-dev
runs:
  using: composite
  steps:
    - name: Update apt
      shell: bash
      run: sudo apt update

    # Pkg-config is required for finding OpenSSL on Linux.
    - name: Download pkg-config
      shell: bash
      run: sudo apt -y install pkg-config

    # We don't (yet) bundle SQLite with duck.
    - name: Download libsqlite3-dev
      shell: bash
      run: sudo apt -y install libsqlite3-dev