name: Download duck dependencies
description: Download pkg-config and libsqlite3-dev
runs:
  using: composite
  steps:
    - name: Update apt
      shell: bash
      run: sudo apt update

    # Pkg-config is required for finding OpenSSL on Linux.
    - name: Download pkg-config
      shell: bash
      run: sudo apt -y install pkg-config

    # We don't (yet) bundle SQLite with duck.
    - name: Download libsqlite3-dev
      shell: bash
      run: sudo apt -y install libsqlite3-dev

    # Russcip needs this
    - name: Download libgfortran5
      shell: bash
      run: sudo apt -y install libgfortran5

    - name: Download sccache
      shell: bash
      run: sudo apt -y install sccache

    - name: Setup sccache environment
      shell: bash
      run: |
        echo 'RUSTC_WRAPPER=sccache' >> "$GITHUB_ENV"
        echo "SCCACHE_DIR=${{ github.workspace }}/.cache/sccache" >> "$GITHUB_ENV"
        echo 'SCCACHE_CACHE_SIZE=1G' >> "$GITHUB_ENV"
