PostCase: python3 check.py

Tests:
  init:
    Description: can initialise a new project with --no-git flag
    Cases:
      init:
        test_cmd: duck init --no-git foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`"
