#pragma once

#include <base/types/floats.hpp>

#include <string_id/string_id.hpp>

#include <vm/bytecode/opcode_args.hpp>
#include <vm/bytecode/type_of_data.hpp>

#include <utility>

namespace compiler::backend_vm::internal {
	struct DVMLocal {
		base::StrID          name;
		vm::code::TypeOfData type;

		bool operator==(const DVMLocal& other) const = default;
		operator vm::opargs::OpCodeArg() const;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
		[[nodiscard]] vm::opargs::OpCodeArg asAnyArgument() const;
	};

	struct DVMGlobal {
		base::StrID          name;
		vm::code::TypeOfData type;

		bool operator==(const DVMGlobal& other) const = default;
		operator vm::opargs::OpCodeArg() const;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
		[[nodiscard]] vm::opargs::OpCodeArg asAnyArgument() const;
	};

	struct DVMImmediate {
		DVMImmediate(u64 value, vm::code::TypeOfData type);
		// @TODO: #2451: Make DVMImmediate string based
		static DVMImmediate usgn8(u8 value);
		static DVMImmediate usgn16(u16 value);
		static DVMImmediate usgn32(u32 value);
		static DVMImmediate usgn64(u64 value);
		static DVMImmediate sgn8(i8 value);
		static DVMImmediate sgn16(i16 value);
		static DVMImmediate sgn32(i32 value);
		static DVMImmediate sgn64(i64 value);
		static DVMImmediate flt32(f32 value);
		static DVMImmediate flt64(f64 value);
		static DVMImmediate boolean(bool value);
		static DVMImmediate character(char value);

		// All values are represented as u64, so e.g. a float is bit-casted to u64.
		u64                  value{};
		vm::code::TypeOfData type;
		bool                 operator==(const DVMImmediate& other) const = default;
		operator vm::opargs::OpCodeArg() const;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
	};

	struct DVMLabel {
		base::StrID name;

		bool operator==(const DVMLabel& other) const = default;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
	};

	struct DVMFunctionName {
		base::StrID name;

		bool operator==(const DVMFunctionName& other) const = default;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
	};

	struct DVMExternCFunctionName {
		base::StrID name;
		bool        operator==(const DVMExternCFunctionName& other) const = default;

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
	};

	using DVMCallable = std::variant<DVMFunctionName, DVMExternCFunctionName>;

	/**
	 * @brief Structure representing a place (L-value) in the generated DVM bytecode.
	 * This structure is an abstraction layer over a place in generated bytecode. Place in DVM can
	 * either mean:
	 * - Direct reference to a local stack variable - for which the AccessKind field will be set to
	 *  Direct.
	 * - Direct reference to a global variable - for which the AccessKind field will be set to
	 * Direct.
	 * - A pointer to the place - for which the AccessKind field will be set to `Pointer`. This
	 * handles cases like:
	 * 		- some_int_reference = 123 - DVMPlace stores a local variable storing a pointer to the
	 * 		  original address that the reference stores.
	 * 		- class.field = 123 - DVMPlace stores a local variable storing a pointer to the exact
	 * offset at which the `field` is located in `class`.
	 * 		- array[3] = 123 - DVMPlace stores a local variable storing a pointer to the exact
	 * offset at which the third element of the array is located.
	 *
	 * If the access kind is set to `Direct`, a load into the place will be performed by `mov_X_X`.
	 * If the access kind is set to `Pointer`, a load into the place will be performed by
	 * `store_lptr_lany`.
	 */
	class DVMPlace {
	private:
		using StoredValueVariant = std::variant<DVMLocal, DVMGlobal>;

	public:
		enum class AccessKind : uint8_t { Direct, Pointer };

		DVMPlace(StoredValueVariant value, AccessKind access_kind):
			  stored_place(std::move(value)),
			  access_kind(access_kind) {}

		bool operator==(const DVMPlace& other) const = default;
		operator vm::opargs::OpCodeArg() const;

		[[nodiscard]] bool isDirect() const { return access_kind == AccessKind::Direct; }

		[[nodiscard]] vm::code::TypeOfData getType() const;

		void setAccessKind(AccessKind kind) { access_kind = kind; }

		template<class T>
		[[nodiscard]] bool is() const {
			return std::holds_alternative<T>(stored_place);
		}

		template<class T>
		[[nodiscard]] T get() const {
			return std::get<T>(stored_place);
		}

		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;
		[[nodiscard]] vm::opargs::OpCodeArg asAnyArgument() const;

	private:
		StoredValueVariant stored_place;
		AccessKind         access_kind;
	};

	class DVMValue {
		using StoredValueVariant
			= std::variant<DVMPlace, DVMImmediate, DVMLabel, DVMFunctionName, DVMExternCFunctionName>;

		StoredValueVariant stored_value;

	public:
		DVMValue(StoredValueVariant value): stored_value(std::move(value)) {}

		DVMValue(DVMLocal local, DVMPlace::AccessKind access_kind):
			  stored_value(DVMPlace(local, access_kind)) {}

		DVMValue(DVMGlobal global, DVMPlace::AccessKind access_kind):
			  stored_value(DVMPlace(global, access_kind)) {}

		bool operator==(const DVMValue& other) const = default;

		operator vm::opargs::OpCodeArg() const;

		[[nodiscard]] vm::code::TypeOfData getType() const;

		/**
		 * @brief Converts the DVMValue into it's typed argument representation.
		 */
		[[nodiscard]] vm::opargs::OpCodeArg asArgument() const;

		/**
		 * @brief Converts the DVMValue into it's untyped local/global argument
		 * representation(`lany`, `gany`). Should be used only when working with `store_X_X`,
		 * `load_X_X`, `ref_X_X` instructions.
		 * Panics if the DVMValue can't be converted into an any argument, e.g. Is an Immediate,
		 * Label or a Function.
		 */
		[[nodiscard]] vm::opargs::OpCodeArg asAnyArgument() const;

		template<class T>
		[[nodiscard]] bool is() const {
			using Tp = std::decay_t<T>;
			// Simple forward to check if the DVMValue stores a DVMPlace and it's a DVMLocal/DVMGlobal.
			if constexpr (base::IsOneOf<Tp, DVMLocal, DVMGlobal>) {
				variant_match(stored_value) {
					variant_case(DVMPlace, place) return place.is<T>();
					variant_default return false;
				}
			} else {
				return std::holds_alternative<T>(stored_value);
			}
		}

		template<class T>
		[[nodiscard]] T get() const {
			using Tp = std::decay_t<T>;
			// Simple forward to check if the DVMValue stores a DVMPlace and it's a DVMLocal/DVMGlobal.
			if constexpr (base::IsOneOf<Tp, DVMLocal, DVMGlobal>) {
				variant_match(stored_value) {
					variant_case(DVMPlace, place) return place.get<T>();
					variant_default CORE_PANIC("Bad type in DVMValue");
				}
			} else {
				return std::get<T>(stored_value);
			}
		}
	};
}
