PostCase: "(python3 check.py; rm -r foo) && : || false"

Tests:
  init:
    Description: can initialise a new project with different venvconfig flags
    Cases:
      expose_freezefile:
        test_cmd: |+
          init --expose-freezefile foo &&
          cd foo &&
          git rev-parse --show-toplevel &&
          cat venvconfig.yaml
        Output:
          Run: |+
            printf "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`\n$(pwd)/foo\nexpose_freezefile: true\n"
      ephemeral:
        test_cmd: |+
          init --ephemeral foo &&
          cd foo &&
          git rev-parse --show-toplevel &&
          cat venvconfig.yaml
        Output:
          Run: |+
            printf "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`\n$(pwd)/foo\nephemeral: true\n"
      local_storage:
        test_cmd: |+
          init --local-storage foo &&
          cd foo &&
          git rev-parse --show-toplevel &&
          cat venvconfig.yaml
        Output:
          Run: |+
            printf "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`\n$(pwd)/foo\nlocal_storage: storage\n"