Tests:
  init:
    Description: can initialise a new project with different venvconfig flags
    Cases:
      expose_freezefile:
        test_cmd: duck init --expose-freezefile foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        PostCase: python3 check.py expose_freezefile && @{cleanup_tmp_env}
      ephemeral:
        test_cmd: duck init --ephemeral foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        PostCase: python3 check.py ephemeral && @{cleanup_tmp_env}
      local_storage:
        test_cmd: duck init --local-storage foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$DIT_TMP_DIR/foo\`"
        PostCase: python3 check.py local_storage && @{cleanup_tmp_env}
