Tests:
  init:
    Description: can initialise a new project with different venvconfig flags
    Cases:
      expose_freezefile:
        test_cmd: duck init --expose-freezefile foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`"
        PostCase: python3 check.py expose_freezefile
      ephemeral:
        test_cmd: duck init --ephemeral foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`"
        PostCase: python3 check.py ephemeral
      local_storage:
        test_cmd: duck init --local-storage foo
        Output:
          Run: |+
            echo "info: successfully created a new project \`foo\` at \`$(pwd)/foo\`"
        PostCase: python3 check.py local_storage
