# Tests for reference types
Tests:
  simple_refs:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "42\n11\n13\n11\n123\n234\n357\n-123\n357\n-357\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "42\n11\n13\n11\n123\n234\n357\n-123\n357\n-357\n"
        ExitCode: 0
  not_so_simple_refs:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "10\n20\n20\n20\n345\n345\n456\n123\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "10\n20\n20\n20\n345\n345\n456\n123\n"
        ExitCode: 0
  global_refs:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "999\n999\n888\n888\n999\n888\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "999\n999\n888\n888\n999\n888\n"
        ExitCode: 0
  records:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "1\n42\n123\n456\n0\n1\n10\n20\n777\n888\n"
        ExitCode: 0
  overload_resolution:
    Cases: 
      llvm:
        backend: llvm
        Output:
          String: "2\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "2\n"
        ExitCode: 0
