# Test configuration for while-loops
# Tests while loops with named loops, break, continue, and performance

Tests:
  while_test:
    Description: Tests for while loops with named loops, break, and continue.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "5\n4\n5\n4\n5\n4\n5\n4\n2\n1\n5\n4\n2\n1\n5\n4\n2\n1\n"
        ExitCode: 0
      dvm:
        backend: dvm
        Output:
          String: "5\n4\n5\n4\n5\n4\n5\n4\n2\n1\n5\n4\n2\n1\n5\n4\n2\n1\n"
        ExitCode: 0
  loops_performance:
    Description: Performance test for while loops.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "20\n100000001\n"
        ExitCode: 0
        TimeOut: 1
      dvm:
        backend: dvm
        Output:
          String: "20\n100000001\n"
        ExitCode: 0
        TimeOut: 1

