Tests:
  invalid-name:
    Description: cannot initialise a project with an invalid name
    Cases:
      init:
        test-cmd: duck init foo!
        ExitCode: 1
        Err:
          Run: |+
            echo "error: cannot create a project with an invalid inferred name \`foo!\`

              Caused by:
                package name \`foo!\` contains an illegal character \`!\`"
  std-name:
    Description: can initialise a project with a std name
    Cases:
      init:
        test-cmd: duck init std
        ExitCode: 0
        Err:
          String: "warning: initializing a project with name \\`std\\` can have weird effects, as it's one of the packages from the Duckling standard library\n"
        Output:
          Run: |+
            echo "info: successfully created a new project \`std\` at \`$DIT_TMP_DIR/std\`"

  keyword:
    Description: can initialise a project with a keyword name
    Cases:
      init:
        test-cmd: duck init self
        ExitCode: 0
        Err:
          String: "warning: initializing a project with name \\`self\\` can have weird effects, as it's a Duckling keyword\n"
        Output:
          Run: |+
            echo "info: successfully created a new project \`self\` at \`$DIT_TMP_DIR/self\`"
