PostCase: python3 check.py
PreCase: |+
  cd $DIT_TMP_DIR
  @{duck_exe} init foo
  echo "features:
    cycle: [cycle]" >> foo/quackconfig.yaml
Tests:
  sync:
    Description: can sync a project with features cycle
    Cases:
      sync:
        test_cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
