PostCase: python3 check.py && @{cleanup_tmp_env}
PreCase: |+
  @{cd-tmp-dir}
  @{duck-exe} init foo
  echo "features:
    cycle: [cycle]" >> foo/quackconfig.yaml
Tests:
  duck/sync/project-with-a-cycle-in-flags:
    Description: can sync a project with features cycle
    Cases:
      sync:
        test-cmd: duck -C foo sync
        Output:
          String: 'info: successfully synchronized venv \`foo\`\n'
        
