# Integration tests for scripts in Duckling.

mode: "direct"
folder: "."

duckc_path: "@{build_dir}/bin/duckc"
dvm_path: "@{build_dir}/bin/VM"
clean_cmd: "rm -rf @{folder}/duck_build"

Clean: "@{clean_cmd}"

PreCase: "
  @{clean_cmd};
  if [ '@{mode}' = 'vm' ]; then
    cd @{folder} && @{duckc_path} compile_script @{Name}.ds --dvm-backend;
  fi"

Run: "
  if [ '@{mode}' = 'vm' ]; then
    @{dvm_path} run @{folder}/duck_build/@{Name}.dbc;
  else
    @{duckc_path} run @{folder}/@{Name}.ds;
  fi"

SubDirs:
  - basic_tests
