name: docs

concurrency:
  # This workflow runs only on main branch, so no need to distinguish between PRs.
  # github.workflow refers to the name of the workflow. "docs" in this case.
  # new run of the workflow from the same group will cancel the previous ones
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.md'
      - 'dev/docs/**'

env:
  DEV_DIR: ${{ github.workspace }}/dev
  BUILD_DIR: ${{ github.workspace }}/dev/build
  DOCS_DIR: ${{ github.workspace }}/dev/build/docs/config
  WWW_HOST: ducktype.org

jobs:
  docs:
    if: github.repository == 'ducktype-org/duckling'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.READ_DOCS_REPOS_PAT }}
          submodules: true

      - name: Install dependencies
        run: sudo apt -y install doxygen graphviz llvm-19 llvm-19-dev clang-19

      - name: Create Python virtual environment
        working-directory: ${{ env.DEV_DIR }}
        run: |
          python3 -m venv .venv
          .venv/bin/python3 -m pip install -r requirements.txt

      - name: Create build directory
        working-directory: ${{ env.DEV_DIR }}
        run: |
          source .venv/bin/activate
          cmake \
           -B ${{ env.BUILD_DIR }} \
           -D BUILD_DOCS=ON \
           -D CMAKE_BUILD_TYPE=Debug

      - name: Build docs
        working-directory: ${{ env.DEV_DIR }}
        run: cmake --build ${{ env.BUILD_DIR }} -- docs

      - name: Build search engine databse
        working-directory: ${{ env.DOCS_DIR }}
        run: |
          doxyindexer doxygen/searchdata.xml
          mkdir search-engine
          mv doxysearch.db search-engine/

      # Prepare ssh key for secure connection to server.
      # Save the key to a file, set permissions.
      # Adding the server's host key to the known_hosts file
      # to avoid the prompt for confirmation and check the server's identity.
      - name: Prepare ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WWW_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.WWW_SERVER_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # Move "doxygen" to specified directory on server.
      # The destination directory is ignored by the server and preconfigured one is used.
      # rsync is a tool for syncing files between two locations and avoiding
      # unnecessary copying.
      # -a: archive mode, preserves permissions, timestamps, enables recursion,
      # -z: compresses data during transfer,
      # -h: human readable output,
      # -c: checksum, compares files based on checksums,
      # -v: verbose output.
      - name: Upload to server
        working-directory: ${{ env.DOCS_DIR }}
        run: |
          rsync -azhcv -e 'ssh -p 222  -i ~/.ssh/id_rsa' \
          doxygen \
          search-engine \
          ${{ secrets.WWW_LOGIN }}@${{ env.WWW_HOST }}:/home/
