name: Linker Benchmark

on:
  pull_request:
env:
  # @note: boolean variables evaluate to true/false string, but github expressions treat
  # all non-empty strings as true, so one must use `evn.abc == 'true'` to actually use
  # them im conditional statements.
  # (this apply to all variables, not just the ones form here)
  WORKSPACE: ${{ github.workspace }}/dev
  BUILD_DIR: ${{ github.workspace }}/dev/build
  CCACHE_DIR: ${{ github.workspace }}/dev/.ccache
  CXX_COMPILER: g++-14
  CC_COMPILER: gcc-14
  GCOV_VERSION: gcov-14

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linker: [DEFAULT, LLD, MOLD]
        build-type: [Debug, Release]

    steps:
      - name: Set number of threads
        id: set-jobs
        run: echo "jobs=2" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LLVM
        run: sudo apt -y install llvm-19 llvm-19-dev

      - name: Install GCC 14 and gcov-14
        run: |
          sudo apt update
          sudo apt install -y ${{ env.CC_COMPILER }} ${{ env.CXX_COMPILER }} # gcov is included in gcc package

      - name: Check installations
        run: |
          ${{ env.CXX_COMPILER }} --version
          ${{ env.CC_COMPILER }} --version
          cmake --version

      - name: Install linker
        run: |
          if [ "${{ matrix.linker }}" = "DEFAULT" ]; then
            echo "Skipping linker installation (default)"
          else
            echo "Installing ${{ matrix.linker }}..."
            START=$(date +%s)

            sudo apt update
            if [ "${{ matrix.linker }}" = "MOLD" ]; then
              sudo apt install -y mold
            elif [ "${{ matrix.linker }}" = "LLD" ]; then
              sudo apt install -y lld
            fi

            END=$(date +%s)
            echo " Installation of ${{ matrix.linker }} took $((END - START)) seconds"
      
      # Remove ccache folder for better benchmark
      - name: Remove ccache
        id: ccache-rm
        run: rm -rf ${CCACHE_DIR}

      - name: Configure CMake
        working-directory: ${{ env.WORKSPACE }}
        run: |
          cmake \
              -B ${{ env.BUILD_DIR }} \
              -D CMAKE_CXX_COMPILER=${{ env.CXX_COMPILER }} \
              -D CMAKE_C_COMPILER=${{ env.CC_COMPILER }} \
              -D BUILD_DOCS=OFF \
              -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} \
              -D DOWNLOAD_UBUNTU_ICU_BUILD=ON \
              -D CMAKE_LINKER_TYPE=${{ matrix.linker }}
        # DEFAULT is treated as "no linker override"

      - name: Build tests
        working-directory: ${{ env.WORKSPACE }}
        run: |
          echo "Linker: ${{ matrix.linker }}"
          echo "Build type: ${{ matrix.build-type }}"
          echo "Starting build..."
          time cmake --build ${{ env.BUILD_DIR }} -j ${{ steps.set-jobs.outputs.jobs }} -- build_all_tests

