name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create compile_commands
        run: |
         cd dev
         cmake -DCMAKE_CXX_COMPILER=g++-11 -D BUILD_DOCS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
         cd ..
        shell: bash
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          version: '17'
          lines-changed-only: 'true'
          database: "dev"
          # The following value will only update a single comment
          # in a pull request's thread. Set it to false to disable the comment.
          # Set it to true to post a new comment (and delete the old comment).
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        #run: echo "Some files failed the linting checks!"
        # for actual deployment
        run: exit 1
