name: tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
  workflow_dispatch:

env:
  # @note: boolean variables evaluate to true/false string, but github expressions treat
  # all non-empty strings as true, so one must use `evn.abc == 'true'` to actually use
  # them im conditional statements.
  # (this apply to all variables, not just the ones form here)
  WORKSPACE: ${{ github.workspace }}/dev
  BUILD_DIR: ${{ github.workspace }}/dev/build
  CCACHE_DIR: ${{ github.workspace }}/dev/.ccache
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  IF_MAIN_PR: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'}}

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]  # (Release, Debug, RelWithDebInfo, etc.)
      fail-fast: false

    outputs:
      # @note: with matrix runs, each run works with the same output,
      # and they will overwrite each other
      # see: https://github.com/orgs/community/discussions/26639
      #
      # According to: https://github.com/orgs/community/discussions/38088
      # it should not override if the step if skipped.
      coverage-value: ${{ steps.test-coverage.outputs.coverage-percent }}

    timeout-minutes: 12  # (Per matrix run)

    runs-on: ubuntu-24.04

    env:
      COVERAGE_ENABLED: ${{ matrix.build-type == 'Debug' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lcov and LLVM
        if: ${{ env.COVERAGE_ENABLED == 'true' }}
        run: sudo apt -y install lcov llvm llvm-dev

      - name: Install ccache
        working-directory: ${{ env.WORKSPACE }}
        run: ./toolbox.py download-binaries -s ccache

      # Generate a timestamp and save it to a variable.
      # Timestamp is appended to the key in caching, so each cache has a unique key.
      # This step is arbitrary, and has nothing to the order of choosing the most
      # recent hash.
      - name: Prepare cache timestamp
        id: cache-timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H::%M::%S" UTC)
          file(APPEND "$ENV{GITHUB_OUTPUT}" "timestamp=${current_date}")

      # Cache local branch and on miss fallback to main branch's cache. In case
      # main branch misses, fallback to any branch's cache.
      - name: Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}-${{ steps.cache-timestamp.outputs.timestamp }}
          # If there is no match with the key, then it tries to partially
          # match with any of restore-keys (top to bottom).
          # Most recent entry is used when multiple match to the same key.
          # See readme for details.
          restore-keys : |
            ${{ runner.os }}-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}
            ${{ runner.os }}-build-${{ matrix.build-type }}-main
            ${{ runner.os }}-build-${{ matrix.build-type }}

      # Remove ccache folder to prevent cache snowball growth
      - name: Remove ccache on main
        if: ${{ env.BRANCH_NAME == 'main' }}
        id: ccache-main-rm
        run: rm -rf ${CCACHE_DIR}

      # Enables coverage only in case of Debug build.
      - name: Additional CMake flags
        id: cmake-flags
        # Env here is used for readability only
        env:
          flags: ${{ env.COVERAGE_ENABLED == 'true' && '-D ENABLE_COVERAGE=ON' || '' }}
        run: echo flags=${{ env.flags }} >> $GITHUB_OUTPUT

      - name: Configure CMake
        working-directory: ${{ env.WORKSPACE }}
        run: |
          cmake \
              -B ${{ env.BUILD_DIR }} \
              -D CMAKE_CXX_COMPILER=g++-13 \
              -D BUILD_DOCS=OFF \
              -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} \
              -D DOWNLOAD_UBUNTU_ICU_BUILD=ON \
              -D USE_CCACHE=ON \
              ${{ steps.cmake-flags.outputs.flags }}

      - name: Build tests
        working-directory: ${{ env.WORKSPACE }}
        run: cmake --build ${{ env.BUILD_DIR }} -j 2 -- build_all_tests

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build ${{ env.BUILD_DIR }} -- test

      - name: Test Coverage
        id: test-coverage
        if: ${{ env.COVERAGE_ENABLED == 'true' }}
        working-directory: ${{ env.WORKSPACE }}
        run: |
          cmake --build ${{ env.BUILD_DIR }} -- coverage
          echo coverage-percent=$(python3 ${{ env.WORKSPACE }}/scripts/cmake/coverage_info_parser.py ${{ env.BUILD_DIR }}/coverage/index.html) > $GITHUB_OUTPUT

      # Source:  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
      # This step deletes all the cache entries that are related to this branch,
      # and it is done in this moment in the script, right after building, because
      # upload of the current build happens after everything
      # else has finished, so there will be a cache entry ready for pulling.
      - name: Cleanup previous Cache entries for this branch
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            if [[ $cacheKey == ${{ runner.os }}-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}* ]]; then
              gh actions-cache delete $cacheKey -R $REPO --confirm
            fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.CACHE_DEL_PAT }}  # This env variable is used by the GH tool.
          REPO: ${{ github.repository }}

  coverage:
    needs: [build]

    runs-on: ubuntu-24.04

    timeout-minutes: 2

    steps:
      - name: Save main coverage percentage
        uses: action-pack/set-variable@v1
        if: ${{ env.BRANCH_NAME == 'main' }}
        with:
          name: 'MAIN_COVERAGE_VALUE'
          value: ${{ needs.build.outputs.coverage-value }}
          token: ${{ secrets.QUACKER_PAT }}

      - name: Read main coverage percentage
        id: read-main-coverage
        run: echo value=${{ vars.MAIN_COVERAGE_VALUE }} > $GITHUB_OUTPUT

      - name: Check coverage status
        id: check-coverage-status
        run: echo success=${{ needs.build.outputs.coverage-value >= steps.read-main-coverage.outputs.value }} > $GITHUB_OUTPUT

      - name: Hide previous bot comments
        if: ${{ env.IF_MAIN_PR == 'true' }}
        uses: int128/hide-comment-action@v1
        with:
          token: ${{ secrets.QUACKER_PAT }}
          authors: quacker-bot

      - name: Post coverage status as github comment
        uses: actions/github-script@v7
        if: ${{ env.IF_MAIN_PR == 'true' }}
        env:
          FAIL_MSG: '❌❌❌ - **You have to write some more tests, so the coverage is at least as high as on the main branch!** \n\n 🆘 Run coverage tests: `./toolbox.py coverage` to get more information.'
          SUCC_MSG: '✅✅✅ - **Great job writing tests!**'
        with:
          github-token: ${{ secrets.QUACKER_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 Tests and coverage ran successfully! 🎉\n \
                     ⭐ Lines covered on the **current** branch: **${{ needs.build.outputs.coverage-value }}%** \n \
                     ⭐ Lines covered on the main branch: ${{ steps.read-main-coverage.outputs.value }}% \n \
                     ${{ steps.check-coverage-status.outputs.success == 'true' && env.SUCC_MSG || env.FAIL_MSG }}'
            })

      - name: Fail if insufficient coverage
        if: ${{ steps.check-coverage-status.outputs.success != 'true' && env.IF_MAIN_PR == 'true' && (! contains(github.event.pull_request.labels.*.name, 'Override Coverage Check'))}}
        run: exit 1
