name: tests-clang

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  WORKSPACE: ${{ github.workspace }}/dev
  BUILD_DIR: ${{ github.workspace }}/dev/build
  CCACHE_DIR: ${{ github.workspace }}/dev/.ccache
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  CXX_COMPILER: clang++-19
  CC_COMPILER: clang-19
  BUILD_SYSTEM: Ninja

jobs:
  determine-runners:
    if: github.event.pull_request.draft == false
    permissions: {}
    uses: ./.github/workflows/determine-runners.yml
    with:
      self-hosted-labels: '["debug", "release"]'
      github-labels: '["ubuntu-24.04", "ubuntu-24.04"]'
    secrets: inherit

  build:
    if: github.event.pull_request.draft == false
    needs: determine-runners
    permissions:
      contents: read

    strategy:
      matrix:
        build-type: [Dev, DevOpt]
      fail-fast: false

    timeout-minutes: 25  # (Per matrix run)
    runs-on: ${{ matrix.build-type == 'Dev' && fromJson(needs.determine-runners.outputs.runners)[0] || fromJson(needs.determine-runners.outputs.runners)[1] }}

    steps:
      - name: Set self-hosted flag
        id: set-self-hosted
        run: |
          if [[ "${{ matrix.build-type }}" == "Dev" && "$(echo '${{ needs.determine-runners.outputs.runners }}' | jq -r '.[0].group')" == "SelfHostedRunners" ]]; then
            echo "is-self-hosted=true" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.build-type }}" == "DevOpt" && "$(echo '${{ needs.determine-runners.outputs.runners }}' | jq -r '.[1].group')" == "SelfHostedRunners" ]]; then
            echo "is-self-hosted=true" >> $GITHUB_OUTPUT
          else
            echo "is-self-hosted=false" >> $GITHUB_OUTPUT
          fi

      - name: Set number of threads
        id: set-jobs
        run: |
          if [[ "${{ steps.set-self-hosted.outputs.is-self-hosted }}" == "true" ]]; then
            echo "jobs=4" >> $GITHUB_OUTPUT
          else
            echo "jobs=2" >> $GITHUB_OUTPUT
          fi

      - name: Clean workspace (self-hosted only)
        if: ${{ steps.set-self-hosted.outputs.is-self-hosted == 'true' }}
        run: |
          echo "Cleaning up workspace on self-hosted runner..."
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}
          echo "Workspace cleaned."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt update

      - name: Install LLVM
        run: sudo apt -y install llvm-19 llvm-19-dev

      - name: Install clang
        # clang-tools-19 provides clang-scan-deps-19, required for C++20 modules support in CMake
        run: sudo apt -y install clang-19 clang-tools-19

      - name: Install xxd
        # Necessary to embed LLVM bitcode into duckc source files.
        run: sudo apt -y install xxd

      - name: Install Ninja
        run: sudo apt -y install ninja-build

      - name: Install Valgrind
        run: sudo apt -y install valgrind

      - name: Setup duck dependencies
        uses: ./.github/actions/setup-duck-dependencies/

      - name: Check installations
        run: |
          ${{ env.CXX_COMPILER }} --version
          ${{ env.CC_COMPILER }} --version

      - name: Install ccache
        working-directory: ${{ env.WORKSPACE }}
        run: ./toolbox.py download-binaries -s ccache

      - name: Prepare cache timestamp
        id: cache-timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H::%M::%S" UTC)
          file(APPEND "$ENV{GITHUB_OUTPUT}" "timestamp=${current_date}")

      - name: Restore build cache
        id: restore-build-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-clang-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}-${{ steps.cache-timestamp.outputs.timestamp }}
          restore-keys : |
            ${{ runner.os }}-clang-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}
            ${{ runner.os }}-clang-build-${{ matrix.build-type }}-main
            ${{ runner.os }}-clang-build-${{ matrix.build-type }}

      - name: Remove ccache on main
        if: ${{ env.BRANCH_NAME == 'main' }}
        id: ccache-main-rm
        run: rm -rf ${CCACHE_DIR}

      - name: Configure CMake
        working-directory: ${{ env.WORKSPACE }}
        run: |
          CTEST_PARALLEL_LEVEL=${{ steps.set-jobs.outputs.jobs }} \
          cmake \
              -B ${{ env.BUILD_DIR }} \
              -G ${{ env.BUILD_SYSTEM }} \
              -D CMAKE_CXX_COMPILER=${{ env.CXX_COMPILER }} \
              -D CMAKE_C_COMPILER=${{ env.CC_COMPILER }} \
              -D BUILD_DOCS=OFF \
              -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} \
              -D DOWNLOAD_UBUNTU_ICU_BUILD=ON \
              -D USE_CCACHE=ON \
              -D STRIP_SYMBOL_INFORMATION=ON

      - name: Build tests
        working-directory: ${{ env.WORKSPACE }}
        run: |
          cmake                                 \
          --build ${{ env.BUILD_DIR }}          \
          -j ${{ steps.set-jobs.outputs.jobs }} \
          --                                    \
          build_all_tests

      - name: Show disk usage
        working-directory: ${{ env.WORKSPACE }}
        run: |
          echo "build:"
          du -hs ${{ env.BUILD_DIR }}

          echo "build/lib:"
          du -hs ${{ env.BUILD_DIR }}/lib

          echo "build/bin:"
          du -hs ${{ env.BUILD_DIR }}/bin

          echo "ccache:"
          du -hs ${{ env.CCACHE_DIR }}

      - name: Cleanup previous Cache entries for this branch
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            if [[ $cacheKey == ${{ runner.os }}-clang-build-${{ matrix.build-type }}-${{ env.BRANCH_NAME }}* ]]; then
              gh actions-cache delete $cacheKey -R $REPO --confirm
            fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.CACHE_DEL_PAT }}  # This env variable is used by the GH tool.
          REPO: ${{ github.repository }}

      - name: Save build cache
        id: save-build-cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build ${{ env.BUILD_DIR }} -- test_parallel

      - name: Integration Tests
        id: integration-tests
        working-directory: ${{ env.WORKSPACE }}
        run: ./toolbox.py itest -b ${{ env.BUILD_DIR }}
