# Test configuration for io-builtins
# Tests builtin output functions and print function

Tests:
  io-builtins-output:
    Description: printing number types and strings.
    Cases:
      llvm:
        backend: llvm
        Output:
          String: "42\n15\n6\t8\nhello\n"
        ExitCode: 0
